### ISSUE TITLE
編集Wikiを編集する場合はadminじゃなくて各自のアカウントでログインして編集するようにする

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#105]
see https://github.com/rubima/rubima/issues/11#issuecomment-16175500
adminからアカウントを各自作ってもらう感じでしょうか。
編集MLで告知したほうがいいですね（手順書が必要？）。

**Comment by hsbt** [comment]
手順書いて、各自作ってもらう、で良いと思います!

あと目的としては、アカウントを厳密に管理したいとかそういうことじゃなくて、単純にページを更新した人が誰かをゆる〜く知りたいというのを付け加えればよいですかねえ。

**Comment by znz** [comment]
pre-HowtoJoinTemplate も更新をお願いします。

**Comment by gunjisatoshi** [comment]
とりあえず[RubiMa-editors:6496]で告知しました。

**Comment by znz** [comment]
rubima/magazine.rubyist.net#359 に各自のアカウント作成も入れるといいかもしれません。
それから各記事の著者の人にも今までのように admin (のような共通のアカウント) のパスワードを教えるのではなく、個別のアカウントを作成すると良さそうです。

**Comment by znz** [comment]
https://github.com/rubima/rubima/wiki/HowToEditRubyistMagazine に手順もまとめられているようなので閉じます。
