### ISSUE TITLE
Ruby の歩き方を github へのリンクにするかどうか

### ISSUE THREAD

**Issue by hsbt** [rubima/rubima#134]
現状の確認
- http://magazine.rubyist.net/?FirstStepRuby に @satococoa さんが書いて頂いたものを反映済み
- https://github.com/rubima/rubima/blob/master/first_step_ruby/first-step-ruby-2.0.md は適時更新されている

論点: magazine.rubyist.net にはもう載せないで github を正として直リンクだけで良いのでは?

**Comment by miyohide** [comment]
本件、56号でGitHubのリンクに変更します。反対意見がありましたらコメントでお知らせください。

**Comment by miyohide** [comment]
特に反対意見もありませんでしたので、56号でGithubのリンクに変更しました。
