### ISSUE TITLE
etc/hikiconf.rb での設定

### ISSUE THREAD

**Issue by znz** [rubima/rubima#148]
`@options['diffmail.style'] = 1` の設定が移行出来ていなかったので追加しました。
他には

```
@options['freeze'] = true
@options['template.keyword'] = 'template'
@template_path = '/home/wiki/hiki/template.rubima'
@options["attach_size"] = 2 * 1024 * 1024
```

の設定が移行されていないようですが、どうしましょうか?

元の hikiconf.rb には `@use_wikiname = false` はたぶん設定画面で false にしているので etc/hikiconf.rb では true のままになっているのだと思います。

**Comment by miyohide** [comment]
別システムとしてリリースしたのでCloseします。
