### ISSUE TITLE
hsbt の継続デリバリの原稿

### ISSUE THREAD

**Issue by hsbt** [rubima/rubima#20]
- [x] 担当を決める
- [x] 作者から目次をもらう
- [x] 編集Wikiのprepに記事ページのリンクを作る
- [x] 作者から記事をもらう
- [x] もらった記事を編集Wikiに転載する
- [ ] 編集Wikiの記事を編集する
- [ ] 編集した記事を作者に確認してもらう
- [ ] 編集MLに作者からの確認が完了した旨を伝える
- [ ] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [ ] 作者にお礼のメールを出す

いつにマイルストーンを合わせるか謎なので置いておきます。何処かに設定してください。

**Comment by gunjisatoshi** [comment]
@hsbt この記事どうしましょうか（予定が未定であればもう閉じてしまおうかという話をしています）

**Comment by hsbt** [comment]
最近興味あるネタが変わってきているので閉じます!
