### ISSUE TITLE
未公開記事が分野別目次に載ってしまう

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#216]
ML の松田さんの指摘を転載。

> 公開まではそもそも何も見えないようになってて分野別目次 http://magazine.rubyist.net/?CategoryIndices とかにも載ってこないのがやっぱり一番望ましいですね。。

気づいてなかったけど、問題ですね。。。
まだ見てないけど、直すの少し面倒そう。

**Comment by miyohide** [comment]
別システムとしてリリースしたのでCloseします。
