### ISSUE TITLE
未公開記事をログイン前に開くと注釈が見えている

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#217]
ML での松田さんの指摘を転載。

> ところで、今ログインしてないブラウザで該当URLを見ると注釈だけ表示されるという謎状態になってて、これはマジで不具合レベルだと思います。

注釈。。。
#216 との合わせ技でページにも気づけるのですね。

**Comment by kdmsnr** [comment]
まだ未解決だった……。

**Comment by miyohide** [comment]
別システムとしてリリースしたのでCloseします。
