### ISSUE TITLE
編集しているうちにHikiのログイン状態がタイムアウトしちゃうことがある

### ISSUE THREAD

**Issue by zunda** [rubima/rubima#251]
るびまWikiにログインしてページの編集をして、何十分かあとにやっと保存を押すと、「エラー」と返されることがあります。その場合はログインしなおして同じページの編集を再開して、さっきの編集結果をペーストすると回避できるのですが、できればエラー無しで編集を保存できるとうれしいですよね。

**Comment by miyohide** [comment]
別システムとしてリリースしたのでCloseします。
