### ISSUE TITLE
神奈川 Ruby 会議 01 レポート記事

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#283]
神奈川 Ruby 会議 01の開催が決まりましたので、レポート作成 issue を起こします。レポート担当は @miyohide です。編集も @miyohide が担当しようと考えています。

開催ですが、2015年1月17日となります。かなり先の話となりますが、よろしくお願いします。

**Comment by miyohide** [comment]
50号掲載を目標に、記事を起こしました。
http://magazine.rubyist.net/?0050-KanagawaRubyKaigi01Report

**Comment by gunjisatoshi** [comment]
ありがとうございます！
すごい、もうほとんどできてますね :clap:

**Comment by miyohide** [comment]
@gunjisatoshi さん、早速見ていただきありがとうございます。
殆ど出来ていますが、あと数回推敲するのと、写真や記事の追加を行いたいと思います。

1点質問なのですが、「RegionalRubyKaigi レポート」の後に記されている番号はどのように採番すればよろしいでしょうか。早い者勝ち？

**Comment by gunjisatoshi** [comment]
@miyohide 前の号の大江戸のレポートが 45 なので、それに続く番号を振る感じですねえ。

渋谷 Ruby 会議 01 のレポートも同時掲載される場合は、開催日の早い渋谷のほうが 46 で、神奈川は 47 になるかと思います (渋谷のほうが掲載されない場合は神奈川が 46)。

**Comment by miyohide** [comment]
進捗報告です。
本記事ですが、レポートの番号の採番決定待（渋谷Ruby会議が50号に載るか載らないかで決まります。）という状態です。記事については完成です。

**Comment by sunaot** [comment]
渋谷 Ruby 会議原稿いただいてます！掲載予定です

**Comment by miyohide** [comment]
@sunaot さん、了解です。では、渋谷は48、神奈川は49として採番します。

**Comment by muryoimpl** [comment]
@miyohide ちょっとご相談なのですが(今更過ぎて申し訳ないです…)、基調講演2 の `その後は...` に続く文章をもう少し補完したほうが、私を含む当日その場にいなかった人にもわかりやすそうな気がしました。

(お話を直接聴いていないのでエスパーなのですが、)`なりきるときがしんどくなったとき` は `(設定したロールに)`なりきるときがしんどくなったとき、みたいにするとわかりやすそうだな、と思いました。
もし↑の想定であっているのであれば、続く文章も`(設定したロールの)理想(像に)はたどり着けないぐらいにすごそうなイメージなので` とできそうです。
※↑は想像で書いています。。

`ロールは新しく作られることもある` の「ロール」が何をさしているのか(何のロールなのか)ちょっと分かりづらい気がしました。こちらも少し情報を補完してあげるとわかりやすくなりそうと思いました。

**Comment by miyohide** [comment]
@muryoimpl さん、ご指摘ありがとうございます。

補足については、どうしようか悩んでいます。意図としては、スライドと同じ文言を使っており、そこに著者としての解釈を加える事に抵抗があるからです。
そのことを示すために「」で囲っているのですが、分かりにくいと言われるとそうかもしれません。

**Comment by muryoimpl** [comment]
@miyohide 
最終的なご判断はお任せします。レポートを作成した miyohide さんたちの解釈を優先させてください。
もし言葉を補足したり添えたりするのであれば、私が前述したように直接補完するのではなく、話を聞いた人の解釈として感想的に書く、という方法もありますね。

**Comment by miyohide** [comment]
リリースされました。
http://magazine.rubyist.net/?0050
