### ISSUE TITLE
巻頭言をまとめた ebook を販売 or 作成する

### ISSUE THREAD

**Issue by hsbt** [rubima/rubima#293]
高橋さんの巻頭言をまとめた冊子を達人出版会で販売したい。そして巻頭言集の巻頭言をもらう。

@takahashim 第一感触としていかがでしょうか。許可が頂ければ編集等全てやります。

**Comment by ko1** [comment]
これは誰かやる気のある人って感じですかねえ。

**Comment by takahashim** [comment]
これ、わりとやる気はあるのですが、一番悩んでいるのが表紙ですね…

**Comment by miyohide** [comment]
先ほど最新の53号までの記事を追加したpull requestを送りました。
https://github.com/takahashim/rubimamessages/pull/1

**Comment by hsbt** [comment]
楽しみ...!

**Comment by miyohide** [comment]
54号がリリースされましたので、こちらも追加するpull requestを送りました。
https://github.com/takahashim/rubimamessages/pull/2

**Comment by miyohide** [comment]
55号がリリースされましたので、Pull Requestを送りました。
https://github.com/takahashim/rubimamessages/pull/3

**Comment by miyohide** [comment]
56号リリースに伴い、追加するPRを送りました。
https://github.com/takahashim/rubimamessages/pull/4
