### ISSUE TITLE
RubyKaigi 2014 での公式レポートについてのスレ

### ISSUE THREAD

**Issue by snoozer05** [rubima/rubima#294]
RubyKaigi 2014 の方から来ました。

実行委員側も（薄い陣形で戦っていることもあって）あまり色んなことに手が回らないということもあり、今年については公式では「るびまレポート班」を編成しないという判断としました。

一方で、カンファレンスの雰囲気などはるびまでレポートできたらいいなという気持ちは去年と同様に持っていて、編集部のみなさんの方で何か良いアイデアがあれば、エクストリームスポーツではない形でレポートを実現できればと思うのですが、何か良いアイデアありますかねえ。

「そういうことならやらない方向で」とか「特にアイデアはなさそう」ということならこのissueは閉じていただいて問題ないです。もしやりようがありそうなら、一緒に考えれるといいなあと思います。

どうぞよろしくお願いいたします。

**Comment by sunaot** [comment]
あ、身内なのにリマインドすら忘れていた。。
50 号からは落とします。

**Comment by hokkai7go** [comment]
るびま編集会議から来ました。

こちら、時間が経ってしまったものの出せていないので、掲載しない方向になりました。
チャレンジングではあったのですが、「るびま編集部員が頑張り過ぎない範囲で寄稿する形」での掲載は
まだまだ見直すところがあったようです。
