### ISSUE TITLE
記事の日付

### ISSUE THREAD

**Issue by ko1** [rubima/rubima#298]
http://magazine.rubyist.net/?0006-YarvManiacs
がいつの記事だったか知りたくて、日付が出てたよなぁ、と思ったら、

日付は記事の鮮度を見るために大事な情報だと思うので、出して貰えると助かります。
移行するときに日付なくなっちゃった？

**Comment by miyohide** [comment]
別システムとしてリリースしたので一旦Closeします。

記事の日付や著者名はどこかに表示したいという思いがあるので、別リポジトリのIssueで管理したい。
