### ISSUE TITLE
ルビマの英語版の作成にご協力させてください

### ISSUE THREAD

**Issue by tokumasa** [rubima/rubima#301]
はじめまして。
山下と申します。
現在、麻布十番に所在するIT系のベンチャー企業を運営しているバイリンガルです。（日本語より英語の方が得意です。）
ルビマを今後は英語でも出していき、海外の方々にも情報を共有できればと思い、是非ご協力させてください。
どうぞよろしくお願い申し上げます。

山下

**Comment by ko1** [comment]
@tokumasa こちら、今現状ですと、どう思われますでしょうか。

**Comment by gunjisatoshi** [comment]
@tokumasa せっかくお申し出いただいたところ恐縮ですが、だいぶ時間も経ってしまったので、一旦本 Issue としては Close とさせていただき、また何かございましたらご連絡いただく形とさせていただければと思います。

ご提案ありがとうございました :bow:
