### ISSUE TITLE
渋谷 Ruby 会議 01 レポート

### ISSUE THREAD

**Issue by chiastolite** [rubima/rubima#302]
渋谷 Ruby 会議 01の開催が決まったので、レポート作成 issue を起こします。

レポート担当は @chiastolite です。
開催は2014.11.01(土)です。よろしくお願いします。

**Comment by sunaot** [comment]
@chiastolite @muryoimpl 

0050 号の進行予定が下記のようになっております (#324)。
ご都合よければ、執筆よろしくお願いします。

* 3/1 (日) 記事の目次、アウトライン締切
* 3/15 (日) 記事の締切

**Comment by chiastolite** [comment]
@sunaot はい、よろしくおねがいします!

**Comment by chiastolite** [comment]
目次ですが下記を予定してます



開催概要
===

はじめに
===

当日の様子
===

Unconference～shibuyarb lunch
---

Keynote
---

Community Talks
---

Member Talks
---

まとめ
===

Shibuya.rbについて
===

開催メンバー
---

**Comment by sunaot** [comment]
@chiastolite ありがとうございます。引き続きよろしくお願いします。

**Comment by sunaot** [comment]
@chiastolite 

3/15 が 50 号記事の締切日でした。
地域 Ruby 会議レポートについては校正のぎりぎりまで受け付けられますので、
3/27 あたりまでに完成稿をいただければ掲載の方向にしたいと思います。
引き続きよろしくお願いします。

**Comment by miyohide** [comment]
@chiastolite さん、こんにちは。
長らくお待たせして申し訳ございません。

渋谷Ruby会議の記事ですが、1点お願いがあります。最後の著者のみなさまのところに自己紹介的な一言コメントを頂きたいのですが、ご用意していただけますでしょうか。

るびま0050号は5月10日（日）のリリースを目標としております。そのため、5月3日（日）までにはコメントを頂けますと助かります。

お手数おかけしますが、よろしくお願いします。

**Comment by chiastolite** [comment]
@miyohide 了解しました!

**Comment by chiastolite** [comment]
@miyohide

自分ともう1名のを貼ります。もう1名のは現在確認していますので申し訳ありませんがもうちょっとお待ちください :sweat: 

```
chiastolite
Shibuya.rb参加当初から高円寺→新宿→恵比寿と流浪してようやく渋谷のRubyistになりました


5704x3 
渋谷でインフラエンジニアやっています。渋谷Ruby会議01では記録役として写真の撮影とビデオを回したりしていました。
最近は本当にスイッチやルーターと戯れる毎日です。
```

**Comment by miyohide** [comment]
@chiastolite さん
ご対応有難うございます。現在の状況でまずは記事を更新しました。

もう1名（ @hokkai7go さん）の情報が得られましたら、またご連絡ください。

**Comment by hokkai7go** [comment]
遅くなってご迷惑をおかけしてすみません。。。。

>
hokkai7go
北海道から出てきたRubyistです。ChefやAnsibleを書くことが多いです

よろしくお願いします！

**Comment by miyohide** [comment]
@hokkai7go さん。ご連絡ありがとうございます。記事に反映しました。

**Comment by miyohide** [comment]
@chiastolite さん
リリース予定日である5/10（日）が近づいてきました。特に問題ない場合は、このままリリースを行いたいと考えておりますが、いかがでしょうか。
編集したいところがある場合は、ご連絡頂けますと助かります。
特にない場合も、お手数ですが、ご連絡頂けますと幸いです。

**Comment by chiastolite** [comment]
@miyohide
このままのリリースで問題ないと思うのですが念の為内容を再確認したいと思うのですが
現在の記事確認することは出来ますか?

**Comment by miyohide** [comment]
お手数おかけします。

**Comment by miyohide** [comment]
@chiastolite さん、お手数おかけします。

るびま編集アカウントをお持ちの場合は、ログインして頂き、ページ一覧から渋谷Runy会議の記事を参照してください。

るびま編集アカウントをお持ちでない場合は、アカウントを発行いたします。お手数ですが、アカウント情報のご連絡のために、 miyohide ＠ gmail . com までメール頂けませんか？

なお、申し訳ありませんが、アカウント発行は、本日21時過ぎになる見込みです。申し訳ありません

**Comment by chiastolite** [comment]
@miyohide メール送りました!

**Comment by miyohide** [comment]
@chiastolite さん
お待たせして申し訳ございません。
先ほど、るびま編集アカウントを作成し、頂いたメールに返信しました。ご確認いただけますでしょうか。

**Comment by chiastolite** [comment]
@miyohide 
ありがとうございます！確認がでいました。

いまさらなのですが、コミュニティトークの部分に写真を追加していただくことは可能でしょうか？

**Comment by miyohide** [comment]
@chiastolite さん、確認ありがとうございます。

写真追加は、5/10（日）22:00まででしたら可能です。 @chiastolite さんのアカウントで編集可能なので、直接編集して頂いても構いません。

**Comment by chiastolite** [comment]
@miyohide 写真の追加終えました!

**Comment by miyohide** [comment]
@chiastolite さん、ありがとうございます。

**Comment by miyohide** [comment]
@chiastolite さん、お待たせしました。先ほど、るびま 50号がリリースされました。
http://magazine.rubyist.net/?0050

このたびは、記事の寄稿ならびに校正へのご協力ありがとうございました。
