### ISSUE TITLE
0049 号スケジュール

### ISSUE THREAD

**Issue by muryoimpl** [rubima/rubima#304]
締め切りを **12/14(日)** に設定したいと思います。(関連:  #303 )
- 概要締切: 11/16(日)
- 目次締切: 11/23(日)
- 記事締切: 11/30(日)
- リリース: 12/14(日)

あとで目次ページ作成と、掲載予定記事のまとめしておきます。

現時点掲載予定
- #306 インドのバンガロールの勉強会やカンファレンスに参加された体験記
- #246 小崎さんのインタビュー続編
- #309 @znz さんのRuby 考古学

次号以降に掲載
- @kenchan くんさんに寄稿いただく記事
- 渋谷Ruby会議01 レポート

**Comment by ko1** [comment]
@hokkai7go
プレゼントってどうなってますでしょうか。
オーム社さんより、問い合わせを頂きまして。

**Comment by hokkai7go** [comment]
@ko1 はっ。すみません。応募だけいただいてその後何もできていないです

**Comment by ko1** [comment]
On 2015/04/16 19:46, Yutaro Sugai wrote:
> @ko1 <https://github.com/ko1> はっ。すみません。応募だけいただいてその後
> 何もできていないです

こちら、私の方に当選者の連絡先を教えていただければ、進めますが、いかがし
ましょうか。

-- 
// SASADA Koichi at atdot dot net
