### ISSUE TITLE
他言語からの訪問：Go

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#311]
Go の記事を書いてくれるということだったので、掲載時期未定ですがひとまず記事 issue を立てます。

**Comment by gunjisatoshi** [comment]
@sunaot すみません、本件の状況の共有をお願いできますでしょうか (0051 号のスケジュール https://github.com/rubima/rubima/issues/353 に乗りそうでしょうか)。

**Comment by sunaot** [comment]
@gunjisatoshi いったん閉じちゃいます。代わりに http://magazine.rubyist.net/?0050-ECMAScript2015 を書いてもらってます。Go のほうは識者をご紹介いただくという話をしてましたが、その後私が職場を変えたこともあって、とくに動いてません。ゼロからのスタートになるので、やる気になったときにまた issue 立てます。

**Comment by gunjisatoshi** [comment]
@sunaot 了解です！
