### ISSUE TITLE
改名に失敗する

### ISSUE THREAD

**Issue by muryoimpl** [rubima/rubima#314]
[Rubyist インタビュー特別編 小崎資広さん 後編](http://magazine.rubyist.net/?0047-SpecialInterviewKosaki) を 0049-...にリネームしようと「改名」リンクをクリックすると以下のエラーメッセージが表示されました。

`undefined method `escapeHTML' for "0047-SpecialInterviewKosaki":String`

ユーザはadminでなく、自分のアカウントで実施しています。

**Comment by znz** [comment]
https://github.com/rubima/rubima/issues/336#issuecomment-92344779 にも書きましたが、https://github.com/rubima/hiki-plugin/commit/51dc31b9a2237762060eb85d8b35561bf4c1fc01 で修正してみたつもりです。
動作確認していないので、動作確認がとれたら close してください。

**Comment by miyohide** [comment]
@znz 何度か改名作業を実施してみましたが、異常終了することはなかったのでCloseします。対応ありがとうございました。
