### ISSUE TITLE
0048 号読者プレゼントの発送

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#315]
@ko1 

抽選を終えました。この後発送作業があるのですが、当選者の方の Email アドレスをささださんへ伝えて、当選連絡＆宛先の確認、発送までをお願いしてしまう形で問題ないでしょうか？

**Comment by sunaot** [comment]
遅くなりました。メールしたつもりです

**Comment by ko1** [comment]
了解しました。

**Comment by miyohide** [comment]
2015年5月31日（日）の編集会議で対応済みということをヒアリングしましたので、Closeします。
