### ISSUE TITLE
Bundler と Rubygems.org の改善の話

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#319]
[RubiMa-editors:6829] の件です。

Andre Arko さんより、Bundler と Rubygems.org の改善の話 （依存関係インデックスフォーマットの改良、Travis 等から利用される API の改良、CDN の活用など） を記事にしていただけるそうです。

http://andre.arko.net/2013/12/09/extreme-makeover-rubygems-edition/
http://andre.arko.net/2014/03/28/the-new-rubygems-index-format/

1 月 15 日までには原稿をいただけるそうなので、どなたか本記事を担当してみたいという方はいらっしゃいませんでしょうか。
(翻訳はたいへんそうなので、英語記事のまま載せるイメージですかねえ)

**Comment by oshow** [comment]
るびまMLに何度か送ってもエラーが出てしまうので、情報が分散してしまって申し訳ないのですがこちらで。

@ko1 「申し出」というのは私(oshow)の申し出のことでよろしいのですよね？　すぐお返事したけれどMLに届いていなかったようです。これは私が引き取ったということで大丈夫です。ボールは僕の方にあります。なので、他の件について転送をよろしくお願い致します。

**Comment by ko1** [comment]
@oshow いえ、もう２，３件別の人から書いてもいいよ、ってのがあった感じです。

**Comment by oshow** [comment]
@ko1 あ、「申し出」って他のスピーカーさんからってことなんですね。勘違いしておりました。

わかりました、ではこの「BundlerとRubygems.org改善」の原稿については、私の方で進めていきます。

**Comment by ko1** [comment]
@oshow わかりにくくてすみません。よろしくお願い致します。

**Comment by oshow** [comment]
@ko1 いえいえ！ 頑張ります！

**Comment by oshow** [comment]
こちらの記事ですが、まだ原稿を頂けておりません。

@sunaot  既に諸々の締め切りを過ぎていますが、この記事を50号の記事候補からはずさせてください。連絡が遅くなりすみません。

**Comment by sunaot** [comment]
@oshow ありがとうございます。りょうかいです

**Comment by gunjisatoshi** [comment]
@oshow すみません、この記事の状況はいかがでしょうか。

**Comment by oshow** [comment]
@gunjisatoshi 進展なしです。。僕だけじゃなく他の人に協力頂いた方がよいかもしれません。

**Comment by gunjisatoshi** [comment]
@oshow だいぶ経ってしまったので一旦クローズして仕切り直しましょうか。

**Comment by oshow** [comment]
@gunjisatoshi わかりました。また別のところでお手伝いできたらと思います。。　進まない時は早めに言うように致します。

CLOSEします。
