### ISSUE TITLE
Rubyist Hotlinks 島田浩二さん

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#322]
現在、個別に @shyouhei さんが @snoozer05 さんと調整中。備忘録として Issue にしておきます。

- [x] インタビュー日時・場所を決める
- [x] インタビュー協力者を募集する
- [x] 事前にインタビュー項目をお伝えする
- [x] インタビューを実施する
- [x] 担当を決める
- [x] 掲載号を決める
- [x] テープ起こし要員を募集する https://github.com/rubima/rubima/issues/349
- [x] テープ起こしをする
- [x] 編集Wikiに記事ページを作る
- [x] 編集Wikiの記事を編集する
- [x] 編集した記事をインタビュイーに確認してもらう
- [x] 編集MLにインタビュイーの確認が完了した旨を伝える
- [x] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [x] インタビュイーにお礼のメールを出す

**Comment by gunjisatoshi** [comment]
@shyouhei @snoozer05 だいぶ時間が経ってしまいましたが、状況いかがでしょうか。

**Comment by snoozer05** [comment]
状況は今のところ日程の調整で止まっているという感じかと...
6月の週末は既にすべて予定が埋まってしまったので、週末ということだと7月以降でしたら調整できそうです...

**Comment by shyouhei** [comment]
これ明日やります。

**Comment by gunjisatoshi** [comment]
@shyouhei @snoozer05 当日はよろしくお願いします！

（ちなみに野次馬も十分そうだったので、募集とかは特にしてません）

**Comment by shyouhei** [comment]
実施しました。録音済みですが結局どうしますか? テープ起こしします?

参加者は 島田さん、卜部夫妻、設楽さん、前田さん、佐藤さん、今津さん、角谷さん、須藤さんでした。

**Comment by snoozer05** [comment]
しまだRuby会議の資料です https://dl.dropboxusercontent.com/u/175923/20121027-ShimadaRubyKaigi.pdf

**Comment by gunjisatoshi** [comment]
@shouhei @snoozer05 おつかれさまでした！

テープ起こしはここで募集すると埋もれてしまうので、別 Issue で募集したほうが良いですかねえ。

**Comment by shyouhei** [comment]
データ受け渡しどうしますかねえ。

**Comment by gunjisatoshi** [comment]
大きなファイルの共有は毎回悩みどころですね‥‥。

以前（こさきさんインタビューの時）は Dropbox で共有いただいて URL を個別にお伝え頂いたかと思いますが、容量的に問題なければ今回もそんな感じでお願いできますでしょうか。

**Comment by shyouhei** [comment]
データすでにdropboxに置いてありますがURLどうしますか? ここに書くとみんなアクセスできちゃうしな。

**Comment by gunjisatoshi** [comment]
ではとりあえず私宛にURLをお願いします！
（ご協力いただける方に展開します）

**Comment by snoozer05** [comment]
こっちに書けばよかったですね...。いただいた原稿と音声データを付き合わせしながらの内容チェックと編集作業を一通り完了しました。あとはURLを貼った方が良いところに脚注リンクをつけたり、画像とかを貼った方が良いところに画像貼ったり、という作業をして校正していただければと思います。

**Comment by miyohide** [comment]
@snoozer05 編集作業、ありがとうございます。取り急ぎお礼まで。

**Comment by snoozer05** [comment]
できる範囲で、リンク貼ったり、脚注をつけたり、画像を貼ったりもしてみました。

**Comment by kakutani** [comment]
いまさらではありますが、野次馬しにいった手前、出る前にレビューというわけではないですが目を通すぐらいはやりたいと思ったのですが、いまって原稿はどこいったら見れるんでしたっけ……。

**Comment by snoozer05** [comment]
@kakutani https://github.com/rubima/rubima/issues/349#issuecomment-147692788 という感じになっております..!!

**Comment by kakutani** [comment]
> という感じになっております..!!

ありがとうございます!

**Comment by niku** [comment]
すごく面白く読みました(ついでにリンクが変になっていたところを少し直しました)

写真の画像はDropboxにリンクされているようです．
これはるびまにアップロードして差し替えますか？

**Comment by snoozer05** [comment]
>写真の画像はDropboxにリンクされているようです．
これはるびまにアップロードして差し替えますか？

るびまのアップロードを使おうと思ったのですが、サイズに上限があってやりづらかったので、Dropboxに置いて逃げてしまいました...上限にかからないように調節していい感じにできるのであれば、アップロードして差し替えてください ><

**Comment by miyohide** [comment]
@snoozer05 一通り編集が完了しました。最後にご確認いただけますでしょうか。

画像に関しましては、画像レイアウトがうまく行かずに断念しました。

**Comment by snoozer05** [comment]
ありがとうございます。一通り確認しましたー

**Comment by miyohide** [comment]
@snoozer05 さん、ありがとうございます。では、これでリリースします。ご協力ありがとうございました。

**Comment by miyohide** [comment]
@snoozer05 さん、先ほどるびまを無事リリースすることができました。ご対応ありがとうございました。
http://magazine.rubyist.net/?0052

**Comment by snoozer05** [comment]
@miyohide ありがとうございます。上記からリンクを辿って気づいてしまったのですが、島田の記事だけプレフィックスが0046となっている http://magazine.rubyist.net/?0046-Hotlinks のですが、これは大丈夫でしょうか...??

**Comment by elim** [comment]
> *2 http://www.ustream.tv/recorded/60437349 

これがリンク切れのようですー

**Comment by snoozer05** [comment]
@elim どもです。Youtube の方が公式アーカイブっぽいので差し替えておきました...!!

**Comment by elim** [comment]
@snoozer05 ありがとうございますー :tulip:

**Comment by miyohide** [comment]
@snoozer05 oh...すみません。なんで0046にしたんだろう。。。もう、公開してしまったので、このままで。

**Comment by sunaot** [comment]
一つ前の hotlinks が 0046 号だからかもしれないですね。一通り影響出そうなところ (記事一覧系のものとか) を見て問題出てないことは確認したのですが、プラグインや集計のときにその部分が号数なことを期待していることはあるので、できれば変えてしまえるとよさそうです。

**Comment by miyohide** [comment]
@snoozer05 @sunaot 前言撤回して、修正しました。すみません。
