### ISSUE TITLE
「YARV Maniacs 【第 12 回】」が連載扱いになっていない？

### ISSUE THREAD

**Issue by kou** [rubima/rubima#323]
[YARV Maniacs 【第 12 回】](http://magazine.rubyist.net/?0048-YARVManiacs)が http://magazine.rubyist.net/?CategoryIndices のリストに出ていないので連載扱いになっていないようにみえます。

http://magazine.rubyist.net/?0041-YarvManiacs の最後みたいにバックナンバーのリンクもあるとよさそうに思いました。

**Comment by kou** [comment]
（報告場所としてここが適切じゃなかったらごめんなさい。）

**Comment by ko1** [comment]
ありゃ、大文字小文字まちがえた。

**Comment by ko1** [comment]
ありがとうございます。対応しました。
http://magazine.rubyist.net/?0048-YARVManiacs

**Comment by hsbt** [comment]
@kou ここで大丈夫です!

**Comment by kou** [comment]
速い！
（リンクになっているともっとよさそう！）

**Comment by kou** [comment]
> @kou ここで大丈夫です!

よかったです！

**Comment by ko1** [comment]
ありゃ、したつもりなのになってなかった。

**Comment by ko1** [comment]
301 Moved Permanently を返せるようになると、もっと良いですねえ。

**Comment by gunjisatoshi** [comment]
> 301 Moved Permanently を返せるようになると、もっと良いですねえ。

ですよねー (Permalink は資産！)

**Comment by gunjisatoshi** [comment]
> （報告場所としてここが適切じゃなかったらごめんなさい。）

実は報告用のやつもあるんですが https://github.com/rubima/rubima-support/issues 現状あんまり活用されてないので、こっちでいいと思います！
