### ISSUE TITLE
0050 号の記事候補

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#325]
掲載候補は以下でしょうか。
各記事の担当編集の方は 0050 号の掲載目指すかについて再度確認お願いします。

* ~~Bundler と Rubygems.org の改善の話 #319~~ 次号以降へ
* ~~他言語からの訪問：Go #311~~ 次号以降へ
* 他言語からの訪問：Node.js/io.js #329 
* Hypermedia Web API #326 
* ~~RubyKaigi 2014 の公式レポート #294~~
* 神奈川 Ruby 会議 01 レポート記事 #283 
* EffectiveRuby プレゼント記事
* mruby Debugger の話 #328 
* よちよち.rb イベントレポート #321 
* 松江 Ruby 会議 05 レポート #317 

また、以下は担当不在の掲載候補です。地域 Ruby 会議の担当編集たくさん募集中 (主に窓口する人になります)。

* ~~DeccanRubyConf （インド）旅行記 #296~~ 次号以降へ
* ~~松江 Ruby 会議 06 レポート #318~~ 次号以降へ
* 渋谷 Ruby 会議 01 レポート #302 
* ~~Tokyu Ruby 会議 08 レポート #300~~ 次号へ
* Tokyo Ruby 会議 07 レポート #330

こちらは次号かな？

* しまださんの Hotlinks #322

**Comment by sunaot** [comment]
その他の掲載予定記事があればもちろん歓迎ですので、コメントぶらさげてください。

**Comment by takkanm** [comment]
arton さんより EffectiveRuby をプレゼント用に 3 冊いただいてますので、本紹介とプレゼント企画やります

**Comment by miyohide** [comment]
取りまとめありがとうございます。
#283 神奈川 Ruby 会議 01 レポート記事は0050号掲載でお願いします。

また、各種Ruby会議レポートの担当について、どれか一つ窓口になろうかと思っています。

**Comment by sunaot** [comment]
> * 他言語からの訪問：Go #311 

Go は別の人のほうが〜というお話をもらい、Node.js/io.js 記事 (#329) の執筆をしてもらえることになりました。

**Comment by sunaot** [comment]
@miyohide 

> また、各種Ruby会議レポートの担当について、どれか一つ窓口になろうかと思っています。

ありがとうございます。いずれも担当いないと思うので気になるものへサインアップしていただけるとうれしいです！

**Comment by sunaot** [comment]
@takkanm 

ありがとうございます。プレゼント企画は担当もお願いしてしまってよいかんじでしょうか？

**Comment by sunaot** [comment]
mruby Debugger の話を記事候補の一覧へ足しました

**Comment by takkanm** [comment]
プレゼント担当やります

**Comment by miyohide** [comment]
@sonaot さん。では、松江 Ruby 会議 05 レポート #317 を担当します。

**Comment by gunjisatoshi** [comment]
0050 号がリリースされましたので、こちらはいったん閉じます。
（0051 号の記事候補として、別途また Issue を立てましょう！）
