### ISSUE TITLE
Hypermedia Web API

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#326]
tkawa さんに RubyKaigi 2014 での発表を記事起こししてもらえることになりました。
そのまま sunaot が担当します。

今号のスケジュール
- #324 

進行
- [x] 担当を決める
- [x] 作者から概要をもらう
- [x] 作者から目次アウトラインをもらう
- [x] 作者から記事をもらう
- [x] もらった記事を編集Wikiに転載する
- [x] 編集Wikiの記事を校正する
- [x] 編集した記事を作者に確認してもらう
- [x] 編集MLに作者からの確認が完了した旨を伝える
- [x] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [x] 作者にお礼を伝える

**Comment by tkawa** [comment]
よろしくおねがいします！

**Comment by tkawa** [comment]
原稿を更新して、目次アウトラインをつくってみました。
https://gist.github.com/tkawa/c3849684996804904f3c

**Comment by sunaot** [comment]
ありがとうございます！これから読みますので、まずは ack のコメントをしておきます。

**Comment by tkawa** [comment]
@sunaot さん
推敲・加筆してだいたい記事本文完成しました。よろしくお願いします。
図の入れ方がよくわかりませんがそのままGistに添付します。

**Comment by sunaot** [comment]
@tkawa さん

ありがとうございました。
RubyKaigi 2014 以来、半年ぶりで読んでいることになるのですが、現地で聞いていた興奮を思い出します。あらためて読みながらわくわくできました。

いったん私のほうでるびまの hiki へ転載しますので、後ほど hiki 上での図やコラム、注釈の表現が意図とずれていないかの確認をお願いします (転載完了後に閲覧用の id をメールでお知らせします)。

**Comment by sunaot** [comment]
@rubima/owners 

いったん転載したつもりです。表組みでいただいている markdown の意図に沿えていないところがあるので、まだ直します。手元のデータとずれが出ると困るので、hiki 上のページの編集はまだしないでください。

http://magazine.rubyist.net/?0050-Hypermedia

**Comment by sunaot** [comment]
@tkawa さん

通常、記事に「著者について」というかんたんな自己紹介を入れております。
こちらへコメントしてもらえれば転記しますのでご希望の内容を返信お願いします。

**Comment by tkawa** [comment]
ありがとうございます。
僕はアカウントを持っていないためか http://magazine.rubyist.net/?0050-Hypermedia は脚注だけが見える状態ですが、これは問題ないんですよね。
「著者について」を書きましたので使ってください。

---
# 著者について

川村 徹 ([@tkawa](https://twitter.com/tkawa))

Railsばかりやっているフリーランスプログラマ。RESTafarian。株式会社ソニックガーデン技術支援。
[Sendagaya.rb](http://sendagayarb.doorkeeper.jp/) 共同主催、 [RESTful Web APIs読書会](http://www.circleaf.com/groups/19) 主催、[RESTful#とは勉強会](http://rubychildren.doorkeeper.jp/) 進行役。

**Comment by sunaot** [comment]
はい、ログインしていないと脚注しか見えない状態で正しいです。
「著者について」もありがとうございました。転載しました。

**Comment by tkawa** [comment]
@sunaot さん
お忙しいようでしたら校正手伝いますので、Wikiのアカウントをいただけますか？

**Comment by miyohide** [comment]
@tkawa さん、お手数おかけします。
アカウントを発行しました。アカウント情報は Twitter DMにて送信させていただきましたので、ご確認ください。

編集については、ログイン後 http://magazine.rubyist.net/?0050-Hypermedia にアクセスしていただき、「編集」リンクをクリックしていただくと可能となります。
どのようにHikiを書けばよいかわからないなどの場合は、このIssueでご連絡頂けますと対応いたします。

なお、リリースは5/10（日）を目指しています。よろしくお願いします。

**Comment by sunaot** [comment]
@tkawa さん、ありがとうございます。
目は通し終わっていて、校正は特に必要なかったです。
ただ、hiki のフォーマットで表の中央寄せがないのでそこの見せ方だけどうにかしようと思ってました。

**Comment by sunaot** [comment]
@miyohide さんもフォローありがとうございます。

**Comment by miyohide** [comment]
@tkawa さん
こんにちは。すみません、1点確認させてください。
記事の中頃にある

> 複数のitemscopeがある場合、`main`要素もしくは`data-main-item`属性のものがルートノードとみなされます。

という部分なのですが、これはMarkdownでいう1行コードを意図されていますでしょうか。

もしそうだとしますと、残念ながら、Hikiでは該当機能がサポートされていません。代替として、太字（'''）で表現することをるびまではやっているのですが、その方法で大丈夫でしょうか。

**Comment by tkawa** [comment]
はい、バッククォートで囲まれた部分はそうです。たしかほかにも何ヶ所かあったと思います。
太字表現に直してもらってかまいません。

2015年5月1日金曜日、miyohide<notifications@github.com>さんは書きました:

> @tkawa <https://github.com/tkawa> さん
> こんにちは。すみません、1点確認させてください。
> 記事の中頃にある
>
> 複数のitemscopeがある場合、main要素もしくはdata-main-item属性のものがルートノードとみなされます。
>
> という部分なのですが、これはMarkdownでいう1行コードを意図されていますでしょうか。
>
>
> もしそうだとしますと、残念ながら、Hikiでは該当機能がサポートされていません。代替として、太字（'''）で表現することをるびまではやっているのですが、その方法で大丈夫でしょうか。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubima/rubima/issues/326#issuecomment-98142452>.
>


-- 
Toru KAWAMURA <tkawa@4bit.net>

**Comment by miyohide** [comment]
@tkawa さん
早速のご連絡ありがとうございます。太字表現に直しました。

**Comment by miyohide** [comment]
@tkawa さん。
リリース予定日である5/10（日）が近づいてまいりました。問題が無いようでしたら、このままリリースを行いたいと考えておりますが、いかがでしょうか。

**Comment by tkawa** [comment]
@miyohide さん、校正ありがとうございます。
目を通しました。リリースOKです！
もし細かいミスにあとから気づいたときは、直してもいいでしょうか？

**Comment by miyohide** [comment]
@tkawa さん。
ご連絡ありがとうございます。
また、細かいミスに気がついたときには、編集して構いません。

**Comment by miyohide** [comment]
@tkawa さん、お待たせしました。るびま 50号がリリースされました。
http://magazine.rubyist.net/?0050

今回は、記事の寄稿ならびに校正へのご協力ありがとうございました。

**Comment by tkawa** [comment]
@sunaot さん、 @miyohide さん、編集担当の方々、ありがとうございました！
