### ISSUE TITLE
mruby Debugger の話

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#328]
- [x] るびまWiki のアカウントを作って著者の方にお伝えする
- [x] ページ名を決める ( http://magazine.rubyist.net/?0050-XXXX の XXXX の部分)
- [x] 上記名前で auth つきで空ページをつくる (auth つきだとログインしないと見えない)
- [x] 原稿を受け取る
- [x] 上記で作った空ページにいただいた原稿を転記する
- [x] 転記した記事を著者の方に見ていただき、必要であれば加筆修正いただく
- [x] 表紙からリンクを張る
- [ ] リリース時に auth を外して誰でも見える状態にする
- [ ] 著者の方に執筆ありがとうとお伝えする

@yurie さんより mruby Debugger のお話を記事にしていただけるというオファーを頂いております。

http://www.slideshare.net/yamanekko/writing-mruby-debugger

まだ具体的なことは何も決まっていませんが、取り急ぎ issue にしておきます。

**Comment by gunjisatoshi** [comment]
0050 号掲載を目指す方向で調整中です。

本日が概要締切りですが、上記 SlideShare の内容をもって概要とします。

**Comment by gunjisatoshi** [comment]
行きがかり上、本件担当します。

**Comment by gunjisatoshi** [comment]
状況報告ですが、原稿はほぼ終わっていて、最後に URL を修正して、表紙からリンクを張れば完了です。
（今日中くらいには終わりそうです）

**Comment by gunjisatoshi** [comment]
ご連絡遅くなりましたが、リリース可能な状態にある認識です。

**Comment by muryoimpl** [comment]
@gunjisatoshi 質問です。(今更ですみません。。)
nomitory へのリンクが貼られていないのですが、意図的でしょうか？なんとなく、どこにあるかくらいは掲載しておいたほうがよいかな、と思いました。

リポジトリと思われる [nomitory-eclipse-plugin](https://github.com/yamanekko/nomitory-eclipse-plugin) と [nomitory](https://github.com/yamanekko/nomitory) を見てみたのですが、README にあるリンクが "gh-pages" としか表示されないので、気になりました。

**Comment by yurie** [comment]
こんにちは、やまねです。
現時点ではソースコードは公開しておりません。Eclipseプラグインのみ公開しています。
Eclipseのインストールページにて下記URLを指定するとインストールできます。
http://yamanekko.github.io/nomitory/

ページにその旨記載しておいた方がいいですね・・・。
今ちょっと電波が不安定なところにいるので、明朝までに記載しておきます。
という感じでいいでしょうか？

**Comment by muryoimpl** [comment]
@yurie ありがとうございます！対応いただけると嬉しいです！
読者の方も触りやすくなると思います。
Eclipse のインストールページでURLを指定する必要があるんですね。

**Comment by muryoimpl** [comment]
@yurie "明朝" という単語を見落としておりました…
29日をリリース目標にしようとしているため、28日にはチェックできる状態であると助かります。もちろん、難しい状況であれば調整いたしますので、ご連絡ください。無理して明朝、とかでなくて全然大丈夫です。
急なお願いでご迷惑おかけします。よろしくお願いいたします。

**Comment by yurie** [comment]
紛らわしくてすみません。
27日の午前3時ぐらいには直ってます！

**Comment by yurie** [comment]
紛らわしくてすみません。
27日の午前3時ぐらいには直ってます！

**Comment by muryoimpl** [comment]
ありがとうございます。助かります。

**Comment by yurie** [comment]
遅くなりましたが、追記してみました。
やっぱりわかりにくい・・・ということでしたらご連絡ください
# 該当ページにも書いているようにWindows環境では試せていません。すみません・・・

**Comment by muryoimpl** [comment]
説明の追記ありがとうございます！環境とか説明については今のベストエフォートで全然大丈夫だと思います！
私の方で、るびま記事の `monitory とは` のパートの最後に下の一文を追加してみました。いかがでしょうか…

`利用する場合は、こちら http://yamanekko.github.io/nomitory/ を参考に Eclipse の機能を利用してインストールしてください。`

**Comment by yurie** [comment]
遅くなってすみません。
修正いただいたのにすみませんが、元々Eclipseの話にすると読者の興味が薄れそうな点を危惧して
nomitoryではEclipse使ってるけどこの記事を読んで試す分にはEclipseはいらないよ！ということを
強調したネタだったので、「おわりに」のところに興味をもったらEclipseの方も試してみてね。という感じに移動させてみました。
併せて、冒頭も「mruby を使ったことはありますか？ 」に変えてみました。
いかがでしょうか？

**Comment by muryoimpl** [comment]
修正ありがとうございます！

>修正いただいたのにすみませんが、元々Eclipseの話にすると読者の興味が薄れそうな点を危惧して
nomitoryではEclipse使ってるけどこの記事を読んで試す分にはEclipseはいらないよ！ということを
強調したネタだったので、「おわりに」のところに興味をもったらEclipseの方も試してみてね。という感じに移動させてみました。

そのほうがよいと思いました！

> 併せて、冒頭も「mruby を使ったことはありますか？ 」に変えてみました。

よいと思います！


ディレクトリについては、`/Users/xxx/…` に統一してみました。


「nomitory のしくみ」のところで、使用しているサンプルコードは…というところで https://github.com/yurie/rubima50/blob/master/rubima2.c の提示があるのですが、この記事で https://github.com/yurie/rubima50/ にある他のファイルも登場しているので、最初のほうでhttps://github.com/yurie/rubima50/ のURLを示したほうがよいかもしれません。

すみません、上の rubima50 を見て気がついたのですが、文中に出てくる `rubima.rb` と `rubycode.rb` は同一のものですか？

**Comment by yurie** [comment]
遅くなってすみません！
「はじめに」のところに
本記事内で使用したコードは https://github.com/yurie/rubima50 にあります。
を追加しました。

> 新たに編集いただいた箇所のディレクトリの記載については、/Users/xxx/… に統一してみました。
問題ないでしょうか？

修正漏れです。ありがとうございます！

> すみません、上の rubima50 を見て気がついたのですが、文中に出てくる rubima.rb と rubycode.rb は同一のものですか？

別ものです。
紛らわしいので注釈をつけてみましたが、これでわかりそうですか？

**Comment by muryoimpl** [comment]
>「はじめに」のところに
本記事内で使用したコードは https://github.com/yurie/rubima50 にあります。
を追加しました。

ありがとうございます！よいと思います！

>> すみません、上の rubima50 を見て気がついたのですが、文中に出てくる rubima.rb と rubycode.rb は同一のものですか？
> 別ものです。
> 紛らわしいので注釈をつけてみましたが、これでわかりそうですか？

注釈入れていただいたことで `rubima.rb` が何かわかりやすくなったと思います。
`簡単のために` というところを `説明を簡単にするために` と変更してみました。(意図が違っていたら申し訳ありません。)
`rubima.rb`が画像の3行だとすると、`v` の値が `3` になると思います。この値から`rubycode.rb`かと思っておりました。変数表示の実装例のところの value の値を 3 にするだけでよいでしょうか？

**Comment by yurie** [comment]
確かに紛らわしいかもですね。
ちょっと直してみますので、1時間ぐらい待ってください

**Comment by yurie** [comment]
遅くなってすみません。
変数表示の実装例はrubycode.rb、「Ruby コード 1 行はバイトコード 1 行とは限らない」のところで使用しているのはrubima.rb と異なっています。(この記事内に2種類の.rbが存在しています。ややこしくてごめんなさい・・・)
rubyma.rb と rubycode.rbについて、同じ元ネタから派生した関係で、変数名が同じだったのが紛らわしい原因かと思い、rubyma.rb で使用している変数名を変更して画像を貼り直してみました。
また、breakpointの実装例のところに注釈でrubycode.rbを使用している旨記載しておきました。

あわせて、「参考) バイトコードを出力するには (ry」の部分のコード
./bin/mruby -v rubima.rb　ついて、bin ってどこ？というのがわかりにくいので、
~/git/mruby/bin/mruby -v rubima.rb　に変えました。

こんな感じでどうでしょうか？

「簡単のため」は半分ネタなので、"簡単のためは日本語としておかしい派"じゃなければそのままにしておいていただけるとうれしいです。（わがままですみません

**Comment by muryoimpl** [comment]
いろいろと対応ありがとうございます！確認させていただきます

**Comment by muryoimpl** [comment]
> こんな感じでどうでしょうか？

よいと思います！すごく読みやすくなったと思います。

> 「簡単のため」は半分ネタなので、"簡単のためは日本語としておかしい派"じゃなければそのままにしておいていただけるとうれしいです。（わがままですみません

こちら承知いたしました。(ネタなんですね。情弱ですみません…)

遅い時間にいろいろとご対応いただきありがとうございました！LGTM です！

**Comment by yurie** [comment]
こちらこそ、いろいろご指摘ありがとうございました！

> (ネタなんですね。情弱ですみません…)
ネタというか、ちょっと話題になってたので、機会があれば使ってみたいなーと思ってただけですw

**Comment by gunjisatoshi** [comment]
@yurie だいぶ遅くなりましたが、ようやくリリースの運びとなりました。

投稿ありがとうございました。mruby 関連の記事は少ないので嬉しいです :smiley_cat:

また機会があれば投稿お待ちしておりますので、引き続きよろしくお願いいたします :bow:

**Comment by yurie** [comment]
このたびはお世話になりました。
この記事のおかげでデバッガの名前も決まりましたし、大変感謝しています。（命名した本人は記憶にないそうですが・・・w）

なかなか るびま読者層が興味を持ちそうなネタができないので、それだったらいけるかも？ってのが出てきたら、またお声がけいただけると幸いです。

早速、すとうさんから誤字の指摘をいただきました。

> code_getch になっているところが1つと
> code_fech になっているところが1つあります。

修正可能でしょうか？
可能でしたらやり方を教えてください。よろしくお願いします！

**Comment by gunjisatoshi** [comment]
やまねさん

郡司＠るびま編集部です。

修正は直接実施いただいてかまいません！

http://magazine.rubyist.net/?c=login

にアクセスいただいて、以前お伝えしたアカウントにてログイン後に、

http://magazine.rubyist.net/?0050-nomitory

の右上の「編集」を押してHiki記法にて
原稿の修正をお願いいたします！
（Hiki 記法については下記をご参照ください）

http://hikiwiki.org/ja/TextFormattingRules.html


2015年5月14日 1:50 yurie <notifications@github.com>:

**Comment by yurie** [comment]
ありがとうございます。
修正できました！
