### ISSUE TITLE
他言語からの訪問 Node.js/io.js

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#329]
@yosuke-furukawa さんに書いてもらえることになりました。

#324 のとおり、

- 3/1 (日) 記事の目次、アウトライン締切
- 3/15 (日) 記事の締切
- 3/29 (日) 校正完了、リリース

となってます。

今号のスケジュール
- #324 

進行
- [x] 担当を決める
- [x] 作者から概要をもらう
- [x] 作者から目次アウトラインをもらう
- [x] 作者から記事をもらう
- [x] もらった記事を編集Wikiに転載する
- [x] 編集Wikiの記事を校正する
- [x] 編集した記事を作者に確認してもらう
- [x] 編集MLに作者からの確認が完了した旨を伝える
- [x] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [x] 作者にお礼を伝える

**Comment by yosuke-furukawa** [comment]
一旦目次を作ってみました。

一旦EverNoteに貼っておくので、もう少ししたほうが良ければ連絡をください。

https://www.evernote.com/l/AARFOInwyqZJIZ6cTU6Kmx9k7iVZPKurzoU

**Comment by SugHimsi** [comment]
ついついES6と書いてしまいがちでしょうから、確認するときは注意しようと思いますが、書かれる段階でも気をつけていただけると有難く。

**Comment by sunaot** [comment]
読みました。とてもバランスのよい内容だと思います。このまま進めていただければ！

**Comment by hsbt** [comment]
@yosuke-furukawa 

狙いと目次だけパッと見て、とても読みたくなってます。

**Comment by sunaot** [comment]
@yosuke-furukawa 

こんにちは。記事の状況いかがでしょうか？

着々と書いてもらえているのは Evernote で観測中ですので「いつ頃までには完成見込みなので待ってくれ」などあれば気軽にご相談ください。

**Comment by yosuke-furukawa** [comment]
@sunaot すいません。おまたせしております。一旦今週末まで待っていただくこと、可能でしょうか。
そのタイミングでは仕上げておきます。

**Comment by sunaot** [comment]
@yosuke-furukawa 

了解です。では完成を楽しみに待っています！

**Comment by yosuke-furukawa** [comment]
一旦上げておきます。

https://github.com/yosuke-furukawa/babel_tutorial/blob/master/README.md

一つ迷っているのは、 ECMAScript 2015という呼び方があまりにも一般的になってないので、
ECMAScript6、 ES6という呼び方に戻そうかと思っています。

よろしくお願いいたします。

**Comment by SugHimsi** [comment]
お迷いの点、とりあえず、「はじめに」の「新しいSprocketsでは[ES6]で記述することもできる」のような表記の不統一を、今のうちに統一しておきませんか。
(ただ、コマンド名にes6などとあるので、どこかで「これは実は…」と触れる必要があるのかもしれません…)

**Comment by sunaot** [comment]
@yosuke-furukawa 

ありがとうございます。内容の確認とるびま wiki への転載作業を始めます。

**Comment by sunaot** [comment]
@yosuke-furukawa 

hiki へ転載しました。もう少し体裁整えたら確認用のアカウントを連絡します。
タイトルと自己紹介 (「著者について」として記載します) を追加したいので、それぞれコメントください。

**Comment by yosuke-furukawa** [comment]
かしこまりました。

タイトル：「2015年のJavaScriptとbabelの話」
著者について：「
古川陽介 (Yosuke Furukawa / @yosuke_furukawa) 。日本Node.jsユーザーグループ代表、io.jsエヴァンジェリスト、io.jsコントリビュータ。記事掲載時点では会社でサーバサイドのPerlとフロントJavaScriptも行うフルスタックなエンジニア
」

**Comment by yosuke-furukawa** [comment]
こんな感じでいかがでしょう？？

**Comment by yosuke-furukawa** [comment]
@sunaot さん、
こちらどうなりました?

**Comment by sunaot** [comment]
@yosuke-furukawa 返事遅れてすみません、今編集モードの記事を見られる ID/Password を Twitter DM で送りました。記事の転記で意図しない形になった箇所がないから確認お願いします。

**Comment by miyohide** [comment]
@yosuke-furukawa さん
こんにちは。るびま編集者の一人であるmiyohideと申します。記事について1点確認させてください。記事の中頃にある

> これで `grunt` コマンドを実行すればbabelが実行されます。

という部分なのですが、これはMarkdownでいう1行コードを意図されていますでしょうか（他にも類似部分がありますが省略）。

もしそうだとしますと、残念ながら、Hikiでは該当機能がサポートされていません。代替として、太字（'''）で表現することをるびまではやっているのですが、その方法で大丈夫でしょうか。

**Comment by yosuke-furukawa** [comment]
@miyohide 

問題ありません。今 Hiki で編集しようと思っている事があるので、明日以降修正していただけると幸いです。

**Comment by miyohide** [comment]
@yosuke-furukawa さん
ご連絡ありがとうございます。では、明日以降、修正いたします。

**Comment by yosuke-furukawa** [comment]
@miyohide @sunaot 修正しました。
http://magazine.rubyist.net/?0050-ECMAScript2015

**Comment by miyohide** [comment]
@yosuke-furukawa さん、対応有難うございます。私も修正が終わりました。

お手数ですが、1点確認させてください。

今後の ECMAScript2015 の展望の部分で、

> jsx とあわせることで故 E4X のような XML リテラルを記述することができるようになっています。

という記述があるのですが、以下のように「故」は「より」の誤変換ではないでしょうか。

> jsx とあわせることでより E4X のような XML リテラルを記述することができるようになっています。

**Comment by sunaot** [comment]
追悼的な意味の故なのでは。界隈のハイコンテキストはありそうなので、るびま的に補完するなら、編集者注で[追悼な文脈](http://nanto.asablo.jp/blog/2013/05/27/6824873)を補完するのがよさそうです。

**Comment by sunaot** [comment]
よさそうですっていうか、編集者なんだから自分でしろよっていう天の声を感じたので編注入れてみました

**Comment by yosuke-furukawa** [comment]
@sunaot @miyohide 
E4X は事実上死んでしまった仕様なので、追悼の意であってます。
https://developer.mozilla.org/ja/docs/E4X

"故E4X" よりも "かつて存在した E4X" のが伝わりやすい気がしました。

**Comment by miyohide** [comment]
@yosuke-furukawa さん、 @sunaot さん、ご対応有難うございます。

@yosuke-furukawa さんから提示頂きました文章（「かつて存在した E4X」）に書き直し、かつ、 @sunaot さんの脚注を活かすように編集しました。

**Comment by miyohide** [comment]
なお、本記事については、5/10（日）がリリース目標日となっております。そのため修正は、5/9（土）までに行っていただけますと助かります。

**Comment by yosuke-furukawa** [comment]
@miyohide @sunaot 私の方の修正は終わっております。大きな問題がなければこのままリリースでお願い致します。

**Comment by miyohide** [comment]
@yosuke-furukawa さん、ご連絡ありがとうございます。記事作成、ありがとうございます。

**Comment by miyohide** [comment]
@yosuke-furukawa さん、お待たせしました。先ほどるびま 50号がリリースされました。
http://magazine.rubyist.net/?0050

記事の寄稿、ならびに校正へのご協力ありがとうございました。
