### ISSUE TITLE
Sqale の更新手続き

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#331]
早いもので、毎年恒例の Sqale の更新案内が来ました
参考: https://github.com/rubima/rubima/issues/263

@takahashim 問題ないようでしたら継続でお願いしたいのですが、いかがでしょうか。

**Comment by takahashim** [comment]
はい、それで問題ないです！　申し込んでおきます。

**Comment by gunjisatoshi** [comment]
@takahashim お手数おかけいたしますが、よろしくお願いいたします :bow:

**Comment by takahashim** [comment]
振り込んだので先方の確認待ちです

**Comment by gunjisatoshi** [comment]
ありがとうございます :+1:

**Comment by gunjisatoshi** [comment]
先方にて無事入金確認でき、2015 年 4 月 1 日～ 2016 年 3 月 31 日分の更新が完了した旨のメールを受領済です。なのでこの Issue は閉じちゃいますね。

@takahashim ありがとうございました！
