### ISSUE TITLE
monban の記事

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#332]
@kbaba1001 さんが書いてくれるそうです！

**Comment by kbaba1001** [comment]
@sunaot 引き受けたきり音沙汰がなくてすみません。
今月は時間がありそうなので書かせていただきたいと思います。

ただ、私の興味として statesman より [monban](https://github.com/halogenandtoast/monban) という authentication に関する gem への関心が高まっておりまして、もし差し支えなければ monban をテーマとした記事を書かせていただきたく思います。
概要としては、 monban は新しく知名度が低い gem なので devise や sorcery などの同系統の gem との比較や、カスタマイズの方法について紹介したいと考えております。
勝手なお願いで恐縮ですが、ご検討頂きたいです。

**Comment by sunaot** [comment]
@kbaba1001 いえ、こちらこそ状況の確認などせずすみません。

>今月は時間がありそうなので書かせていただきたいと思います。

ありがとうございます！

> ただ、私の興味として statesman より monban という authentication に関する gem への関心が高まっておりまして、もし差し支えなければ monban をテーマとした記事を書かせていただきたく思います。

関心の高いものについて書いていただくのが一番なので、monban での寄稿歓迎です。なかなかスタンダードが決まらないところで、読者の興味も高いものだと思うので楽しみにしています。

**Comment by sunaot** [comment]
@kbaba1001 次号へのスケジュールがこのような進行になっているのですが、ご都合いかがでしょうか？
もし問題なければ、このまま9月リリース号掲載予定で進めるようにします。

* 記事の目次、アウトライン締め切り
    * 8/9 (日)
* 記事の締め切り
    * 8/16 (日)
* 校正完了、リリース
    * 9/6 (日)

via https://github.com/rubima/rubima/issues/353

**Comment by miyohide** [comment]
頂いた記事を以下に貼り付けました。（要認証）
http://magazine.rubyist.net/?0051-IntroduceMonban

コードの部分の貼り付けとかの作業が残っているので、これを近日中に終わらせたい。

**Comment by miyohide** [comment]
本記事、作者さんのOKが取れました。

**Comment by gunjisatoshi** [comment]
@kbaba1001 可能であれば「著者について」の記載をお願いできますでしょうか (必須ではないので「記載しない」という判断もありです)。どんな感じで書けばよいかはるびまの他の記事をご参考にいただければと思いますが、簡単な自己紹介、近況などをいただければと思います :bow: /cc @miyohide

**Comment by kbaba1001** [comment]
@gunjisatoshi https://github.com/rubima/rubima/pull/357 末尾に追加しました。 cc @miyohide

**Comment by miyohide** [comment]
@kbaba1001 さん、さきほどるびま51号がリリースされ、monban紹介記事も掲載されました。
http://magazine.rubyist.net/?0051
寄稿・編集へのご協力ありがとうございました。

**Comment by sunaot** [comment]
@kbaba1001 記事いただいてから何もできておらず申し訳ありません。ご寄稿ありがとうございました。記事拝見しましたが、認証機能の Monban 以上にその設計のバランスから刺激を受けました (Generators 込みで)。

**Comment by kbaba1001** [comment]
@sunaot るびまに貢献できて嬉しいです！お話いただきありがとうございました。
