### ISSUE TITLE
0050 号巻頭言

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#333]
@takahashim 

0050 号の巻頭言をお願いします。
(先ほどリスケし) 4/8 リリース予定になっております。

http://magazine.rubyist.net/?c=edit;p=0050-ForeWord

**Comment by takahashim** [comment]
はい、今回は隣で原稿書いてる人がいたのでスケジュールは把握しておりました(がまだ書けてなくてすみません…

**Comment by takahashim** [comment]
本文の方はひと通り書いてみましたが、書影もあった方がいいでしょうか…

**Comment by gunjisatoshi** [comment]
書影もあった方が良さそうですね。
（お忙しいようでしたら、こちらで追加いたします！）

**Comment by gunjisatoshi** [comment]
書影を追加してみました。
（ちょっとうるさい感じになっちゃいましたね‥‥）

**Comment by takahashim** [comment]
書影ありがとうございます！　私の方でも一部修正しました（amazonで品切れになってる奴はマイナビさんへのリンクにしてみました）。

**Comment by SugHimsi** [comment]
ちょっと手を出せない状況で、言うだけになってしまうのですが、Rubyの歩き方のページからリンクさせたい。いつでも可。

**Comment by takahashim** [comment]
とりあえず「Rubyの歩き方」の書籍の節からリンクしてみました。
あと、遅ればせながら記事紹介も追加しましたが、ES2015とハイパーメディア原稿は今号で良かったんでしょうか？

**Comment by sunaot** [comment]
@takahashim 

記事いただいていて、hiki 転載も終わってるので今号でお願いしたいです。

**Comment by takahashim** [comment]
@sunaot  了解です！(次号送りになりそうなら記事紹介から削ろうかと思っていたのでした)

**Comment by muryoimpl** [comment]
lintかけて整形してみました。
@takahashim アンダースタンディングコンピュテーションのところで出てきた `CS` は`コンピュータ・サイエンス`だと思ったので(ちょっと唐突かなと思ったので)、コンピュータ・サイエンスにして置きました。

**Comment by gunjisatoshi** [comment]
毎号、巻頭言をいただきありがとうございます！

だいぶ遅くなりましたが、無事 0050 号がリリースされましたのでお伝えいたします。

今後ともよろしくお願いいたします :bow:
