### ISSUE TITLE
0050 号アクセスランキング

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#334]
アクセスランキングページをつくる

**Comment by sunaot** [comment]
こちらも残タスク〜

**Comment by gunjisatoshi** [comment]
https://github.com/rubima/rubima/issues/324#issuecomment-96364574 でも書きましたが、私がやります。

（くどいようですが https://github.com/rubima/rubima/issues/313#issuecomment-66380842 でも書いた通り、るびまの Google Analytics アカウントを持っている人 https://github.com/rubima/rubima/issues/152 なら https://github.com/rubima/rubima/issues/273#issuecomment-39480713 の手順に従って誰でもこの記事を作ることができるはず）

**Comment by hsbt** [comment]
:bow:

**Comment by miyohide** [comment]
Wikiに作成方法を起こしました。
https://github.com/rubima/rubima/wiki/create_access_ranking_page

**Comment by gunjisatoshi** [comment]
:+1:

**Comment by gunjisatoshi** [comment]
というわけで作ってみたのですが、あんまり代わり映えがしないですねえ。
（前号の記事がひとつくらいは載っていて欲しいところですが‥‥）

http://magazine.rubyist.net/?0050-RubyistMagazineRanking

**Comment by gunjisatoshi** [comment]
無事リリースされたのでこちらはクローズします！
ありがとうございました！
