### ISSUE TITLE
0050 号編集後記

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#335]
お題を決めて編集後記を記入する

**Comment by sunaot** [comment]
お題募集中です...

**Comment by gunjisatoshi** [comment]
「50 と言えば」だと平凡ですかねえ。

**Comment by SugHimsi** [comment]
「GitHubが今なくなったら何が困るか」

**Comment by sunaot** [comment]
節目だし 50 といえばにしておきますか。

**Comment by miyohide** [comment]
「50といえば」で書きました。

**Comment by gunjisatoshi** [comment]
書きました！

**Comment by gunjisatoshi** [comment]
ちょっとまだ寂しい感じなので、編集された方もそうでない方も最近の近況とか書いていただけると嬉しいです :bow:

http://magazine.rubyist.net/?0050-EditorsNote

別にリリース後でも構わないので、よろしくお願いします！

**Comment by niku** [comment]
今回はなにもしておりません(すみません)が，足しました

**Comment by gunjisatoshi** [comment]
リリースされたのでクローズします。記入ありがとうございました！
（リリース後でも追記OKなので、何か書きたい方は後からでもぜひ）
