### ISSUE TITLE
0050 号表紙

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#336]
各記事目次を書く。主に地域 Ruby 会議の記事。

**Comment by sunaot** [comment]
地域 Ruby 会議の目次がまだ一つも埋まっていないのです〜

- #330 
- #317 
- #302 
- #283

**Comment by sunaot** [comment]
渋谷 01 の記事も私が md で受け取ってたのでした。。
記事転記しないと。

**Comment by sunaot** [comment]
表紙に地域 Ruby 会議の記事を追加して、渋谷の記事ページが 0049 だったのと松江の `s/MatsueRubyKaigi05/MatsueRubyKaigi05Report/` するのに改名をしたら、

> Error
> undefined method `escapeHTML' for "0050-MatsueRubyKaigi05":String

だったところで力尽きました。

「書いた人」も追加しないと。。

**Comment by miyohide** [comment]
お手数おかけします。
松江と神奈川については、著者名入力しました。松江の改名については私もチャレンジしましたが、同じメッセージが出てしまったので、リンクのみを修正しました。

**Comment by znz** [comment]
NoMethodError については https://github.com/rubima/hiki-plugin/commit/51dc31b9a2237762060eb85d8b35561bf4c1fc01 で修正してみたつもりですが、どうでしょうか。

**Comment by gunjisatoshi** [comment]
改名の件はまだ試してませんが（すみません‥‥）、とりあえずリリースしたのでこちらはクローズします。ありがとうございました！
