### ISSUE TITLE
るびま合宿 あらため るびま編集者会議 (0050 号記念)

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#337]
0050 号という記念すべき号がもうすぐ発行されようとしていますが、それを記念して、というわけでもないのですが、いろいろと現状のるびまに関する問題点とかもろもろを話し合う場を作りたいねという話をしたところ、日本 Ruby の会様よりご支援いただけそうな雰囲気です。 https://github.com/ruby-no-kai/official/issues/177

ここでやるのが良いのかメーリングリストのほうでやるのがいいかという話はありますが、まずは Issue としておきます。とりあえずまだふんわりした感じではありますが、そういう場が開かれたら参加したい！という方はここにコメントください。

- [x] 参加希望者を確認する
- [x] いつどこで何をやるか決める
- [x] 想定コストを日本 Ruby の会様に伝えてご支援可能かどうかにつきお伺いする
- [x] 参加確認
- [x] 宿 or 会議室等の場所確保
- [x] 実行

**Comment by miyohide** [comment]
参加希望で手を上げます。

**Comment by gunjisatoshi** [comment]
いまのところ @miyohide さんだけなので、どこかの地域 Ruby Meetup とか（その帰りに飲みに行くとか）で済んじゃうような気がしますね‥‥。
（企画倒れ）

難しい話は抜きにして「50 号おめでとう」とかのほうがいい気がしてきた！

**Comment by hokkai7go** [comment]
最近さっぱりるびまで動けていないのですが
発行を省力化するだとか、属人化しないための方策とか考えたいなぁと思っているので
やれるようなら合宿か、るびま自体のふりかえりとかやりたいです。

**Comment by miyohide** [comment]
合宿だとハードルが高い気がします。 @hokkai7go さんが言われている「ふりかえり」をやるっていうのはいいかもしれませんね。どっかの会議室に集まって、2〜3時間ぐらいお話するってイメージです。

**Comment by gunjisatoshi** [comment]
@miyohide @hokkai7go ではそんな感じでいきましょうか～。日時と場所を決めてしまって、あとは来れる方が来るという感じですかねえ。
（場所の当てがあればご提案をお願いします～）

**Comment by hokkai7go** [comment]
場所はあんまり思いつかないですねぇ。
るびまは、結構いろんな場所に住んでいる人たちがいるので悩ましいです

**Comment by gunjisatoshi** [comment]
そーいえば全然関係ないんですが、最近（でもないか）うちのそばにこんな施設ができたので利用してみたいなあとか思ったりもしました。

http://www.cp-bigship.net/%E8%B2%B8%E9%A4%A8%E6%96%BD%E8%A8%AD%E3%81%AE%E4%BA%88%E7%B4%84/

小会議室でも24人いけるみたい。3時間半の利用で 2,200 円。Honjo.rb でも始めようかしらん。

**Comment by miyohide** [comment]
場所については、ルノアールの会議室はいかがでしょうか。
http://www.ginza-renoir.co.jp/myspace/

あと、とりあえず今の時点で手を上げている人たちがアクセスしやすい場所に決めちゃっていいような気がします。

**Comment by ko1** [comment]
休日で少人数でしたら、弊社会議室（丸の内）も可能です。
ただし、Guest wifi 遅いです。

**Comment by gunjisatoshi** [comment]
@ko1 おー、それはぜひお願いしたいです！
直近で可能な日程をいくつかいただいて、そこで決めちゃいましょうか。

**Comment by ko1** [comment]
私のスケジュールを見たら、土日だと 5/30, 31 となっておりました。ちょっと、遅すぎるでしょうか。

**Comment by gunjisatoshi** [comment]
ちょうどいいんじゃないでしょうか～。
あとはこのスレに参加している方の都合を聞いて、良さそうなら ML でも他の方に参加意思を聞いてみましょう。

というわけで 5/30 と 5/31 の都合はいかがでしょう？＞ @miyohide @hokkai7go

**Comment by hokkai7go** [comment]
僕もちょうどいいです。
どちらの日程も昼あたりから夕方にかけてであれば問題ありません

**Comment by miyohide** [comment]
31日は終日OKです。
30日はまだ未確定な予定があります(15日に確定予定)ので、それ次第といった感じです。

**Comment by gunjisatoshi** [comment]
では 5/31(Sun) お昼あたりから夕方あたりで仮決めして、とくに問題ないようであれば今日中くらいに他の参加者を募る、みたいにしましょうか。

お手数ですが会議室の仮押さえをお願いします！＞ @ko1

**Comment by ko1** [comment]
現在会議室について、調整中です。

なお、ビルに入る、出る時には、私のアテンドが必要になりますので、遅刻・早退をなるべくないようにして頂けると助かります。

**Comment by ko1** [comment]
多分、大丈夫です。8人の会議室で足りるかな。

**Comment by gunjisatoshi** [comment]
@ko1 ありがとうございます！　いまのところ8人で大丈夫そうですね。
あとはアテンドが必要ということであれば集合時刻も決めてしまったほうが良いですね。13:00 からがいいですかねえ。

**Comment by miyohide** [comment]
@gunjisatoshi さん、13:00からでよいかと。

**Comment by ko1** [comment]
5/31 (Sun) 12:30-18:30 で会議室を取りました。
昼飯から集まるか、昼飯後集まるか、という感じでしょうか。

編集会議の交通費を、Rubyの会様に聞いてみるのは手かもしれません。

**Comment by SugHimsi** [comment]
記事のあたまにあるチェックボックス、もう少し“つぶしていけそうな”形を考えてみました。
(参加を表明しているわけではありません。)

[X] 日時と場所の決定
[X] 参加者募集、
[ ] 募集の〆切(日の設定から)
[ ] 参加者と補助希望額ネゴ
[ ] 日本 Ruby の会様と補助額ネゴ
[ ] 参加者にリマインダ発信
[ ] 当日の緊急連絡法確立・連絡先確保

**Comment by gunjisatoshi** [comment]
https://github.com/ruby-no-kai/official/issues/177#issuecomment-104102223 にて、交通費は出してもらえそうだったので遠方の方もご参加につきご検討いただければと思います :smiley:
（おそらく飛行機なり新幹線なりのチケット購入時に日本 Ruby の会様宛の領収書をもらえばそれが確証になるかと思いますので、もし来られる際は領収書をお忘れなく）

いずれにせよ費用の相談のためにいったん参加者募集の締め切りを決めましょうか。一週間前の 5/24(Sun) あたりにしますかね。

**Comment by miyohide** [comment]
@gunjisatoshi さん、 @hokkai7go さん、 @ko1 さん、 @SugHimsi さん、今度の日曜日が開催予定日です。

集合場所と時間を決めたいです。場所は丸の内のJPタワーでしょうか？
http://www.salesforce.com/jp/company/direction.jsp

**Comment by SugHimsi** [comment]
集合時間ですが__現地での食事の都合がよい__時間を提示いただければ(当方はその辺の事情よく分からず…)、_なるべく_ 合わせます。

**Comment by ko1** [comment]
はい、JPタワーになります。

休日で、普通の扉は開いていないので、
KITTE 1F から JPタワーオフィスフロアに入る手前の自動ドアでお集まり頂く感じになるかと思います。
13:00 にそこにお集まり下さい。
多分、行けばわかると思いますが、わからなかったら適当に twitter などで聞いて貰う感じで。

昼食なら、1時間程度でしょうか。
12:00 にどっかで集まって食べて頂き、13:00 にオフィスフロアで合流という感じで。

あと、会議室でお弁当食べることも可能です。アイスブレイクのために、お弁当を 13 時集合時に買って、食いながら会議、でもいいかもしれませんね。お任せします。

各自のご意向を聞いておけると助かります。

**Comment by gunjisatoshi** [comment]
> 会議室でお弁当食べることも可能です。アイスブレイクのために、お弁当を 13 時集合時に買って、食いながら会議、でもいいかもしれませんね

これが楽な気がしますねー。食べながらだと集合時間はもうちょっと早くても良いかもしれないので「12:30 集合、その時点で（必要な人は）お弁当持参」にしましょうか。

なお、領収書の宛名は「一般社団法人日本Rubyの会」だそうですので領収書をもらう際にはご留意ください。 https://github.com/ruby-no-kai/official/issues/177#issuecomment-105349528

**Comment by ko1** [comment]
おっと、会議室は 13 時から空調がつくようにしているんで、ちょっと暑いかも。
12:30 集合、飯の調達開始、でどうでしょう。私がいると、地下 1F でお弁当が1割引です。

**Comment by gunjisatoshi** [comment]
ありがとうございます！　では 12:30 集合してお弁当を買いに行く、ということにしましょう！

集合場所は「KITTE 1F から JPタワーオフィスフロアに入る手前の自動ドア」のままで良いでしょうか。

**Comment by ko1** [comment]
はい、それが良いかと思います。人も少ないですし。

**Comment by miyohide** [comment]
@gunjisatoshi さん、 @ko1 さん、了解しました。調整ありがとうございます。

5/31（日） 12:30 に「KITTE 1F から JPタワーオフィスフロアに入る手前の自動ドア」付近に集まります。

**Comment by SugHimsi** [comment]
集合時間と場所、諒解しました。
おなかをすかせてうかがいますが、そちらのお弁当は、おいくらくらいのものでしょうか。

**Comment by ko1** [comment]
高くても1000円弱くらいかと思います。（いや、もっと高いのもあるようですが）
昼食代は、Rubyの会が出してくれるそうです。

**Comment by hokkai7go** [comment]
会場提供ありがとうございます！
時間と場所承知しました。

**Comment by gunjisatoshi** [comment]
全員そろったので、そろそろ始めます。

**Comment by miyohide** [comment]
今日の議事メモです。

```
・システムに対する要望

著者と執筆履歴と編集履歴がでない（リリース後にどのような編集が有ったかわからない）。

「書いた人」が有ったりなかったりするので、それを改善したい。
できればシステマティックに。

Issue
https://github.com/rubima/rubima/issues/93
https://github.com/rubima/rubima/issues/298

・RubyKaigiでるびまをどうにかするか？

なにかするか？

・50号のプレゼント締め切り。

新しいIssueを立てる →　https://github.com/rubima/rubima/issues/341

・50号振り返り

今日はやらないことに。

・コミュニケーションツールの話（メーリングリストとGithub、IRC）

そもそも振り返りができていないので、振り返りをしましょう。
　→　振り返りから改善できた？

メーリングリスト必要ですか？
　→　Githubだと基本オープンなので、秘密の企画をやりたいときにはちょっと困る気がする。
　→　MLは残すけど、周知してMLには投稿しないようにする。
　　　→　保守は1年周期と変更しました。

　→　当日のリリースやりとりはリアルタイム性がほしい。
　　　→　IRC？idobata？Facebook Group？
　　　→　IRC,MLは非推奨。Wikiの修正が必要な気がする。
　　　→　idobataで。アナウンス、お願いします。

・未掲載の記事の棚卸しをしたい

　　インタビュー、どうします？
　　　→　卜部さんフォロー。https://github.com/rubima/rubima/issues/322

・statesmanの記事（https://github.com/rubima/rubima/issues/332）
・Bundlerの記事（https://github.com/rubima/rubima/issues/319)
・松江06（https://github.com/rubima/rubima/issues/318）→　みよひで
・Go言語（https://github.com/rubima/rubima/issues/311）
・Tokyu08（https://github.com/rubima/rubima/issues/300）
・DeccanRubyConf（https://github.com/rubima/rubima/issues/296）→なしで。
・RubyKaigi2014（https://github.com/rubima/rubima/issues/294）→落とします。
・hsbtさんの継続デリバリのお話（https://github.com/rubima/rubima/issues/20）→郡司さんがPing
・「式と文、…」（https://github.com/rubima/rubima/issues/66）→落とします
・WindowsでRubyを野良ビルド（https://github.com/rubima/rubima/issues/52）→落とします
・factory_girlの話 (https://github.com/rubima/rubima/pull/310）


・プレゼントの件

→48号、49号完了。

プレゼント提供者が「したい」と言われない限り、特に募集はしないです。


・1年先ぐらいのリリース計画

51号は8月。
11周年が9月。
12月頃に52号。（直前号も大変だけど、直後）
2016年3月ごろに53号。

RubyKaigiのお話をテキスト化するだけでもうれしい。
発表記事のスピンアウト。

雑誌記事やWebなんかへのポインタとしてるびまを活用してもよいのかなと。

・属人化しているのが気になる。

関わっている人（activeに動けている人）が多ければいいよね。

生産性を上げるか、人を増やすか。

るびまがどこにリーチしているのか、リーチしていないのかが把握できていない。

編集をやるひとに対して、一種の売名行為としてできれば嬉しいかなぁ。

Podcastの文字起こしすると嬉しい人はいるかも。

記事のCloud Founding化とか。

https://2015.battlehack.org/tokyo

間口を広げる。リクルーティング活動。

入ってきた人をどうやってフォローするか。

るびまWikiにある程度まとまっているが、流れがなかなか見えないのが難しい。
https://github.com/rubima/rubima/wiki

「るびま編集の始め方」をもう少し整備する。
https://github.com/rubima/rubima/wiki/HowToEditRubyistMagazine

自己紹介Issueを立てる
https://github.com/rubima/rubima/issues/345


```

**Comment by ko1** [comment]
次は RubyKaigi 2015 で。

**Comment by miyohide** [comment]
議事メモをWikiに起こしました。
https://github.com/rubima/rubima/wiki/EditorialMeeting50

完了しましたので、Closeしますね。お疲れ様でした。

**Comment by znz** [comment]
Wiki の方ですが、閉じ括弧が全角だとそこまで自動リンクに含まれてリンク切れになっているように見えます。

**Comment by miyohide** [comment]
@znz さん、ご指摘ありがとうございます。修正しました。
