### ISSUE TITLE
浜松Ruby会議01レポート

### ISSUE THREAD

**Issue by suchi** [rubima/rubima#339]
手順をしっかり踏んでいなかったようで申し訳ありません。

@suneo3476 さんと私 (@suchi) で担当いたします。

開催日は3/28(土)でした

**Comment by miyohide** [comment]
@suchi さん、ご連絡ありがとうございます。るびま編集チームの @miyohide と申します。浜松Ruby会議の開催、お疲れ様でした。

次回のるびまは8月頃のリリースを予定しておりますが、詳細は未定となっております。大まかなスケジュール感は、

- リリースの1ヶ月前が、記事の目次・アウトラインの締め切りのめど
- リリースの2週間前が、記事の締め切り
- リリースまで、校正を実施。

となっておりますので、ご認識いただけますと幸いです。

記事につきましては、最終的にはHiki記法で書く必要があるのですが、初稿においてはMarkdownなどでも問題ありません。

記事として書く内容につきましては、最近のるびまに掲載されている各種地域Ruby会議レポートを参照してください。

まずは、ご連絡まで。ご質問等ありましたら、お気軽にお問い合わせください（このIssueへの書き込みでOKです）。

**Comment by suchi** [comment]
ありがとうございます。再来週までには初稿が提出できる見込みです。よろしくお願いします。

**Comment by miyohide** [comment]
@suchi さん、了解しました。

私が担当しますので、初稿は「 miyohide _atmark_ gmail _dot_ com 」（ _atmark_ は＠に _dot_ は「.」に変更してください）に送信してください。

また、るびま編集用アカウントを発行いたします。初稿送付時に、必要となるアカウント数と希望ユーザ名を明記していただけますと助かります。

それでは、初稿お待ちしております。

**Comment by suchi** [comment]
承知しました。でき次第お送りします。

**Comment by miyohide** [comment]
@suchi さんより記事をいただきましたので、ご連絡いたします。51号を目処に編集いたします。

- [x] 担当を決める
- [x] 作者から概要をもらう
- [x] 作者から目次アウトラインをもらう
- [x] 作者から記事をもらう
- [ ] もらった記事を編集Wikiに転載する
- [ ] 編集Wikiの記事を校正する
- [ ] 編集した記事を作者に確認してもらう
- [ ] 編集MLに作者からの確認が完了した旨を伝える
- [ ] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [ ] 作者にお礼を伝える

**Comment by gunjisatoshi** [comment]
おつかれさまです。浜松 Ruby 会議 01 には私も参加していたので、どんな感じのレポートか楽しみです :smile:

**Comment by miyohide** [comment]
@suchi さん。
るびま編集用アカウントをメールでご連絡いたしました。ご確認いただけますと幸いです。

**Comment by suchi** [comment]
確認いたしました。また執筆の藤森さんにも連絡いたしました。ありがとうございました。

**Comment by miyohide** [comment]
@suchi さん。
取り急ぎ、頂いた原稿を記事化しました。お手数ですが、先日お知らせしたユーザIDとパスワードでログインしていただき、その後、下記URLにアクセスしていただけますでしょうか。
http://magazine.rubyist.net/?0051-HamamatsuRubyKaigi01Report

修正に関しましては、ここでお知らせしていただけると編集部の方で修正します。
また、ご自身でも修正可能です。修正方法については下記URLを参照してください。
https://github.com/rubima/rubima/wiki/HowToMakeWikiPagePrivate

**Comment by suchi** [comment]
ありがとうございます。とりあえず見逃していた「YouTube」の表記だけ統一しました。

**Comment by miyohide** [comment]
@suchi さん、しばらく連絡が遅れまして済みません。
「YouTube」の表記統一ありがとうございます。

次号のるびまですが、 9月6日にリリースの予定です（ #353 ）。それまでは編集・修正可能です。

現在編集部で校正中です。 今週中を目処に完了する予定ですので、今しばらくお待ち下さい。

**Comment by kurotaky** [comment]
@suchi さん
/cc @miyohide 

はじめまして、るびま編集チームの @kurotaky です :octocat: 

浜松Ruby会議01レポート楽しく読ませていただきました。 :smile: 
2点修正しましたので、ご確認よろしくお願いします! 

http://magazine.rubyist.net/?0051-HamamatsuRubyKaigi01Report

## 修正点
> Rails Girls と、私。

発表スライドのタイトルに合わせて、`Rails Girls` の間の半角スペースを削除して、
`RailsGirls と、私。` にしました。

> マイコンボード「Adruino」用シンセサイザーのプロトタイプとして

誤字の修正です。
`Adruino` を `Arduino` に修正しました。

**Comment by suchi** [comment]
@miyohide さん

ありがとうございます。リリーススケジュール承知しました。

@kurotaky さん、はじめまして。

修正確認いたしました。
ありがとうございました。助かります。

**Comment by miyohide** [comment]
@suchi さん、さきほどるびま51号がリリースされ、浜松Ruby会議01のレポートも掲載されました。
http://magazine.rubyist.net/?0051
寄稿・編集へのご協力ありがとうございました。

**Comment by suchi** [comment]
確認しました。ありがとうございました。ようやく浜松Ruby会議01の全タスクが終了して感無量です。
