### ISSUE TITLE
0050 プレゼント

### ISSUE THREAD

**Issue by ko1** [rubima/rubima#341]
@takkanm 
http://magazine.rubyist.net/?0050-Present

これ、どうなってますか？

**Comment by takkanm** [comment]
締め切りが今日までなんで、来週中には抽選しようかと

2015年5月31日日曜日、Koichi Sasada<notifications@github.com>さんは書きました:

**Comment by ko1** [comment]
ありがとう。

**Comment by takkanm** [comment]
当選者発表、ならびに当選連絡のメールをだしました

**Comment by ko1** [comment]
:+1:

**Comment by takkanm** [comment]
当選者の方から住所をいただいたので、週末には送付予定。
送料を日本 Ruby の会から援助していただけないかを issue にしております。 https://github.com/ruby-no-kai/official/issues/186

**Comment by takkanm** [comment]
本日、当選者の方への発送が完了しました。
感想をまとめたら close にします。

**Comment by gunjisatoshi** [comment]
@takkanm お疲れさまです。だいぶ時間も経っていて、発送も終わっているようですので閉じちゃってもいいでしょうか。

**Comment by miyohide** [comment]
@takkanm お疲れ様です。本件、発送も終わっているようですので、Closeしちゃってもよいでしょうか。

**Comment by takkanm** [comment]
とじときます
