### ISSUE TITLE
RubyKaigi の submission form に要望を出す

### ISSUE THREAD

**Issue by ko1** [rubima/rubima#342]
@takahashim @kakutani @shyouhei @amatsuda

RubyKaigi の submission form に、
「あとでるびまに記事を書く」というチェックボックスを付けて貰い、選考に勘案してもらえないか交渉する。
チェックを入れた人の情報は、るびま編集部に情報が行くとか。

**Comment by hsbt** [comment]
:+1: これはいいアイデア

**Comment by kakutani** [comment]
発表したいという人のコンテンツに関連する情報を共有できると、記事あつめの観点からはよさそうですね(CFPには落選したけど、るびまの記事としての価値は十分にありそう、みたいなのは過去の応募にもありそう)。

「るびまに書くっていうと通りやすくなる」みたいなのは、それが良いことなのか判断つかないです。

**Comment by ko1** [comment]
どう勘案するかは、勿論選考者による基準になるかと思います。
一個人としては、発表だけだと勿体ないので、記事化は＋ポイントになると良いなと思います。

**Comment by amatsuda** [comment]
確かに面白いアイデアではあるけど、選考に勘案とか以前にCFPのフォームには入れたくないです。
理由は、ひとことで言うなら方向性のミスマッチです。

RubyKaigiは国際カンファレンスを志向しているし、実際海外からの応募がかなり多くなってきています。CFPの受け付けは英語で行うし、サブミットも英語で書いてもらうことを推奨します。
一方でるびまはあくまでも国内メディアですよね。ごく稀に海外の著者の記事を翻訳して載せたケースもありますが、それはあくまで編集なり訳者なりが著者と個人的なつながりがあった場合に限られていて、基本的にるびまは日本人が日本語で日本の読者に向けて書いた記事を載せるメディアですよね。英語版が出てるわけでもないので、海外にはまったくリーチしていません。これべつに批判してるわけじゃなくて、僕はるびまはそれで良いと思ってます。

つまり、国際カンファレンスのCFPフォームに謎の現地メディアがどーたらこーたら書いてあって、海外の応募者がこれなんだろうと思ってググっても読めないのが現状ですよね。チェックを入れようにも判断できないですよね？外国人には記事を読ませる気はないけど現地人向けに記事を書くかどうか答えてください(Noって答えたらどうなるかはご想像にお任せします)、みたいな質問ですよね？それはなんか気持ち悪いです。システムとして間違っているように感じます。僕が応募者だったらまず不信感を感じます。

ただし、当日の発表を聞いた上で、るびま関係者の誰かが「あなたの発表が面白かったので是非もっと詳しい記事を書いてください」と発表者に個人的にお願いするのはもちろん大歓迎です。それはシステムではなくて人間対人間の気持ちの入った交流なので、僕は大いに応援したいです。
もし自分がスピーカーだったら、こんなことを言われたらめっちゃ嬉しいので喜んで記事でも何でも協力する気になるでしょう。

**Comment by ko1** [comment]
個人的には不信感は抱きませんが、RubyKaigi 主催者がそのような判断をされるのでしたら、それが尊重されるべきであると考えます。

**Comment by miyohide** [comment]
RubyKaigiも終わってしまったのでCloseします。
