### ISSUE TITLE
magazine at ruby-no-kai org の宛先に @miyohide を追加する

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#343]
そういえばこのアドレスの管理って誰にどう頼めばいいんでしたっけ‥‥。

**Comment by ko1** [comment]
@snoozer05 わかりますか？

**Comment by snoozer05** [comment]
登録するメールアドレスを教えていただけたら、ぼくの方で登録可能ですー

**Comment by miyohide** [comment]
@snoozer05 さん、 miyohide ＠ gmail.com でおねがいします。

**Comment by snoozer05** [comment]
登録してみたつもりです。テストメールを送ってみますね。

**Comment by snoozer05** [comment]
送りました。届きましたでしょうか

**Comment by miyohide** [comment]
@snoozer05 さん、届きました。早速の対応有難うございます。
