### ISSUE TITLE
MLを廃止し、Idobataに移行する

### ISSUE THREAD

**Issue by hokkai7go** [rubima/rubima#344]
るびま編集会議から来ました。

（この内容は後で、MLに流して周知します）

MLは廃止しようという流れになりました。
MLの使用は非推奨とし、リリース時などリアルタイムにコミュニケーションを取る必要がある場合は
Idobataを使用することになりました。

コミュニケーションツールは今後、以下のようにしたいと思います。
・ML→廃止
・GitHub Issue→継続
・IRC→Idobata

編集者のみなさんは、以下のリンクから 6/14(日) までに roomに入って欲しいです。
入ってもらったのを確認後、Guestではアクセスできないようにしたいと思っています。

https://idobata.io/organizations/rubima/rooms/rubima/join_request/b8133b76-9519-466b-8fd6-db7531def58f

それ以降は、GitHub issue でIdobataに入りたい旨を書いてもらえたら自分とかがIdobataへ招待します。

**Comment by ko1** [comment]
期日を過ぎた後の instruction は？

**Comment by hsbt** [comment]
議論を追えてないので、あくまでも外野の意見ですが ML を廃止するということと、IRC を Idobata にしようというのは全く関係のない別の問題のように見えました(それを承知のうえでとにかく Idobata にしよう、ということならそれはそれで良いです)

**Comment by gunjisatoshi** [comment]
> ML を廃止するということと、IRC を Idobata にしようというのは全く関係のない別の問題のように見えました

補足です。

1. もともとは「コミュニケーションツールを整理しましょう」という話でした
2. 現状を分析したところ「日々の編集」は ML と GitHub、「リリース直前等のリアルタイムコミュニケーション」は IRC を使っているらしい
3. 「日々の編集」は GitHub に集約しましょう (MLは非推奨)、リアルタイムコミュニケーションは IRC をやめて idobata にしましょう、ということになりました

私はまあとくに意見を持ち合わせていないので、若くて活発なメンバーのやりやすいようにしていただく分にはぜんぜんかまわないのですが、編集会議に参加していない人たちだけで決めるのはちょっと乱暴じゃないかという話はまあ確かにそうですので、何か異論があればこの Issue か別 Issue を立てるかして議論しましょう。

そしてもうちょっと個人的な思いを書くと、「間違っていてもいいからとにかく決断して先に進もう」という姿勢は周りを気にしすぎて結局何も変わらないよりはずっといいと思っています。若手がんばれ :smiley:

**Comment by SugHimsi** [comment]
書き込み時点で、idobataは比較的うまく機能していると思う。

**Comment by hokkai7go** [comment]
@SugHimsi コメントありがとうございます。同感なのでこのissueはcloseします。

何かあれば再オープンまたは別途立ててください。
