### ISSUE TITLE
RedDotRubyConf 2015 レポート

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#346]
@igaiga さんより RedDotRubyConf 2015 参加レポートを寄稿予定というお話を伺っておりますので、取り急ぎ Issue といたします。

**Comment by igaiga** [comment]
@gunjisatoshi ありがとうございます！

**Comment by gunjisatoshi** [comment]
@igaiga 遅くなりましたが、空のページを作りました！

http://magazine.rubyist.net/?0051-RedDotRubyConf2015

**Comment by igaiga** [comment]
おおむね書けました。一晩寝かせて校正したら完成の予定です。

**Comment by gunjisatoshi** [comment]
@igaiga おお、ありがとうございます！　というわけで 0051 号掲載の方向で進めたいと思いますので、よろしくお願いします :smile:

**Comment by igaiga** [comment]
@gunjisatoshi 校正したのでこれで提出とします。なにか問題あれば編集などしていただいても構わないです。よろしくお願いします。m(_ _)m

**Comment by gunjisatoshi** [comment]
@igaiga ありがとうございます！

**Comment by gunjisatoshi** [comment]
@igaiga 予定通り本日 0051 号がリリースされ、無事記事も掲載されましたのでお伝えいたします。

http://magazine.rubyist.net/?0051-RedDotRubyConf2015

執筆ありがとうございました！　またカンファレンスに参加の際はレポートいただけると嬉しいです :smiley:
