### ISSUE TITLE
とちぎRuby会議06のレポート

### ISSUE THREAD

**Issue by vestige** [rubima/rubima#348]
2015/06/20 に”とちぎ06”が無事に行い終わりました。
なので、あとはレポートを書くだけです。
今回、書くのは僕ではないのですが、issueをたてて、レポート班との連絡を行っていきます。

**Comment by gunjisatoshi** [comment]
@vestige ご連絡ありがとうございます！　（とちぎ Ruby 会議、またも体調不良で行けませんでした。ざんねん）
引き続きよろしくお願いします :bow:

**Comment by gunjisatoshi** [comment]
0051 号の進行役の方から来ました https://github.com/rubima/rubima/issues/347

とちぎRuby会議06のレポートの件ですが、0051 号 (スケジュールは https://github.com/rubima/rubima/issues/353 をご参照) の掲載を目指すかどうかの確認です (スケジュール的に厳しいようであれば次号以降としたいと思います)。

別のところで簡易なレポートにするかどうかの議論も進行中かと思いますが、まずは状況を共有いただきたく、よろしくお願いします :bow:

**Comment by vestige** [comment]
よねざわです。
8.16には間に合わなそうな気がします。
いまやっと、レポート全体が揃ったところです。基調講演の内容が豪華だったため、最適化中です。

**Comment by gunjisatoshi** [comment]
@vestige ご連絡ありがとうございます！

では、とりあえず「掲載号未定」のままとしますが、もし間に合いそうになって 0051 号掲載を希望されるようでしたら（締め切り後でも多少は融通ききますので）別途ご相談ください :smile:

**Comment by vestige** [comment]
@gunjisatoshi 0051には間に合わなそうですが、レポートを書いてもらいました。えっと、どういう風にするとよいんでしょうか？一応、hiki形式っぽく書いてもらったのですが...

**Comment by miyohide** [comment]
@vestige さん、メールで原稿や写真をいただけますでしょうか。

miyohide @ gmail.com まで原稿をいただけると、ページを作成し、編集用アカウントをお知らせいたします。

**Comment by miyohide** [comment]
@vestige さん、メールでの原稿送付ありがとうございます。

先ほど、アカウントのご連絡をメールで送信しました。ご確認いただけますと幸いです。
なお、編集作業は、はやければ8/16中に、遅くても来週中には終了する予定です。
編集が終了次第、再度このスレッド上でご連絡いたします。

**Comment by miyohide** [comment]
@vestige さん、頂いた原稿を記事化しました。
http://magazine.rubyist.net/?0051-TochigiRubyKaigi06Report

リンク化やhikiの文法・るびま編集指針合わせた編集を行っております。
先日お知らせしたユーザ名とパスワードでログイン後、上記URLにアクセスして御覧ください。

1点お願いです。「書いた人」に対してそれぞれ一言コメントを書いていただけますでしょうか。

**Comment by vestige** [comment]
書いた人のコメントいれました。

**Comment by miyohide** [comment]
@vestige さん、コメント記入ありがとうございます。今週末ぐらいに確認しておきますね。

**Comment by miyohide** [comment]
@vestige さん、コメントの配置を修正しました。内容等は変更しておりません。
対応有難うございました。

**Comment by miyohide** [comment]
@vestige さん、さきほどるびま51号がリリースされ、とちぎRuby会議06のレポートも掲載されました。
http://magazine.rubyist.net/?0051
寄稿・編集へのご協力ありがとうございました。
