### ISSUE TITLE
Rubyist Hotlinks テープ起こしの募集

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#349]
https://github.com/rubima/rubima/issues/322 の件ですが、インタビューについては無事終了したようですのでテープ起こしをやりたいという方を募集します。

どなたかやってみませんか。

**Comment by SugHimsi** [comment]
今週であれば5分間分くらいは文字起こしできると思います。

**Comment by shyouhei** [comment]
ちなみにデータは卜部の手元にあります。

**Comment by gunjisatoshi** [comment]
@shyouhei ファイルの受け渡しをどうしましょうか（問題なければ以前のように Dropbox などの共有ストレージサービスで共有いただけると助かります）

**Comment by gunjisatoshi** [comment]
@SugHimsi 遅くなりましたが音声ファイルのありかを個別にメールしましたのでご確認ください！
（内容聞いてないのでオフレコ具合は分からないのですが、取り扱いにはご注意ください）

**Comment by SugHimsi** [comment]
@gunjisatoshi 前半(58分以前)は、9割くらいはオープンで問題ないような。

**Comment by kakutani** [comment]
クラウドソーシン的なやつも検討してみましょうか〜。ちょっとググったらRubyの会で出しちゃってもよさそうな金額感だった。RFP書くのがめんどくさそうだけど、試す価値はありそう。

**Comment by gunjisatoshi** [comment]
そうですね、ご支援いただけるのであればぜひ（アウト｜クラウド）ソーシングを試してみたいなあという個人的な思いはあります（他の方から特に反対意見がなければ、ですが）。

ただなにぶん経験がないので（アウト｜クラウド）ソーシングを利用する際のノウハウとかをお持ちの方がいれば是非知見を伺いたいです！

**Comment by shyouhei** [comment]
これそろそろ向き合わないとなー

**Comment by shyouhei** [comment]
@gunjisatoshi ノウハウとか待ってても誰も反応しないのでとりあえず進めていただけますか?

**Comment by gunjisatoshi** [comment]
というわけで、アウトソース（する｜しない）含めて本件を主体的に進めていきたい方を引き続き募集中です。やりたい方はコメントください :bow:

**Comment by miyohide** [comment]
最初の20分ぐらいをやってみて出来そうだったので、やります。

早くて9月末、遅くても10月末ぐらいには文字起こしを終了させる感じで動きます。

適宜、結果はるびまページとしてあげておきます。

**Comment by miyohide** [comment]
今のところ、前半50分までは文字起こしができたので、アップしました。
http://magazine.rubyist.net/?0046-Hotlinks

発言者がわからないとか、聞き取れなかったところとかはとりあえず置いておいて前に進めています。

**Comment by gunjisatoshi** [comment]
@kakutani 「Rubyの会で出しちゃってもよさそうな金額感」ってどれくらいでしょうか。上限があれば教えてください :bow:

というか ruby-no-kai/official のほうの issue にしたほうが良いですね。

**Comment by kakutani** [comment]
> というか ruby-no-kai/official のほうの issue にしたほうが良いですね。

ruby-no-kai/official#199 でよいとおもいます! ありがとうございます~

**Comment by miyohide** [comment]
テープ起こし、アウトソースの結果をいただきました。Hiki化などは引き続き自分が対応します。

**Comment by miyohide** [comment]
アウトソースの結果をHiki化し、49分まで清書した結果を載せました。
http://magazine.rubyist.net/?0046-Hotlinks

いたるところで誰の発言かわからないところがありますので、フォローして頂けますと助かります。

**Comment by shyouhei** [comment]
@kakutani @snoozer05 ご確認ください
@miyohide 確認方法とかをシェアしていただけると… ちょっと久々すぎて…

**Comment by miyohide** [comment]
@shyouhei ログインページ（ http://magazine.rubyist.net/?c=login ）からご自身のアカウントでログイン後、 http://magazine.rubyist.net/?0046-Hotlinks に移動すると確認いただけます（ https://github.com/rubima/rubima/wiki/HowToEditRubyistMagazine ）。

**Comment by snoozer05** [comment]
島田からは、どの程度、校正とかカットとかしちゃって良いものでしょうか。適当にガシガシやっていってしまっても大丈夫でしょうか...??

**Comment by miyohide** [comment]
@snoozer05 適当にガシガシやっちゃってください。

**Comment by snoozer05** [comment]
はい！承知いたしました！

あと、この後のおおよそのマイルストン（校正締切、リリース等）を教えていただいても良いでしょうか...??

**Comment by miyohide** [comment]
@snoozer05 リリース予定は12月初旬です。11月末までにこの記事が出来上がってるというマイルストーンで動きたいです。

**Comment by snoozer05** [comment]
かしこまりましたー

**Comment by gunjisatoshi** [comment]
@miyohide リリース時期を決めたら備忘録として Issue を起こして (参考: https://github.com/rubima/rubima/issues/353) トップページからリンク (参考: https://github.com/rubima/rubima/blob/master/README.md) いただけると幸いです :bow:

**Comment by snoozer05** [comment]
@miyohide @gunjisatoshi 校正、一通り終わったつもりです。あとはリンクつけたりとか、画像とかが必要なところに貼り付けたりすれば、終われるんじゃないかなと思います...!!

**Comment by miyohide** [comment]
無事、52号としてリリース出来ましたのでCloseします。
