### ISSUE TITLE
寄稿記事「Rubyで暦を研究する」

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#350]
- [x] 担当を決める
- [x] 作者から概要をもらう
- [x] 作者から目次アウトラインをもらう
- [x] 作者から記事をもらう
- [x] もらった記事を編集Wikiに転載する
- [x] 編集Wikiの記事を校正する
- [x] 編集した記事を作者に確認してもらう
- [x] 編集MLに作者からの確認が完了した旨を伝える
- [x] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [x] 作者にお礼を伝える

@swallow-life さんより、「Rubyで暦を研究する」という記事を寄稿頂きました（原稿はメーリングリストに展開済み）。

作業進捗用として、Issueを立てておきます。よろしくお願いします。

**Comment by zunda** [comment]
http://magazine.rubyist.net/?0051-FebruaryRectangleWithRuby に転載を始めました。

**Comment by zunda** [comment]
時間を取れそうですので編集を担当します。

**Comment by zunda** [comment]
- [ ] 「2/1」などの日付の表記を「2 月 1 日」などとした方が読みやすいのではないか
- [ ] 配列を返す関数をirbで実行すると結果がみにくい。`puts`するのではなく`.join("\n")`した結果を返すのはどうか?
- [ ] あとがきの「相対位置」について説明が必要ではないか
- [ ] 著者について

**Comment by zunda** [comment]
#353 のリリース予定をメールでお知らせしました。現在は @zunda の校正待ちです

**Comment by gunjisatoshi** [comment]
@zunda ありがとうございます！

**Comment by zunda** [comment]
「編集Wikiの記事を校正する」まで完了しました。

**Comment by zunda** [comment]
著者の方にお礼を伝えました!

**Comment by gunjisatoshi** [comment]
@zunda ありがとうございました！

ということで、本件クローズしますねー
