### ISSUE TITLE
関西Ruby会議06のレポート

### ISSUE THREAD

**Issue by ogom** [rubima/rubima#352]
[関西Ruby会議06](http://regional.rubykaigi.org/kansai06/)を開催しました。レポート作成 Issue を起こします。

開催日は 2015年7月11日 (土) です。
レポート担当は @ogom です。

よろしくお願いします。

----

- [x] 作者から概要をもらう
- [x] 作者から目次アウトラインをもらう
- [x] 原稿を受け取る
- [x] ページ名を決める ( http://magazine.rubyist.net/?0050-XXXX の XXXX の部分)
- [x] 上記名前で auth つきで空ページをつくる (auth つきだとログインしないと見えない)
- [x] 上記で作った空ページにいただいた原稿を転記する
- [x] るびまWiki のアカウントを作って著者の方にお伝えする
- [x] 転記した記事を著者の方に見ていただき、必要であれば加筆修正いただく
- [x] 表紙からリンクを張る
- [x] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [x] リリース時に auth を外して誰でも見える状態にする

**Comment by muryoimpl** [comment]
私、担当しようと思います。

**Comment by muryoimpl** [comment]
@ogom さん、issue の作成ありがとうございます。

レポートについては markdown や hiki で作成いただいた後、るびまの本サイトに非公開のかたちで登録して、リリースまでの間、そこで細かい修正を行った後、リリース時に公開、という流れになっています。
TODO を description に書かせていただきました。上のような流れで進めていく予定でおります。

もし、原稿作成でわからないことがありましたら、お気軽に質問いただければと思います。
よろしくお願いします。

**Comment by ogom** [comment]
原稿は markdown で作成する予定です。公開までよろしくお願いします。

**Comment by ogom** [comment]
原稿を書きました。GitHub Pages で開示するために画像のURLが liquid の形式になっています。
https://raw.githubusercontent.com/rubykansai/kansai06/gh-pages/report/index.md

`{{ site.baseurl }}`は`http://regional.rubykaigi.org/kansai06`です。

**Comment by muryoimpl** [comment]
@ogom 早速の原稿ありがとうございます。
hiki化してるびまサイトに登録したら、確認できるアカウント情報とURLをご連絡差し上げますので、少々お待ちください(この週末に対応予定でおります)

**Comment by ogom** [comment]
@muryoimpl よろしくお願いします。
hiki化にするときに集合写真とアフターパーティーの写真は横並びに３枚並べてもよいかなと思っております。ご対応が可能ならよろしくお願いします。

**Comment by gunjisatoshi** [comment]
0051 号の進行役の方から来ました https://github.com/rubima/rubima/issues/347

関西Ruby会議06のレポートの件ですが、0051 号 (スケジュールは https://github.com/rubima/rubima/issues/353 をご参照) の掲載という認識でよろしいでしょうか（よければ Labels の「掲載号未定」を「51号」に変更したいと思います）。

**Comment by ogom** [comment]
@gunjisatoshi よろしくお願いします。

**Comment by gunjisatoshi** [comment]
@ogom ありがとうございます！

それでは引き続きよろしくお願いします :bow:

**Comment by muryoimpl** [comment]
著者の方に全体的には OK をいただいている状態で、プルーフリーディングの段階に入っています。
ちょっと気になっているところがあるので、リリースまでにちょっとだけ手が入る予定です。

**Comment by gunjisatoshi** [comment]
@muryoimpl 了解です！　引き続きよろしくお願いします :bow:

**Comment by muryoimpl** [comment]
@gunjisatoshi 著者様最終 :ok: を確認しました。

**Comment by gunjisatoshi** [comment]
@muryoimpl ありがとうございます :smiley:

**Comment by muryoimpl** [comment]
@ogom 0051号(http://magazine.rubyist.net/?0051) 先ほどリリースされました。
お忙しいところ寄稿、レビュー、修正にご協力いただきありがとうございました。:smile:
