### ISSUE TITLE
0051 号のリリース時期を決める

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#353]
とりあえず仮置きしますので、問題あればコメントください。今週中くらいには決めちゃいましょう

* 記事申し込み・概要締め切り
    * 7/26 (日)
* 記事の目次、アウトライン締め切り
    * 8/9 (日)
* 記事の締め切り
    * 8/16 (日)
* 校正完了、リリース
    * 9/6 (日)

参考: #324

**Comment by miyohide** [comment]
スケジュール、上記で賛成です。

**Comment by muryoimpl** [comment]
次号掲載予定記事が把握できていないのですが、Hotlinksを掲載しようと考えた場合に、1ヶ月きった状態で文字起こしが収まりそうなのかどうか感覚的に判断できなくて、私はなんとも答えにくい、というのが正直なところです。

**Comment by gunjisatoshi** [comment]
@muryoimpl Hotlinks は奇跡でも起きない限りは次号掲載は無理かと思われます :smile:

次号掲載予定記事はスケジュールを決めたあとで選定することになりますが、記事候補としては article ラベルが貼られた Issue をご参照ください。

https://github.com/rubima/rubima/labels/article

もしどうしても次号に掲載したいけど間に合わない、という記事があるのであれば（たとえば上記でご指摘の Hotlinks とか）ご相談ください。

**Comment by gunjisatoshi** [comment]
とくに反対意見はなかったので、これで Fix とします。

本 Issue は備忘録として Open のままにしておき、0051 号のリリースのタイミングで Close する予定です。

**Comment by miyohide** [comment]
リリース1週間前ですので、現状を共有化します。

#332 monbanの記事 → 著者さんに確認してもらっています。
#348 とちぎRuby会議06 → 終了。リリース待ち。
#318 松江Ruby会議06 → 終了。リリース待ち。
#300 Tokyu Ruby会議08 → 記事なし。8/30に記事が上がってなければ次号送りかなと
#350 Rubyで暦を研究する → 終了。リリース待ち。
#339 浜松Ruby会議01 → 終了。リリース待ち。

**Comment by gunjisatoshi** [comment]
@miyohide ありがとうございます！ Tokyu 08 は次号送りですかねえ

**Comment by miyohide** [comment]
@gunjisatoshi Tokyu 08ですが、今朝確認したところ記事が上がっていました。まだ未記入のところがあるので確認中ですが、51号に入れてしまいたいです。

**Comment by gunjisatoshi** [comment]
@miyohide 承知しました。というわけで表紙からもリンクを作成しました。ナンバリングは修正していませんので、他の記事との兼ね合いで適当に直しといてください :bow:

**Comment by miyohide** [comment]
#332 monbanの記事は著者さんにOKを頂きました。リリース待ちの状態です。

**Comment by miyohide** [comment]
@gunjisatoshi Tokyu 08 ですが、記事をいただけましたので、掲載します。編集完了し、記事の内容について著者さんに確認してもらっています。なお、ナンバリングも合わせて修正しました。

**Comment by gunjisatoshi** [comment]
@miyohide ありがとうございます！

予定通り無事リリースされましたので Close します～
