### ISSUE TITLE
11 周年記念企画について議論するスレ

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#354]
次号は 11 周年記念号になるんですが、実は[前回の 10 周年記念号](http://magazine.rubyist.net/?0048)から 3 号しか進んでないんですね‥‥。なので 3 号に 1 回が n 周年記念号になるのもどうかなあという気がしなくもないです‥‥。

いつもは「[Rubyist Magazine へのたより](http://magazine.rubyist.net/?0048-Comments)」と「[Rubyist Magazine n 周年](http://magazine.rubyist.net/?0048-EditorComment)」という記事を毎回作っているんですけど、これどうしましょう。今後も必要ですかねえ。発行ペースが今くらいなら、2 年に一回にするとか、ちょっと考えてもいいかもしれません。

その他、やりたい企画などありましたら自由にご提案ください！

**Comment by gunjisatoshi** [comment]
特に意見もなかったので、記念企画はなし、また「Rubyist Magazine へのたより」と「Rubyist Magazine n 周年」もお休みにしたいと思います。もうちょっと Close せずに置いときますので、なにかご意見あればコメントください。

**Comment by miyohide** [comment]
11周年記念号というわけではないのですが、RubyKaigi 2015の前にRubyKaigi 2015の紹介記事を寄稿したいという企画案があります。

**Comment by gunjisatoshi** [comment]
@miyohide 了解です！　RubyKaigi 2015 の紹介記事の件は 51 号リリース後にでも別 Issue を立てて議論しましょう :blush:

**Comment by gunjisatoshi** [comment]
0051 号としては完了なので、本件クローズします。12 周年はもうちょっと前から議論したいですね～
