### ISSUE TITLE
0051 号の掲載記事を決める

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#355]
スケジュール https://github.com/rubima/rubima/issues/353 にあるとおり、すでに記事申し込み日を過ぎていますので掲載記事を決めたいと思います。

記事候補は https://github.com/rubima/rubima/labels/article を参照ください。

以前どこかで「巻頭言やアクセスランキング、編集後記などを除いて記事 3 本以上、うち一本は技術的な記事」が最低限のリリース基準という話がありましたが、現状では https://github.com/rubima/rubima/issues/350 と https://github.com/rubima/rubima/issues/346 の 2 本なのであと 1 本は欲しいところですね。

のちほど掲載号未定の各記事を ping してまわりたいとおもいます。

**Comment by gunjisatoshi** [comment]
おっと見落としていました https://github.com/rubima/rubima/issues/339 も掲載予定なので、いちおう現時点でもリリース基準を満たしていることになりますね。

**Comment by znz** [comment]
https://github.com/rubima/rubima/issues/352 も掲載予定で良さそうに見えます。

**Comment by gunjisatoshi** [comment]
@znz ありがとうございます！

とりあえず掲載意志の確認を ping して回りましたので、その回答をもって掲載記事候補をまとめたいと思います。

**Comment by gunjisatoshi** [comment]
掲載見込記事に 51 号ラベルを貼りました。

https://github.com/rubima/rubima/labels/51%E5%8F%B7

もうちょっとしたら別 Issue にて担当のついていない記事の担当者募集をしましょう。

**Comment by gunjisatoshi** [comment]
掲載予定記事については https://github.com/rubima/rubima/issues/359 にて担当者アサインを実施済みなので、こちらは Close します。
