### ISSUE TITLE
0051 号掲載予定記事の担当編集を決める

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#359]
記事候補 https://github.com/rubima/rubima/labels/article から 51 号ラベルのついている記事を下記に書き出しました。抜けがあったら指摘してください。

* 0051 号 巻頭言 https://github.com/rubima/rubima/issues/356 @gunjisatoshi が担当します
* 関西Ruby会議06のレポート https://github.com/rubima/rubima/issues/352 @muryoimpl さん
* 寄稿記事「Rubyで暦を研究する」 https://github.com/rubima/rubima/issues/350 @zunda さん
* RedDotRubyConf 2015 レポートhttps://github.com/rubima/rubima/issues/346 @gunjisatoshi が担当します
* 浜松Ruby会議01レポート https://github.com/rubima/rubima/issues/339 @miyohide さん
* monban の記事 https://github.com/rubima/rubima/issues/332 @sunaot さんがやりとりされていますが、担当編集はまだ決まっていない？→　@miyohide さん
* 松江 Ruby 会議 06 レポート https://github.com/rubima/rubima/issues/318 @miyohide さん
* ~~factory_girlとテストデータ、テストコードの記事 https://github.com/rubima/rubima/pull/310 決まっていない？ →　@miyohide さん → 0051 号の掲載は見送りになりました~~
* Tokyu Ruby 会議 08 レポート https://github.com/rubima/rubima/issues/300 @miyohide さん
* とちぎ Ruby 会議 06 レポート https://github.com/rubima/rubima/issues/348 @miyohide さん

というわけで、まだ決まっていないのは「factory_girlとテストデータ、テストコードの記事」と「monban の記事」でしょうか。

**Comment by miyohide** [comment]
#310 の factory_girlとテストデータ、テストコードの記事については、みよひでが担当しようかなと思っています。他の地域Ruby会議系のものは大体終わりが見えているので、多分大丈夫でしょう。

**Comment by gunjisatoshi** [comment]
@miyohide ありがとうございます！（最近はみよひでさん頼みですみません‥‥）

**Comment by gunjisatoshi** [comment]
@sunaot monban の記事の件ですが、お忙しいようであれば誰か他の人に担当いただくことも考えたいと思います。現状（のお忙しさは）どんな感じでしょうか。

**Comment by miyohide** [comment]
@gunjisatoshi さん、 @sunaot さん、 #332 の monban の記事、引き取りましょうか？とりあえず、何もリアクションがないのは先方も不安を与えてしまうので、コメントを記しておきたいと思います。

**Comment by miyohide** [comment]
#310 （factory_girlとテストデータ、テストコードの記事）は51号キャンセルとなりました。

**Comment by gunjisatoshi** [comment]
@miyohide 任せっきりですみません :bow: お言葉に甘えてお任せしますので、よろしくお願いします :bow: :bow: :bow:

**Comment by miyohide** [comment]
#332 の monban の記事は作者さんのOKを頂きました。公開可能な状態です。

**Comment by gunjisatoshi** [comment]
基本的に現在表紙からリンクのある記事はすべてリリース可能という認識です。もし問題あるようでしたら本日 22:00 までにご連絡ください。

**Comment by miyohide** [comment]
@gunjisatoshi Tokyuの記事ですが、写真提供者の大場さん（ https://twitter.com/koichiroo ）にOKがとれているか確認中です。すみません、もう少しお待ちください。

**Comment by gunjisatoshi** [comment]
@miyohide りょうかりです！

**Comment by miyohide** [comment]
@gunjisatoshi OK取れました。リリースOKです。

**Comment by gunjisatoshi** [comment]
@miyohide ありがとうございます！

**Comment by gunjisatoshi** [comment]
先ほどリリース作業を実施しました。各記事担当の方は、著者の方にご連絡をお願いします :bow:

**Comment by sunaot** [comment]
@miyohide Monban の記事、フォローしていただき、本当にありがとうございました。私事のほうで手一杯でるびまへ回す頭がなくなっていたので助かりました。。

**Comment by gunjisatoshi** [comment]
無事 0051 号がリリースされましたので、本件クローズします。各記事担当の皆様ありがとうございました！
