### ISSUE TITLE
0051 号 編集後記

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#361]
編集後記のお題（～といえば）を募集します。ちなみに 11 周年なんですが、今回は記念号という形にはしない予定なので「11 と言えば」ではなくても良いかなあと思います。

**Comment by miyohide** [comment]
「夏バテ防止法」とか「夏休み」とかどうでしょう。

**Comment by gunjisatoshi** [comment]
お題の案をありがとうございます！

しかし 9 月リリースなのでちょっと季節はずれかなあという気もするので、いただいた案を参考に適当に考えます :smiley:

**Comment by gunjisatoshi** [comment]
というわけで「休み明け」といえば、にしましたので皆様書き込みをよろしくお願いします！

**Comment by gunjisatoshi** [comment]
まだ三人と少し寂しいので、リリース後でも構わないので記入をお願いします！

**Comment by zunda** [comment]
遅くなりました! リリース後ですが記入しました :)

**Comment by gunjisatoshi** [comment]
@zunda ありがとうございます！

というわけで、本件クローズしますー
