### ISSUE TITLE
0051 号アクセスランキング

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#362]
以前 https://github.com/rubima/rubima/issues/313#issuecomment-66380842 でも書いていますが、るびまの Google Analytics アカウントを持っている人 https://github.com/rubima/rubima/issues/152 なら https://github.com/rubima/rubima/issues/273#issuecomment-39480713 の手順に従って誰でもこの記事を作ることができます。どなたかやりませんか（やってみたいけど Google Analytics のアカウントがないよ！という方はご連絡ください）。

**Comment by gunjisatoshi** [comment]
誰もやる人がいなそうなので、リリース作業のタイミングで私が作成することにします :smile:

**Comment by hsbt** [comment]
:bow: るびま編集部の新入部員勧誘もしていかねば〜

**Comment by gunjisatoshi** [comment]
作りましたー
