### ISSUE TITLE
0051 号をリリースする

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#364]
- [x] るびま編集コミュニティ全員に 0051 号全体のプルーフリーディングのお願いをする see https://github.com/rubima/rubima/issues/363
- [x] るびま編集コミュニティ全員に編集後記の記載を促す see https://github.com/rubima/rubima/issues/361
- [x] リリースの時刻を決める → とりあえず 9/6(Sun) 22:00 とします
- [x] 各記事の担当者に担当記事がリリースできる状態になっているか確認する
- [x] ~~リリースできないと判断した記事があれば、表紙から落とす~~ 今回はなし
- [x] 旧編集Wikiでリハーサルする (SideMenuとか目次ページとかの表示を確認する)
- [x] リリース時刻にリリース作業をする (各記事のauthを外し、各号目次、分野別目次、SideMenu および表紙を更新する)
- [x] 「ログアウトした状態ですべての記事が正常に見られること」の確認
- [x] RSSの更新をする
- [x] リリースした旨を日本Rubyの会 ML と ruby-list に告知する
- [x] https://github.com/ruby-no-kai/official/wiki を更新する
- [x] 日本Rubyの会のトップページに掲載するために、https://github.com/ruby/www.ruby-lang.org への pull request をする
- [x] 各記事の担当者に担当記事の著者へのお礼をするよう促す

参考: https://github.com/rubima/rubima/issues/274 [るびまリリース手順](https://github.com/rubima/rubima/wiki/ReleaseProtocol)

**Comment by gunjisatoshi** [comment]
そろそろリリース作業を開始しますが、問題あるようでしたら随時連絡ください。

**Comment by gunjisatoshi** [comment]
先ほどリリース作業を実施しました。RSS の更新と日本 Ruby の会への pull request は明日実施します。

担当の皆さま、お疲れさまでした :beer:

**Comment by miyohide** [comment]
@gunjisatoshi リリース作業お疲れ様でした。

**Comment by gunjisatoshi** [comment]
pull request 出しました https://github.com/ruby/www.ruby-lang.org/pull/1181

**Comment by gunjisatoshi** [comment]
RSS も更新しました！
（しかし毎回手で更新するのも面倒なので、いずれ何とかしたい）

**Comment by zunda** [comment]
ありがとうございます :+1:

**Comment by gunjisatoshi** [comment]
pull request もマージされて無事掲載されました https://www.ruby-lang.org/ja/news/2015/09/06/rubyist-magazine-0051-published/ ので本件クローズします。皆様ありがとうございました！
