### ISSUE TITLE
RubyConf Taiwan 2015 レポート

### ISSUE THREAD

**Issue by muryoimpl** [rubima/rubima#366]
@yucao24hours さんより、RubyConf Taiwan 2015 の参加レポートを寄稿予定とのお話をいただきましたので、取り急ぎ Issue を登録させていただきます。

**Comment by miyohide** [comment]
@muryoimpl さん、 @yucao24hours さん。るびま52号進行役の @miyohide です。

るびま52号ですが、

記事申し込み・概要締め切りを11/1 (日)、記事の締め切りを11/22 (日)、リリースを12/6 (日)の予定で進めようかと考えております（ #369 ） 。記事の状況はいかがでしょうか。

**Comment by muryoimpl** [comment]
@miyohide 
現在記事を作成いただいているところで、日程的には問題ないとの回答をいただきましたのでご報告いたします。よろしくお願いします。

**Comment by miyohide** [comment]
@muryoimpl さん、ご連絡ありがとうございます。了解しました。

**Comment by miyohide** [comment]
@muryoimpl さん、リリースまであと1週間ほどとなりましたが、状況いかがでしょう。あとは写真を貼れば良さそうに思えました。

**Comment by muryoimpl** [comment]
@miyohide (1週間前…) 画像の処理は今晩中にします。
タイトルがまだ決まっていないので、タイトルいただいてきます

**Comment by miyohide** [comment]
@muryoimpl 画像処理、お手伝いしましょうか。

**Comment by muryoimpl** [comment]
@miyohide 画像をgistにおいてもらっていたのですが、容量オーバーか何かで削除されてしまっていて旧PCから今サルベージしていただいている最中なのです…画像が来れば変換はすぐにできそうです。

**Comment by muryoimpl** [comment]
@miyohide
筆者の方から写真・文章いただきチェックOK、私も再度確認して特に問題ないと思います。
リリースready だと思っております。

**Comment by miyohide** [comment]
@muryoimpl 担当ありがとうございます。了解しました。

**Comment by miyohide** [comment]
@muryoimpl さん、本記事担当ありがとうございます。先ほど、無事るびまをリリース出来ました。著者の方にもご連絡・お礼をしていただけますと助かります。

**Comment by muryoimpl** [comment]
@yucao24hours
るびまリリースされました！ 写真の件等いろいろお手数おかけしてしまいましたが、無事公開できました。ありがとうございました :smile:
