### ISSUE TITLE
0052号 巻頭言

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#370]
@takahashim いつも巻頭言をご執筆いただき、ありがとうございます。

0052 号の発行予定は現在のところ 12/6 (日) となっております（ #369 ）。
お忙しいところ恐縮ですが、発行の 1 週間前（11/29（日））までに巻頭言の原稿を頂けると助かります。
それでは、よろしくお願いいたします :bow:

**Comment by takahashim** [comment]
う、厳しそうな時期ですが頑張ります…！

**Comment by miyohide** [comment]
@takahashim お忙しいところ申し訳ございませんが、本件状況いかがでしょうか。

**Comment by takahashim** [comment]
うううすみません、今晩中に第一稿があがるかも、というところです…

**Comment by SugHimsi** [comment]
(配布それ自体もWWW勃興前夜にはネットニューズでありFTPでしたからね…)

**Comment by SugHimsi** [comment]
偉大さ、の一文に違和感。(どこに書いてあるの?と思った。「いくら」の前に「きっと、」と付ければよいのかな。)

**Comment by SugHimsi** [comment]
(ほかの記事を読んでいるが、松江 Ruby 会議 07 #351 の基調講演と読み合わせて矛盾がないか心配)

**Comment by takahashim** [comment]
だいたい修正も終わりましたっ

**Comment by miyohide** [comment]
@takahashim お忙しい中、寄稿ありがとうございました。

**Comment by miyohide** [comment]
@takahashim さん、先ほどるびまを無事リリースすることができました。ご対応ありがとうございました。
http://magazine.rubyist.net/?0052

**Comment by takahashim** [comment]
@miyohide リリースおつかれさまでした！
