### ISSUE TITLE
0052 号の記事募集する

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#371]
ちょっと記事が足りないかもしれないなあ、ということで Issue とします。

（ちなみに昨日たまたま [idobata 会議 02](https://idobata.doorkeeper.jp/events/31060) に行ったら @sunaot さんとばったり会ったので、一緒に会場にいた何人かに「記事書きませんか」と声かけをしたことをここに記録しておきます）

**Comment by miyohide** [comment]
@gunjisatoshi さん、 @sunaot さん、記事集めありがとうございます。来週の大江戸Ruby会議において、私も記事集めをやってみようかと思います。ご協力頂けますと助かりますm(_ _)m

**Comment by miyohide** [comment]
リリースできたので、Closeします。
