### ISSUE TITLE
esa.io の作り方 (仮) の記事

### ISSUE THREAD

**Issue by sunaot** [rubima/rubima#372]
@gunjisatoshi と一緒にお願いをして @fukayatsu さんに esa.io の裏側の紹介記事を書いてもらうことになりました。
担当編集者募集中です。掲載号の相談から (最短だと12月発行の 52 号)。

**Comment by fukayatsu** [comment]
よろしくお願い致します〜 "(\\( ⁰⊖⁰)/)"

**Comment by miyohide** [comment]
@fukayatsu さん、よろしくお願いします。最短だと52号（11/22記事締め切り、12/6リリース予定）ですが、難しいようであれば、53号（4月頃リリース？）となります。

**Comment by fukayatsu** [comment]
@miyohide 了解です！

ひとまず 11/9 (月) までにアウトライン書いてみます

**Comment by fukayatsu** [comment]
一旦頭の中をdump

- 開発の裏側
    - 未だにstaging環境がない
    - スケジュールを決めない
    - ノルマがない
    - github flow; masterにpushしたら本番デプロイ
    - 自動 bundle update
- サポートの裏側(運用に含まれるかも。どちらかと言うと運営?)
    - 5分で返信するのが目標
    - 「はい/いいえ」よりもよい返事がある
        - 出典忘れた
    - github sync
- 運用の裏側
    - Heroku
        - buildpack
        - dyno数のスケジューリング
        - preboot
    - 障害監視
    - リリースノートをwebhookで受け取る
- モチベーションの裏側
    - (\\( ⁰⊖⁰)/)
    - ステッカー等のグッズ
    - twitter.com/esa_io
        - エゴサ
- あの機能の裏側
    - 外部公開機能
    - セキュアオプション
    - 3 way merge
- esa LLCの裏側
    - 人を増やさない
    - 部室
        - IRKit

**Comment by sunaot** [comment]
開発や運用の裏側くらいを期待していたら、あちこちの裏側が聞けそうでとても楽しみです

**Comment by kurotaky** [comment]
@fukayatsu さん
/cc @miyohide @gunjisatoshi @sunaot 
esaの記事を担当します @kurotaky です。よろしくお願いします!

52号掲載予定で進めさせていただきたいと思います。
リリースまでのスケジュールは以下のようになっています :calendar: 

* 11/22(日)  記事締め切り
* 12/6(日) リリース予定

記事は最終的にはHiki記法で書く必要がありますが、
初稿はMarkdown形式でも問題ありません。よろしくお願いします! :ok_woman:

**Comment by kurotaky** [comment]
## 編集担当者ToDoリスト
- [ ] 担当を決める
- [ ] 作者から概要をもらう
- [ ] 作者から目次アウトラインをもらう
- [ ] 作者から記事をもらう
- [ ] もらった記事を編集Wikiに転載する
- [ ] 編集Wikiの記事を校正する
- [ ] 編集した記事を作者に確認してもらう
- [ ] 編集MLに作者からの確認が完了した旨を伝える
- [ ] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [ ] 作者にお礼を伝える

**Comment by fukayatsu** [comment]
@kurotaky 承知しました。よろしくお願いします！

**Comment by kurotaky** [comment]
=͟͟͞͞ (\\( ⁰⊖⁰)/)

**Comment by fukayatsu** [comment]
MindMapで作業中: https://my.mindnode.com/aHjQT76RBsPdCmAX1ZLzDyGEampLUzPFvXi5XVuq

**Comment by kurotaky** [comment]
@miyohide @sunaot @gunjisatoshi 
こちらの記事、52号掲載予定で進めています。
権限ある方、どなたか Labels から **掲載号未定** を外して **52号** を付けていただけますか?
よろしくお願いします~

**Comment by miyohide** [comment]
無事、リリース出来ました。 @kurotaky さん、担当ありがとうございます。 @sunaot さん、 @gunjisatoshi  さん記事の充実化にご尽力いただき、ありがとうございました。
