### ISSUE TITLE
大江戸Ruby会議 05 レポート

### ISSUE THREAD

**Issue by fukajun** [rubima/rubima#373]
大江戸Ruby会議 05 レポート作成 issue を起こします。

レポート担当は @shokola @1syo @kei-s @stshsmt @fukajun  です。
記事が出来上がるまでのrubima担当さんとの窓口は 僕 fukajun がやります。
開催は 2015年11月8日 でした。
よろしくお願いします。

cc: @ko1 
レポートのIssue作りました

**Comment by ko1** [comment]
ありがとう御座います。無理だけはしないように、気楽にお願いします！

**Comment by miyohide** [comment]
@fukajun るびま編集のみよひでです。
次号のるびまのスケジュールは
- 記事申し込み・概要締め切り: 2016年2月28日 (日)
- 記事の目次、アウトライン締め切り: 2016年3月6日 (日)
- 記事の締め切り: 2016年3月20日 (日)
- 校正完了、リリース: 2016年4月3日 (日)
を予定しております。

記事の作成等、どのような状況でしょうか。

**Comment by fukajun** [comment]
今週、文章を書き直す予定です。

**Comment by fukajun** [comment]
@miyohide どのようなフォーマットで提出すればよいですか？
過去のサンプル等あれば教えて下さい。

**Comment by miyohide** [comment]
@fukajun るびまの記事フォーマットはHiKiとなります。できればHikiでの提出をお願いしたいのですが、Markdownでの提出でも受け付けています。どちらか書きやすい方でご提出下さい。

なお、Markdownで表現できるもののうち、一部るびまでは表現できないものがあります（例えば一行コード）のでご了承ください。

記事はメールで私宛（miyohide @ gmail . com )まで送ってください。写真などを貼り付ける場合は合わせて送付して下さい。

編集部で記事の編集を行った後、認証が必要なるびまのサイトに載せます。その際にご連絡しますので、ご確認ください。

**Comment by fukajun** [comment]
@miyohide おおよそ、記事の全体が出来上がりつつあるという状態なので、
記事申し込みたいです。

**Comment by miyohide** [comment]
@fukajun では、記事を上記コメントに記したメールアドレスまで送付いただけますか？

**Comment by miyohide** [comment]
@fukajun 昨日、記事申込・概要締め切り日だったのですが、状況いかがでしょうか。

**Comment by fukajun** [comment]
@miyohide すみません、連絡を忘れていました。
ちょっとメールだと送りにくいのでURLを送ります。
https://dl.dropboxusercontent.com/u/30627288/oedo-rubima-master.zip

**Comment by fukajun** [comment]
現在の状況を説明すると、おおよそ文章の修正・校正は済んでいて
残り、記事の最初、最後の説明 + 記事を書いた人の簡単なプロフィールを追加する
のが残っている状態です。

**Comment by miyohide** [comment]
@fukajun 記事の送付ありがとうございます。ざっと見れる状態にしました。
http://magazine.rubyist.net/?0053-OoedoRubyKaigi05Report

上記URLにるびまアカウントでログイン後アクセスしてください。

るびまアカウントをお持ちでない場合は発行しますので、メールにてご連絡ください。その返信メールにてアカウント情報（ユーザ名・パスワード）をお知らせいたします。

**Comment by fukajun** [comment]
さっき送付したので、ちょっと確認してみて追って不明な点等あれば質問させてください。

**Comment by miyohide** [comment]
@fukajun アカウント情報を記したメールを送付しましたので、ご確認ください。

**Comment by fukajun** [comment]
@miyohide 反映ありがとうございます。
確認しました。再度、ここから更新があるのですその場合はどのように反映するのが良いのでしょうか？ 元の原稿は前と変わらず、 markdown を使っています。すでにhiki形式に変えていただいたようですが.....

- 前からの差分をこちら側で手動反映？
- @miyohide さんのほうでmarkdownを hiki に変える便利な方法があります？

その反映が終わったら @ko1 さんに、最終的な手直し入れていただく予定でいます。

**Comment by miyohide** [comment]
@fukajun 確認ありがとうございます。
差分ですが、できれば @fukajun 側で手動反映をお願いしたいです。
手動反映が大変な場合は、私が対応しますが、その際は早めにご連絡を頂けますでしょうか。3/13までに記事の最終稿を送付頂けますと助かります。

**Comment by fukajun** [comment]
ちなみに `markdown` => `hiki` への変換はどのように行ったのでしょうか？
1. 完全手動？
2. スクリプト？(こっちだったら再度それにかけてdiffとかしたい。)
3. 2 + 一部手動？
たぶん1ですかね？

**Comment by miyohide** [comment]
@fukajun 3ですね。ほぼ手動ですが。

**Comment by fukajun** [comment]
@miyohide では、こちらで手動で反映します。
画像で増えたものがあるんですが、変換等ってどうされましたか？
すみません、いろいろ知らないことが多くて....

**Comment by miyohide** [comment]
@fukajun 画像変換は、convertコマンドで縮小しました。元ファイルの10%ぐらいにすると今、貼り付けている画像のサイズになりました。ですが、画像次第ですので、最後は目で確認して微調整をしています。

あとは、変換した画像ファイルを記事編集画面で添付ファイルとしてアップロードし、文中でattr_viewなんかを挿入すると見えるようになります。

**Comment by miyohide** [comment]
@fukajun 本日3月20日（日）が記事の締切日となっているのですが、状況いかがでしょうか。

**Comment by fukajun** [comment]
@miyohide @ko1 さんの方で最終的に記事の微調整を行うとのことでしたがその後いかがでしょうか？
@ko1 さんの方で問題なければ現時点の状態で大丈夫です。

**Comment by fukajun** [comment]
@miyohide あっ、書いた人に最終的な状態を一度見せたいのでお待ちを！

**Comment by ko1** [comment]
On 2016/03/21 1:09, fukajun wrote:
> @miyohide <https://github.com/miyohide> @ko1 <https://github.com/ko1> さ
> んの方で最終的に記事の微調整を行うとのことでしたがその後いかがでしょうか？
> @ko1 <https://github.com/ko1> さんの方で問題なければ現時点の状態で大丈夫
> です。

すみません、あす頑張ります...。


-- 
// SASADA Koichi at atdot dot net

**Comment by miyohide** [comment]
@fukajun すみません、1点確認させてください。
Zachary Scottさんの発表タイトルが「TODO」になっているのですが、これはこういうタイトルで良いのでしょうか。

**Comment by ko1** [comment]
TODO 解決済みということで何よりです。
こちら、遅くなっていてすみません、今からやります。diff、後で貼り付けますね。

**Comment by ko1** [comment]
遅くなりました。修正しました。diff のほうは、レポート班のほうへ、お送りしました。

**Comment by kurotaky** [comment]
@fukajun @ko1 
cc/ @miyohide 
修正後の記事の内容確認しました。執筆ありがとうございました！
http://magazine.rubyist.net/?0053-OoedoRubyKaigi05Report

こちらの内容で、本日4/3(日)の夜(18:00すぎくらい)に公開します。よろしくお願いします

**Comment by fukajun** [comment]
こちらこそ、ありがとうございました。

**Comment by miyohide** [comment]
@fukajun 今回は寄稿ありがとうございました。先ほどるびま 0053 号のリリースが完了しましたのでご連絡いたします。
今後ともRubyist Magazine るびまをご愛読、また寄稿をお待ちしております。
