### ISSUE TITLE
0052号 編集後記

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#375]
編集後記のページを作成する。

お題をどうするかですが、RubyKaigiの直前なので「RubyKaigiといえば」とはどうでしょうか。

**Comment by miyohide** [comment]
ページ作成したので、ご記入お願いします。
http://magazine.rubyist.net/?0052-EditorsNote

**Comment by miyohide** [comment]
先ほど、るびま52号をリリース出来ました。担当編集を引き受けていただいた @kurotaky さんや @muryoimpl さんはぜひとも追記をお願いします。

**Comment by kurotaky** [comment]
リリースおつかれさまです! 追記しました。
