### ISSUE TITLE
0052 号のアクセスランキングを作る

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#377]
アクセスランキングを作成する。

どなたか協力頂けませんでしょうか。

**Comment by hsbt** [comment]
(アカウント情報欲しければバンバン配布します)

**Comment by kurotaky** [comment]
@miyohide 
やります!

@hsbt 
アカウント情報欲しいです!
:mailbox_with_mail: `yuta.kurotaki@gmail.com` です。

**Comment by hsbt** [comment]
追加しました!

**Comment by kurotaky** [comment]
ありがとうございます!

**Comment by gunjisatoshi** [comment]
@kurotaky おねがいします！
(参考: https://github.com/rubima/rubima/issues/273#issuecomment-39480713 )

**Comment by kurotaky** [comment]
便利情報ありがとうございます :octocat:

**Comment by miyohide** [comment]
@kurotaky すみません、本件進捗どうでしょう。

**Comment by miyohide** [comment]
@hsbt すみません、私もアカウント情報頂けますか？ `miyohide@gmail.com` です。

**Comment by kurotaky** [comment]
@miyohide @gunjisatoshi 
[0052 号 アクセスランキング](http://magazine.rubyist.net/?0052-RubyistMagazineRanking) 作成しました!

:memo: 
* 集計期間は前号発行日の 2015/09/06 から 2015/12/05 までのアクセスを集計
* るびまのトップページ、0051号のトップページ、常設記事のFirstStepRubyはランキングに含めない

**Comment by miyohide** [comment]
@kurotaky 作成ありがとうございます。助かります。

**Comment by kurotaky** [comment]
:smile:

**Comment by miyohide** [comment]
@kurotaky  無事、リリース出来ました。作成ありがとうございました。
