### ISSUE TITLE
0052 号をリリースする

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#378]
- [x] るびま編集コミュニティ全員に 0052 号全体のプルーフリーディングのお願いをする
- [x] るびま編集コミュニティ全員に編集後記の記載を促す
- [x] リリースの時刻を決める → 12/6(Sun) 20:00 とします
- [x] 各記事の担当者に担当記事がリリースできる状態になっているか確認する
- [x] リリースできないと判断した記事があれば、表紙から落とす
- [x] 旧編集Wikiでリハーサルする (SideMenuとか目次ページとかの表示を確認する)
- [x] リリース時刻にリリース作業をする (各記事のauthを外し、各号目次、分野別目次、SideMenu および表紙を更新する)
- [x] 「ログアウトした状態ですべての記事が正常に見られること」の確認
- [x] RSSの更新をする
- [x] リリースした旨を日本Rubyの会 ML と ruby-list に告知する
- [x] https://github.com/ruby-no-kai/official/wiki を更新する
- [x] 日本Rubyの会のトップページに掲載するために、https://github.com/ruby/www.ruby-lang.org への pull request をする
- [x] 各記事の担当者に担当記事の著者へのお礼をするよう促す

参考: https://github.com/rubima/rubima/issues/274 [るびまリリース手順](https://github.com/rubima/rubima/wiki/ReleaseProtocol)

**Comment by SugHimsi** [comment]
巻頭言 #370 の番人さんも募集、かな。

**Comment by miyohide** [comment]
@gunjisatoshi 52号リリース時点で、RSSの更新というのがあるのですが、ご協力頂けますでしょうか。作り方が分かっておらず、どのようにすればよろしいでしょうか。

**Comment by gunjisatoshi** [comment]
@miyohide だいたいこんな感じです。

* 表紙が完成したらそれを元に手で XML ファイルを作成
* https://github.com/rubima/hiki/blob/master/public/atom.xml を上記で置き換え
* sqale にデプロイ

なので、rubima/owners グループに所属していて、かつ sqale のるびまアカウント情報を知っていて、かつ上記の XML を手で作れる人、じゃないと作業難しいですね。なので私がやります。
（まあ RSS はオマケなのでリリースして一週間以内くらいにやればいいかなぁという感じです）

**Comment by miyohide** [comment]
では、リリース作業を始めます。

**Comment by miyohide** [comment]
リリースしました。ご協力ありがとうございました。

**Comment by fukayatsu** [comment]
リリース作業ありがとうございました！

**Comment by miyohide** [comment]
@gunjisatoshi お忙しい中申し訳ありませんが、RSSのatom.xmlを更新するPull Requestを出しましたので、ご確認の上更新して頂けますでしょうか。 rubima/hiki#18

**Comment by gunjisatoshi** [comment]
@miyohide ありがとうございます (さぼっててすみません :bow: ) 反映しました！
