### ISSUE TITLE
読者プレゼント

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#381]
@mame さんより、『あなたの知らない超絶技巧プログラミングの世界』( http://gihyo.jp/book/2015/978-4-7741-7643-7 ) を2冊ご提供いただける、というお話をいただいております（ありがとうございます）。

取り急ぎ、私が担当します。0053号（2016年3月〜4月頃）をターゲットとして動きます。

**Comment by miyohide** [comment]
ページを作りました。
http://magazine.rubyist.net/?0053-Present

過去の記事を見ると、プレゼントフォームを用意するとあるのですが、プレゼントフォームってどうやって作るかご存じですか？ > @gunjisatoshi

**Comment by hokkai7go** [comment]
@miyohide 0049号でプレゼントフォームを作ったので情報共有します。
当時のフォームは以下のリンクからどうぞ。GoogleFormで作って、締め切り後に発送の手配を笹田さんにお願いした経緯があったはずです。
https://docs.google.com/forms/d/1I01qM26fvkALf-Ubv6HueCJW9bWs2bBtChY1KyEz2Uo/viewform

当時のやりとりはこちらを参照ください
https://github.com/rubima/rubima/issues/338

**Comment by miyohide** [comment]
@hokkai7go 情報共有ありがとうございます。GoogleFormで作っておけばいいんですね。了解しました。

**Comment by kdmsnr** [comment]
53号は「Rubyist Hotlinks」に登場したので、『メタプログラミングRuby 第2版』を読者プレゼントに出したいです。遠藤さんの本にあわせて、こちらも2冊でお願いします。

**Comment by miyohide** [comment]
@kdmsnr 反応遅れてすみません。読者プレゼントの提供、ありがとうございます。
読者プレゼントのページを更新しましたので、ご確認ください。
http://magazine.rubyist.net/?0053-Present

また、るびま編集部としてはプレゼントの当選者を @kdmsnr にお知らせする形をとり、以降の発送までの作業はお願いしたいと考えているのですが、問題ありませんでしょうか。

**Comment by kdmsnr** [comment]
はい、大丈夫です。

**Comment by kdmsnr** [comment]
表紙からもリンクがあるといいですね

**Comment by kurotaky** [comment]
内容確認しました。表紙にもリンクがあります :book: 
http://magazine.rubyist.net/?0053-Present
プレゼントの提供ありがとうございました！

**Comment by kurotaky** [comment]
@kdmsnr 
cc @miyohide 
記事の内容確認しました。執筆おつかれさまでした。
http://magazine.rubyist.net/?0053-Present
こちらの内容で、本日4/3(日)の夜(18:00すぎくらい)に公開します。よろしくお願いします!

**Comment by miyohide** [comment]
抽選をするためのIssueを個別に起こしたので、これは一旦Closeします。
