### ISSUE TITLE
TRICK 2015 結果発表の報告記事 寄稿

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#382]
@mame さんより、「TRICK 2015 結果発表の報告記事」の寄稿のご連絡をいただきました。

0053号（2016年3月〜4月）をターゲットとして動きます。

**Comment by miyohide** [comment]
@mame さん、次号のるびまですが、

-    記事申し込み・概要締め切り: 2016年2月28日 (日)
-    記事の目次、アウトライン締め切り: 2016年3月6日 (日)
-    記事の締め切り: 2016年3月20日 (日)
-    校正完了、リリース: 2016年4月3日 (日)

を目標に進める予定です。ご認識の程よろしくお願いします。

**Comment by mame** [comment]
@miyohide さん、スケジュールありがとうございます。放置していてすみません。一応、ドラフトのドラフトみたいなものはできているので、今週中にドラフト段階まで進めたいと思います。

**Comment by mame** [comment]
ドラフト段階くらいにはなった気分です！るびまの wiki を見てみましたが、まだ 53 号の予定地は存在しないですかね。出来次第貼り付けたいと思います。他に提出方法あれば教えてください。

**Comment by miyohide** [comment]
早速のご対応ありがとうございます。予定地作りました。
http://magazine.rubyist.net/?0053-TRICK2013

ここに貼り付けていただければ。

**Comment by mame** [comment]
ありがとうございます、貼り付けました！

他の審査員にもレビューしてもらいたいのですが、このプレビューサイトを他の審査員にも教えていいでしょうか？前回の記事の時に、レビューのために "trick2013" というアカウントを作ってもらったので、それを再利用するつもりです。

**Comment by elim** [comment]
> http://magazine.rubyist.net/?0053-TRICK2013

横から失礼します URL が 2013 ですけど OK な感じでしょうか……（よくわかってなくてすみません

**Comment by ko1** [comment]
発表だと、一番凄いのが最後でしたが、
文章だと、最初から凄い奴のほうが良かったりしないでしょうか。

上の方だけ読む人も多いので、凄いやつを、なるべく疲れていない時に読んでもらうのが良いかな、と。
ただの提案なので、ご検討頂ければ。

**Comment by miyohide** [comment]
@elim さん、ご指摘ありがとうございます。私の単なるミスです。修正しました。
新しいURLはこちらになります。
http://magazine.rubyist.net/?0053-TRICK2015

**Comment by miyohide** [comment]
@mame さん、早速の記事貼り付けありがとうございます。URLの連絡はOKです。
なお、URLを http://magazine.rubyist.net/?0053-TRICK2015 に修正しております。

**Comment by mame** [comment]
修正ありがとうございます！では、審査員に URL 伝えてレビューしてもらいます。

@ko1 さん、ご意見ありがとうございます。そのようにしてみました。自分が後半ほど解説さぼってるのが目立つようになりました。

**Comment by elim** [comment]
> 新しいURLはこちらになります。

@miyohide さん、ありがとうございました :+1:

**Comment by kurotaky** [comment]
@mame 
cc @miyohide 
記事の内容を確認しました。執筆おつかれさまでした！
http://magazine.rubyist.net/?0053-TRICK2015
こちらの内容で、本日4/3(日)の夜(18:00すぎくらい)に公開します。よろしくお願いします。

**Comment by mame** [comment]
ご確認ありがとうございました！ 公開について承知しました。こちらこそよろしくお願いします。

**Comment by miyohide** [comment]
@mame 今回は寄稿ありがとうございました。先ほどるびま 0053 号のリリースが完了しましたのでご連絡いたします。
今後ともRubyist Magazine るびまをご愛読、また寄稿をお待ちしております。

**Comment by miyohide** [comment]
@mame すみません、1点確認させてください。
記事中、5位の「Most general solver」のソースコードのリンク先ですが、「ksk_1」ではなく、「ksk_2」の誤記でしょうか？

**Comment by mame** [comment]
@miyohide おっしゃるとおりです！直してみました。ありがとうございます。

**Comment by miyohide** [comment]
@mame ご対応ありがとうございました。
