### ISSUE TITLE
Compiling Ruby scripts (RubyKaigi2015 発表）の記事

### ISSUE THREAD

**Issue by ko1** [rubima/rubima#383]
書きます。
誰か編集やってくれないかな。

**Comment by kurotaky** [comment]
@ko1 
こんにちは、るびま編集のくろたきです。
Compiling Ruby scripts の記事を担当します。

0053号のリリースまでのスケジュールは以下のようになっております。

* 記事申し込み・概要締め切り: 2016年2月28日 (日)
* 記事の目次、アウトライン締め切り: 2016年3月6日 (日)
* 記事の締め切り: 2016年3月20日 (日)
* 校正完了、リリース: 2016年4月3日 (日)

よろしくお願いします！

**Comment by ko1** [comment]
お、がんばりまｓ。

**Comment by kurotaky** [comment]
@ko1 
記事申し込み・概要締め切り: 2016年2月28日 (日) でした。
連絡遅くなってすみません > <

タイトルは Compiling Ruby scripts でよろしいでしょうか？
また、概要は http://rubykaigi.org/2015/presentations/ko1 にかかれているものと同じ感じになりそうですかね？

記事の目次、アウトライン締め切りが2016年3月6日 (日)となっております。
よろしくお願いします！

**Comment by kurotaky** [comment]
@ko1 
こんにちは、Compiling Ruby scripts の記事ですが、
記事の締め切りは2016年3月20日 (日) の予定となっております。 :memo: 

Markdown記法(またはHiki記法)にてこちらのissueに記載いただくか、
`yuta.kurotaki@gmail.com` まで原稿を送っていただいてもよろしいでしょうか？

作成していただいた原稿を元に
http://magazine.rubyist.net/?0053-CompilingRubyscripts
↑ に新規ページを作る予定です。よろしくお願いします!

**Comment by ko1** [comment]
YARV maniacs の新しいやつにしようと思います（まだ書いてない）。
ページ作成までやりますんで、アップロード後、見て下さい。

**Comment by kurotaky** [comment]
承知しました、よろしくお願いします :smile:

**Comment by kurotaky** [comment]
@ko1 
おつかれさまです、記事の締め切りが2016年3月20日 (日) でした : )
アップロード完了していたら、こちらのissueにてお知らせいただけると嬉しいです。
以下に編集担当用のToDoリストを記載しておきます! :memo: 

## 編集担当者ToDoリスト
- [x] 担当を決める
- [x] 作者から概要をもらう
- [ ] 作者から目次アウトラインをもらう
- [ ] 作者から記事をもらう
- [ ] もらった記事を編集Wikiに転載する
- [ ] 編集Wikiの記事を校正する
- [ ] 編集した記事を作者に確認してもらう
- [ ] 編集MLに作者からの確認が完了した旨を伝える
- [ ] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [ ] 作者にお礼を伝える

**Comment by miyohide** [comment]
@ko1 @kurotaky ひとつご提案なのですが、次々号（54号）の記事のストックが無いため、この記事は次々号（54号）にまわしませんか？

**Comment by ko1** [comment]
54号っていつごろでしたっけ。
久々に書いたら、なんかすぐ長くなっちゃって、半分くらい...。

**Comment by ko1** [comment]
遅くなりましたが、とりあえず書き上げました。
絵をスライドから引っ張って来れれば良かったんですが、アップデートが面倒で...。

http://magazine.rubyist.net/?0053-YARVManiacs

**Comment by ko1** [comment]
ちなみに、54号は、時期にもよりますが、
東京11のスピーカーに書いて貰えないかなぁ。

**Comment by miyohide** [comment]
54号は、8月ぐらいかなと考えています。

**Comment by miyohide** [comment]
@ko1 記事執筆ありがとうございます。では、53号掲載で行きたいと思います。
authキーワードが抜けていたので、設定しました。あしからず。

**Comment by kurotaky** [comment]
@ko1 
記事確認しました、ありがとうございます！

**Comment by miyohide** [comment]
@ko1 遅くなりましたが、ちょっと気になる点があります。ご確認いただけますでしょうか。

- 以下のカッコ書きの部分は、脚注に移したいと考えています。
  - アセンブラ言語で書かれたプログラムを機械語に変換する作業も、...
  - たぶん、Java 仮想マシンの高速化技術、という文脈で、...
  - その他の文脈としては、ソースコードを読まれたくないので難読化とか
  - 取得の方法には、いろいろあります。この話、どっかでまとめてたっけ？
  - まったく同じというわけではないところが面倒くさいのですが

- 次のところの日本語を確認いただけますでしょうか（→の部分は訂正案）。
  - `これを、to_a した結果を Marshal.dump した結果をロードするのを比べてみると`
    - → `これと、to_aした結果にMarshal.dumpを行い、その結果をロードしたものと比べると`
  - `ヘッダには、どの情報がどこに入っている`
    - → `ヘッダ部には、どの情報がどこに入っている`
  - `オブジェクト部には、ID と同じように`
    - → `オブジェクト部には、ID 部と同じように`
  - `なので、バイナリのサイズは、一般的には遅いです。`
    - → `なので、バイナリのサイズは、一般的には大きいです。`
  - `ファイル名をキーにして、そのファイル名に相当するものを、 ファイル以外でも、変換してでも、読めば良い`
    - → `ファイル名をキーにして、そのファイル名に相当するもの（ファイルだけにかぎらず、ファイル以外の変換された結果）を読めば良い`
  - `さて、インターフェースは適用しましたので`
    - → `さて、インターフェースは用意しましたので`

**Comment by ko1** [comment]
どもども。

基本的に、脚注は見づらいので、このままにさせて下さい。

修正は仰るとおりかと思います。

**Comment by miyohide** [comment]
@ko1 了解しました。脚注化はやめ、修正は取り込みました。

**Comment by znz** [comment]
「アセンブラ言語」→「アセンブリ言語」でしょうか?

その他の以下の気になった点は自明だろうと思って既に変更しています。

- Ruby の[-命令列へ-]{+命令列への+}コンパイラを作ったよ
- 「Marshal.dump(iseq.to_a)」→「Marshal.dump(iseq.to_a, f)」
- 「直したみました」→「直してみました」
- 「その結果をロードものは」→「その結果をロードするものは」

**Comment by kurotaky** [comment]
@ko1 
修正後の記事の内容確認しました。執筆おつかれさまでした。
http://magazine.rubyist.net/?0053-YarvManiacs の内容で、
本日4/3(日)の夜(18:00すぎくらい)に公開します！

**Comment by kurotaky** [comment]
@ko1 
先ほどRubyist Magazine 0053 号がリリースされました。寄稿ありがとうございました。
http://magazine.rubyist.net/?0053
今後ともRubyist Magazine るびまをご愛読、また寄稿をお待ちしております。

**Comment by ko1** [comment]
@znz san ありがとうございます！（すみません、遅れました）
