### ISSUE TITLE
Rubyist Hotlinks 須藤 功平さん

### ISSUE THREAD

**Issue by gunjisatoshi** [rubima/rubima#384]
まだ何も決まっていないとは思いますが、 とりあえず issue にしておきます。
@shyouhei さん、 @kou さん、よろしくお願いします！

- [x] インタビュー日時・場所を決める
- [x] インタビュー協力者を募集する
- [x] 事前にインタビュー項目をお伝えする
- [x] インタビューを実施する
- [x] 担当を決める
- [x] 掲載号を決める
- [x] テープ起こしをする
- [x] 編集Wikiに記事ページを作る
- [x] 編集Wikiの記事を編集する
- [x] 編集した記事をインタビュイーに確認してもらう
- [x] 編集MLにインタビュイーの確認が完了した旨を伝える
- [x] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [x] インタビュイーにお礼のメールを出す

参考：前回の島田さんインタビューの時のやり取り https://github.com/rubima/rubima/issues/322

**Comment by kou** [comment]
よろしくお願いします！

場所はよほどのことがない限りクリアコード、ということで決まっています。
日時は年が明けてから相談させてください＞＜
（1月・2月は無理そうです。）

**Comment by shyouhei** [comment]
日程相談していきましょうー

**Comment by kou** [comment]
2月9日に[主催イベント](https://groonga.doorkeeper.jp/events/35295)があってバタバタなのでその後からでもいいですか！？
今のところ、やじうま（というか私の外部記憶）として角谷さんと咳さんと角さん（と、もしかしたら島田さん）を誘いたいなぁと思っています。

**Comment by snoozer05** [comment]
参加したいです！

**Comment by kou** [comment]
@snoozer05 2/19（金）の10:00に目黒にお越しください！

**Comment by shyouhei** [comment]
実施済みです。インタビューは卜部というか角さんにやってもらいました。
手元に音声とか写真があります。大場さんも写真を撮ってくれていました。あと角さんが30分くらいテープ起こしてくれてます。
という状況です。

**Comment by kdmsnr** [comment]
原稿を置くリポジトリがあったりしますか？

**Comment by miyohide** [comment]
@kdmsnr るびま編集部の miyohide です。返答遅くなりましてすみません。

> 原稿を置くリポジトリがあったりしますか？
プライベートリポジトリはありません。るびまに未公開ページを作成することはできますので、そこに原稿を置く形をとっています。
未公開ページへのアクセスにはるびま用アカウントが必要となります。必要な場合、発行いたしますので、miyohide @ gmail.com までご連絡いただけますでしょうか。アカウント発行後、アカウント名・パスワードを返送いたします。

**Comment by zunda** [comment]
@miyohide @kou @knsmr 他にいらっしゃらなければ担当編集やりまーす (容量足りなくてidobata消しちゃったのなんとかしなくちゃ)

**Comment by kou** [comment]
（kdmsnrです。。。！）

**Comment by zunda** [comment]
あわわわわ失礼しました！

**Comment by zunda** [comment]
@kdmsnr @kou http://magazine.rubyist.net/?0053-Hotlinks を作りました。アカウントが届いたらみてみていただけますか？

@gunjisatoshi @miyohide 先走ってすみません。みなさんに勢いがあるうちにと思ってページの作成までやりました。問題などあればお知らせください

**Comment by gunjisatoshi** [comment]
@zunda 問題ないとおもいます！　よろしくお願いします :bow:

**Comment by miyohide** [comment]
@zunda 担当引き受けていただきありがとうございます。よろしくお願いします。アカウントは作成してご連絡済みです。

**Comment by zunda** [comment]
kdmsnr さんに文字起こしを転記していただきました!ありがとうございます。あとはこちらでぼちぼち編集していきます。気づいたことがあったらどんどん編集しちゃってください。

**Comment by zunda** [comment]
るびま用に空白などを編集しています「(……きこえますか…きこえますか…Groonga…は？)」の前まで触りました

**Comment by kdmsnr** [comment]
おっと。「卜部 256倍とかも？」あたりまで、リンク追加するついでに（雑に）空白処理もしてました。

**Comment by zunda** [comment]
あ、二度手間すみません! それではとりあえず3月7日くらいまでは触らないようにしておきます

**Comment by kdmsnr** [comment]
画像の追加と、リンクの追加を終わりました。とりあえず私の作業は以上です。★のところは発言者に聞かないとかも（どうしよう）。

**Comment by kou** [comment]
@miyohide 私のアカウントも作ってもらえないでしょうか？「Thu, 03 Mar 2016 08:55:01 +0900 (JST)」にmiyohide @ gmail.comにメールを送っています。

**Comment by miyohide** [comment]
@kou 遅くなってすみません。先ほど作成してメール返信しました。

**Comment by kou** [comment]
@miyohide ありがとうございます。おかげで原稿はできあがりました。あとは @zunda さんが仕上げてくれれば閑静です。

**Comment by zunda** [comment]
原稿の調整だいたい終わりました。@kdmsnr さんのテキストむちゃくちゃ編集しやすかったです。ありがとうございます!!1 お時間のあるときにいまいちど @kou さんに内容を確認していただけるとうれしいです。よろしくお願いします http://magazine.rubyist.net/?0053-Hotlinks

**Comment by kou** [comment]
確認しました！カンペキです！

**Comment by kdmsnr** [comment]
:metal:

**Comment by zunda** [comment]
進捗状況の更新ありがとうございます。表紙を編集しようとおもったらまだ無いのかな？目次は下記のような感じに考えています

> Rubyist Hotlinks 【第 36 回】 須藤功平さん
>
> Rubyist へのインタビュー企画。今回は須藤功平さんにお話を伺いました。(難易度：みんな丸くなって)

**Comment by zunda** [comment]
[IceweaselからFirefoxへの改名](https://glandium.org/blog/?p=3622)の件を脚注に追加しました

**Comment by miyohide** [comment]
@zunda 表紙作成しました。リンク・目次を反映させています。
http://magazine.rubyist.net/?0053

**Comment by zunda** [comment]
ありがとうございます!! 時間のできた時に校正を続けますが、この記事としてはリリースできるようになったと思います。

**Comment by kurotaky** [comment]
@kou @shyouhei @snoozer05 
cc/ @zunda @gunjisatoshi @kdmsnr @miyohide 

インタビュー＆記事の執筆おつかれさまでした！
本日4/3(日)の夜(18:00すぎくらい)に公開予定です。よろしくお願いします。
http://magazine.rubyist.net/?0053-Hotlinks

**Comment by miyohide** [comment]
@kou @shyouhei @kdmsnr @snoozer05 インタビュー＆記事の執筆お疲れ様でした。
@zunda 編集作業お疲れ様でした。助かりました。
無事、リリース出来ましたので、本件Closeします。

**Comment by zunda** [comment]
皆様ありがとうございました!
