### ISSUE TITLE
0053号のリリース時期を決める

### ISSUE THREAD

**Issue by kurotaky** [rubima/rubima#386]
0053号のリリース時期の案です。

* 記事申し込み・概要締め切り: 2016年2月28日 (日)
* 記事の目次、アウトライン締め切り: 2016年3月6日 (日)
* 記事の締め切り: 2016年3月20日 (日)
* 校正完了、リリース: 2016年4月3日 (日)

過去のissueを参考にして、こんな感じで進めていこうと思います。

**Comment by miyohide** [comment]
@kurotaky リリーススケジュールの立案ありがとうございます。

記事の締め切りが1週間ほど後でもよいかなと思います。3/20（日）ぐらい。
著者さんに少し余裕を持たせたいという思いから、上記のように考えました。

**Comment by kurotaky** [comment]
@miyohide 
おおーたしかに、見直してみると、
アウトライン締め切りから記事の締め切りまでの間が1週間だと短い気がしました。
ということで、3/20(日) に変更しました!

**Comment by miyohide** [comment]
了解です。良さそうなスケジュールかと思います。

**Comment by miyohide** [comment]
記事締切日なので、記事候補を上げてみます。

- #365 （Tokyu Ruby会議レポート） 記事アップ済み。レビュー済み、確認依頼中
- #373 （大江戸Ruby会議レポート） まだ記事を受け取っていない状況。ちょっと微妙
- #382 （TRICK 2015解説記事）記事アップ済み。レビュー中。
- #383 （Compiling Ruby Script）担当者未設定。まだ記事を受け取っていない状況

あとはプレゼント企画があります。

フォローアップしてみて、様子を見てみようかと思っています。

**Comment by kurotaky** [comment]
おお、ありがとうございます :smile:

**Comment by gunjisatoshi** [comment]
#383 って @kurotaky さんが担当のように見えるのですが https://github.com/rubima/rubima/issues/383#issuecomment-183640143 進行役と同時で厳しいようであれば引き取りますのでご連絡ください :bow:

**Comment by kurotaky** [comment]
Compiling Ruby Script に関しては僕が担当する予定でした :bow: 
記事の目次、アウトライン締め切りに向けて[こちらにコメント](https://github.com/rubima/rubima/issues/383#issuecomment-190514144)しました！

**Comment by miyohide** [comment]
Hotlinks も掲載候補になりそうです。 #384

**Comment by kurotaky** [comment]
Hotlinksの件、承知しました :ok_woman:

**Comment by miyohide** [comment]
#365 （Tokyu Ruby会議レポート） 記事校正完了です。
#384 （Hotlinks）も校正完了のようです。

**Comment by miyohide** [comment]
リリース1週間前ですので、記事候補と状況の確認です。
【まだ】
- 巻頭言 （ #391 ）
- 大江戸 Ruby 会議レポート （ #373 ）← 最終確認中
- アクセスランキング（ #388 ）
- 編集後記 （ #393 ）

【完了】
- Hotlinks （ #384 ）
- Compiling Ruby scripts （ #383 ）
- Tokyu Ruby 会議レポート （ #365 ）
- 読者プレゼント （ #381 ）

**Comment by SugHimsi** [comment]
いま記事自体が無いのはアクセスランキングだけ?

**Comment by kurotaky** [comment]
アクセスランキング作成して、0053号の記事候補と状況の確認をしました。
http://magazine.rubyist.net/?0053

【完了】
- 巻頭言 （ #391 ）
- 大江戸 Ruby 会議レポート （ #373 ）
- アクセスランキング（ #388 ）
- Rubyist Hotlinks 【第 36 回】（ #384 ）
- YARV Maniacs 【第 13 回】（ #383 ）
- Tokyu Ruby 会議レポート （ #365 ）
- 読者プレゼント （ #381 ）
- 編集後記 （ #393 ）
 - 現状3人、他にも編集してくれた人に書いてもらう

**Comment by kurotaky** [comment]
0053号のリリースは 2016年4月3日 (日) 18:00ごろを予定しています。
リリース時期が決まったのでclose!

**Comment by kurotaky** [comment]
【完了】に追加
* TRICK2015 開催報告＆入賞作品紹介 #382
 * http://magazine.rubyist.net/?0053-TRICK2015
