### ISSUE TITLE
るびまのバックエンド(インフラ)を今のメンバーに展開していく

### ISSUE THREAD

**Issue by hsbt** [rubima/rubima#387]
@hsbt と @gunjisatoshi しか触れないるびまのバックエンド(hiki + sqale)を他の編集者でも触れるようにしていく。

具体的には @miyohide が何かいじれるようにドキュメントや運用スクリプトを用意するって感じかな。

**Comment by gunjisatoshi** [comment]
さぼっててすみません :bow:

そういえばご連絡遅くなりましたが、るびまの sqale のアカウント情報を @miyohide さんに共有したことをお伝えしておきます。なので現状でるびまの sqale のアカウント情報を知っている (はず) なのは、

* @takahashim  さん
* @kakutani さん
* @ko1 さん
* @snoozer05 さん
* @hsbt さん
* @sunaot さん
* @takkanm さん
* @miyohide さん

になります。秘密情報の管理は悩ましいですね‥‥。

**Comment by znz** [comment]
私も知ってます。

**Comment by gunjisatoshi** [comment]
@znz 了解です :+1:
