### ISSUE TITLE
0053 号リリース

### ISSUE THREAD

**Issue by kurotaky** [rubima/rubima#389]
- [x] るびま編集コミュニティ全員に 0053 号全体のプルーフリーディングのお願いをする
- [x] るびま編集コミュニティ全員に編集後記の記載を促す
- [x] リリースの時刻を決める → 4/3(日) 18:00 ごろリリース予定とします。
- [x] 各記事の担当者に担当記事がリリースできる状態になっているか確認する
- [x] リリースできないと判断した記事があれば、表紙から落とす
- [x] 旧編集Wikiでリハーサルする (SideMenuとか目次ページとかの表示を確認する)
- [x] リリース時刻にリリース作業をする (各記事のauthを外し、各号目次、分野別目次、SideMenu および表紙を更新する)
- [x] 「ログアウトした状態ですべての記事が正常に見られること」の確認
- [x] RSSの更新をする
- [x] リリースした旨を日本Rubyの会 ML と ruby-list に告知する
- [x] https://github.com/ruby-no-kai/official/wiki を更新する
- [x] 日本Rubyの会のトップページに掲載するために、https://github.com/ruby/www.ruby-lang.org への pull request をする
- [x] 各記事の担当者に担当記事の著者へのお礼をするよう促す

参考: https://github.com/rubima/rubima/issues/378 [るびまリリース手順](https://github.com/rubima/rubima/wiki/ReleaseProtocol)

**Comment by miyohide** [comment]
@kurotaky リリース作業、お手伝いできます。RSSの更新やruby-no-kaiのwiki更新などをお手伝いしようかと思っています。リリースの予定時刻を教えて頂けますと助かります。

**Comment by kurotaky** [comment]
@miyohide 
ありがとうございます、本日 4/3(日)18:00ごろを予定しております！

**Comment by miyohide** [comment]
@kurotaky 無事リリース出来ました。お疲れ様でした。
