### ISSUE TITLE
0053 号の表紙をつくる

### ISSUE THREAD

**Issue by kurotaky** [rubima/rubima#390]
http://magazine.rubyist.net/?0053

**Comment by kurotaky** [comment]
表紙: http://magazine.rubyist.net/?0053

アクセスランキングは4/1, 4/2に集計してリンクを載せる :memo:

**Comment by SugHimsi** [comment]
今回の内容を踏まえると、この号の巻頭言は難易度を変えたいなあ。

**Comment by kurotaky** [comment]
表紙の一番下にあった、以下の部分を削除しました。
```
----
[[0053-YARVManiacs]]
```

**Comment by kurotaky** [comment]
現在、巻頭言の難易度は `Ruby を始めるときはまずはここから` に変更済。

**Comment by kurotaky** [comment]
「TRICK2015 開催報告＆入賞作品紹介」を表紙に追加。
http://magazine.rubyist.net/?0053-TRICK2015

**Comment by miyohide** [comment]
無事リリース出来ました。対応ありがとうございました。
