### ISSUE TITLE
0053号 巻頭言 

### ISSUE THREAD

**Issue by kurotaky** [rubima/rubima#391]
@takahashim 
こんにちは、るびま編集のくろたきです。
0053号のリリースは2016年4月3日 (日)を予定しております。

リリースの1 週間前の2016年3月27日(日) ごろまでに
巻頭言の原稿をいただけると助かります。よろしくお願いします！

**Comment by takahashim** [comment]
うう、頑張ります！

**Comment by miyohide** [comment]
@takahashim るびま編集のみよひでです。本件、執筆状況いかがでしょうか。

**Comment by kurotaky** [comment]
@takahashim 
0053号のリリースは2016年4月3日 (日)を予定しております。
3/31(木)ごろまでに原稿いただけると嬉しいです。巻頭言よろしくお願いいたします！

**Comment by takahashim** [comment]
すみません、例によって遅れておりますが、今月中にはできる予定です…

**Comment by SugHimsi** [comment]
雑感、その通りですね。
弊社、じゃ、分かる人にしか分からない。

**Comment by miyohide** [comment]
@takahashim 巻頭言、ありがとうございます。英字の前後に空白を入れる処理の対応を行いました。

**Comment by SugHimsi** [comment]
難易度、単なる「高」よりはずっと良くなったと思いました。
もっといい案がありそうな気もしますので、他の方の意見も聞きたいな。

**Comment by kurotaky** [comment]
@takahashim 
巻頭言ありがとうございます！以下の箇所を修正しております。

`いった文書でも` → `といった文章でも`
```diff
-「Ruby 基礎文法最速マスター」(http://route477.net/d/?date=20100125 ) いった文書でも十分に役には立つ。
+「Ruby 基礎文法最速マスター」(http://route477.net/d/?date=20100125 ) といった文書でも十分に役には立つ。	
```

`興味があれば そちらも` の中にあるスペースを削除。
```diff
- 動画を有償で公開している( http://railstutorial.jp/screencasts )ので、興味があれば そちらも参考にしていただきたい。
+ 動画を有償で公開している( http://railstutorial.jp/screencasts )ので、興味があればそちらも参考にしていただきたい。
```

**Comment by takahashim** [comment]
@kurotaky 修正ありがとうございます！
