### ISSUE TITLE
るびまを動かしているサーバ（Sqale）の更新手続き

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#392]
るびまを動かしているサーバ（Sqale）の契約が今月末（2016年3月末）で終了します。
（参考: #331）

@takahashim 問題なければ、継続でお願いしたいのですが、いかがでしょうか。

**Comment by takahashim** [comment]
@miyohide はい、継続で対応します！

**Comment by miyohide** [comment]
@takahashim お手数おかけします。よろしくお願いします。

**Comment by shyouhei** [comment]
@miyohide 振り込み済みとのことですが契約の延長が確認できたりしますか

**Comment by miyohide** [comment]
@shyouhei Sqaleの会員ページからは確認できませんでしたので、担当者さんに連絡してみます。

**Comment by miyohide** [comment]
@shyouhei @takahashim 本日、担当者さんから契約更新した旨の連絡をいただきました。本件、これでCloseとします。

**Comment by takahashim** [comment]
どうもありがとうございました！
