### ISSUE TITLE
日本Rubyの会 MLへのメール投稿が失敗するので、状況を確認する

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#394]
るびま 0053 号のリリースを案内するために日本Rubyの会ML（ ruby@ml.fdiary.net ）にメールを送信したのだが、以下のようにエラーメールが返ってきてしまう。

> This is the mail system at host fdiary.net.
> 
> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
> 
> For further assistance, please send mail to postmaster.
> 
> If you do so, please include this problem report. You can
> delete your own text from the attached returned message.

状況を確認する。

@takahashim 何かご存じですか？

**Comment by takahashim** [comment]
@miyohide む、ちょっと分かりませんが前にも似たようなことがあったかも…（うろおぼえ）

**Comment by hsbt** [comment]
kazuhiko さん管理のサーバーですね、本人に聞くのがいいかも?

**Comment by gunjisatoshi** [comment]
@fdiary というわけで、日本 Ruby の会 ML が動いていないように見えるのですが http://ruby-no-kai.org/mailinglist.html 状況ご確認いただけますでしょうか。メールアーカイブ http://www.fdiary.net/ml/ruby/ のほうも 500 Internal Server Error になるみたいです。

**Comment by fdiary** [comment]
2月にサーバを引っ越した時に、quickml関係を確認するのを忘れていました。
なおったはずですので、再送してくださいますか？ > @miyohide

**Comment by miyohide** [comment]
再送してみました。届いているっぽい？！

**Comment by gunjisatoshi** [comment]
@miyohide [ruby:2693] で届いていることを確認しました！

ありがとうございました！＞ @fdiary

**Comment by kurotaky** [comment]
ありがとうございました :smile:

**Comment by miyohide** [comment]
みなさま、対応ありがとうございました。
対応完了しましたので、Closeします。
