### ISSUE TITLE
るびま 0053 号の読者プレゼントの抽選をして結果をご連絡する

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#395]
るびま 0053 号の読者プレゼントを4月末で締めて、5月連休明けには担当者様にご連絡する。 （参考： #381 ）

**Comment by miyohide** [comment]
当選者を決定して、ご連絡済みです。

確認が取れたら、ページを更新してCloseします。

**Comment by miyohide** [comment]
本件、作業完了しましたのでCloseします。

**Comment by kurotaky** [comment]
ありがとうございます!
