### ISSUE TITLE
東京 Ruby 会議 11 レポート

### ISSUE THREAD

**Issue by zunda** [rubima/rubima#396]
やります

2016年5月28日 秋葉原コンベンションホール
http://regional.rubykaigi.org/tokyo11/

# 当日まで
- [x] レポート担当者を集める
  - @zunda
  - @tsuda7
  - @youhei19880130
- [x] 担当する[講演](http://regional.rubykaigi.org/tokyo11/schedule/)を決める
  - 開会の挨拶: @zunda
  - Streem - まつもとゆきひろさん: @youhei19880130
  - mruby/c - 田中 和明さん: @tsuda7
  - Rubyに型があると便利か - 栗原 勇樹さん: @zunda
  - (ランチ)
  - 最速ウェブサーバの作り方 - 奥一穂さん: @youhei19880130
  - アプリケーションへのRubyインタープリターの組み込み - 須藤功平さん: @zunda
  - Re: Pattern Matching in Ruby - 辻本 和樹さん: @tsuda7 
  - (休憩)
  - Image Recognition and Code that shouldn't exist - Aaron Pattersonさん: @zunda
  - IMF: Image Manipulation Framework - 村田 賢太さん: @youhei19880130
  - Optcarrot: A pure-ruby NES emulator - 遠藤侑介さん: @tsuda7 
  - (休憩)
  - 分散ワークフローエンジン『Digdag』の実装 - 古橋 貞之さん: @tsuda7
  - 閉会の挨拶: @zunda
- [X] メモを書く場所を決める
  - それぞれ手元に書けばいいか

- 事前情報→ #398

# 当日
- メモを書く
- 写真を撮る
- 発表資料のURLを集める

# 開催後
- [x] 目次をつくる - 下記のような感じでいかがでしょうか？講演の休憩だったところに講演以外の記事を挟む感じで並べてみました。講演以外の記事のまとめ方はボリュームもみて考えていければいいと思います
  - イントロダクション、開会前の様子、開会の挨拶
  - Streem - まつもとゆきひろさん
  - mruby/c - 田中 和明さん
  - Rubyに型があると便利か - 栗原 勇樹さん
  - 最速ウェブサーバの作り方 - 奥一穂さん
  - アプリケーションへのRubyインタープリターの組み込み - 須藤功平さん
  - Re: Pattern Matching in Ruby - 辻本 和樹さん
  - ポスター、書籍展示
  - Image Recognition and Code that shouldn't exist - Aaron Pattersonさん
  - IMF: Image Manipulation Framework - 村田 賢太さん
  - Optcarrot: A pure-ruby NES emulator - 遠藤侑介さん
  - OSS Gateについて
  - 分散ワークフローエンジン『Digdag』の実装 - 古橋 貞之さん
  - 閉会の挨拶、まとめ
- 写真を集める
  - `[tokyo11:693]`を参照のこと
- [x] るびま編集アカウントを発行する
- [x] 原稿を書く
- [x] 講演者に確認を依頼する
- [ ] 校正する

**Comment by ko1** [comment]
やってもイイヨ、という方、こちらにコメントください。

**Comment by tsuda7** [comment]
もしよければお手伝いさせてください！

**Comment by youhei19880130** [comment]
お手伝いさせてください！

**Comment by zunda** [comment]
ありがとうございます!! 頼もしい :fist:

人数が揃えば、担当する講演を決めておいて手分けしてレポートを書くのが良さそうです。5月8日くらいまで募集を続けて担当する講演を決めようかと思います。いかがでしょうか？どうやって担当する講演を決めるのがいいかな…

講演以外にも会場の様子とか休憩の様子とか折り込めると良さそうです。こちらは気づいたことをメモしておいて記事にまとめていく段階で混ぜれば良いかと思っています。

**Comment by ko1** [comment]
@zunda あとは委細、zunda さんにお任せしてしまってよろしいでしょうか。
話者へのインタビューは、来週帰国してからやるだけやろうかと（記事が出せるかはともかく）。

**Comment by zunda** [comment]
開催日後のレポートおまかせください!!

話者へのインタビュー、せっかくやるなら事前情報としてどこかに出したいですよねぇ。うーん…

**Comment by zunda** [comment]
@tsuda7 @youhei19880130 レポートのお手伝いの申し出をありがとうございます!! 担当する講演を決めておいて手分けしてレポートを書く感じで良いでしょうか？この講演は自分が担当したい!という講演があればこちらにお知らせいただけますか？このIssueの最初に講演のリストがあるので講演者名をお知らせいただけるとうれしいです。まずいただいたご希望に沿って担当を決めて、残りは担当する講演が続かないようにこちらで振り分けようかと思います。他にこうした方が良さそう、というコメントがあればそちらもよろしくです!!

**Comment by ko1** [comment]
事前記事にご協力頂けると、大変嬉しいです。

https://github.com/rubima/rubima/issues/398

**Comment by youhei19880130** [comment]
@zunda 
いくつか担当したい公演をリストアップしました。
よしなにしていただけると幸いです。
```
Streem - まつもとゆきひろさん
To Be Announced... - 奥一穂さん
Re: Pattern Matching in Ruby - 辻本 和樹さん
IMF: Image Manipulation Framework - 村田 賢太さん
Optcarrot: A pure-ruby NES emulator - 遠藤侑介さん
```

@ko1 
インタビュー原稿とはどれのことでしょうか？

**Comment by zunda** [comment]
@youhei19880130 ありがとうございます! @tsuda7 さんのご希望を待って今週末くらいに振り分けます。インタビュー原稿は #398 (るびま特別号) 関連かな？

**Comment by ko1** [comment]
@youhei19880130 #398 の件は、今スピーカー各位に確認してもらってるので、未公開です。お引き受け頂ける方に公開します。

**Comment by tsuda7** [comment]
@zunda お返事遅れました、現段階では特に希望ありません！

**Comment by zunda** [comment]
@tsuda7 @youhei19880130 ありがとうございます！上記にざっくり割り振りをしてみました。間違いや、やっぱりこっちを担当したいなどあればお気軽にお知らせください。

開催中は、特に希望がなければそれぞれが持参したマシンの中にそれぞれメモをためておいてもいいかとも思ってます。ネットワーク帯域が確実に確保できるなら、まとめてどこかに置くのもアリですよね。カメラや電話で会場の雰囲気を写真に残しておけると良さそうです。講演者のかっこいい写真もあるとうれしいですよね。

ご意見などありましたらよろしくお願いします。

**Comment by zunda** [comment]
講演者の方々への事前インタビューを順次公開してます。ご参考まで

http://magazine.rubyist.net/?preTokyoRubyKaigi11

**Comment by tsuda7** [comment]
お二人にレポートが偏ってしまっていますね、必要であれば担当変わりますのでお声がけください。

**Comment by ko1** [comment]
ちなみについでに、
今回は、ポスターを掲示する、
という企画をしているので、それについても触れて頂けると嬉しいです。

**Comment by zunda** [comment]
@tsuda7 さん、お申し出ありがとうございます。 @youhei19880130 さん、もしこの講演の担当は他の人に任せてもいい、というものがあればお知らせください。

ポスターや書籍の展示などについてもメモや写真を残しておいて記事にまとめましょう！目次のたたき台をこのIssueの最初に置いておきます。

**Comment by zunda** [comment]
@youhei19880130 さん、 @tsuda7 さん、原稿は最終的にはHikiフォーマットになってるびまのWikiページにまとめることになります。るびまを編集するアカウントを持っていない場合は、miyohide @ gmail.com さんまで依頼していただけますか？

@miyohide さん、東京Ruby会議11レポート担当のお二方のるびま編集アカウントをお願いするかもしれません。その場合はよろしくお願いします。

**Comment by youhei19880130** [comment]
@miyohideさん、アカウント発行お願いします。

**Comment by miyohide** [comment]
@youhei19880130 さん、アカウントを発行し、メールにてユーザ名・パスワードをお知らせしましたので、ご確認ください。

**Comment by youhei19880130** [comment]
miyohideさん

ありがとうございます。


2016年5月27日(金) 23:31 miyohide <notifications@github.com>:

**Comment by miyohide** [comment]
記事ページを作成しましたので、ご活用ください。
http://magazine.rubyist.net/?0054-TokyoRubyKaigi11Report

**Comment by youhei19880130** [comment]
@zunda 
一番前の席いってもいいんですか？

**Comment by tsuda7** [comment]
@youhei19880130 
はい、お待ちしてます！

**Comment by youhei19880130** [comment]
@tsuda7 
ありがとうございます。

**Comment by zunda** [comment]
るびま記事ページありがとうございます！編集するときは ?c=login を追加してログインしてからですね〜

**Comment by miyohide** [comment]
@tsuda7 さん、アカウントを発行しましたので、メールをご確認ください。

**Comment by zunda** [comment]
記事ページに担当の方を記入しました。間違えていたら訂正をお願いします

**Comment by tsuda7** [comment]
@zunda @youhei19880130 
1つ記事を更新しました、写真を加えることを考えると分量的にはこのくらいかな？と思っています（少し多いでしょうか？）。今週中には残り3つも上げてしまう予定です。

**Comment by zunda** [comment]
うおおおお！ありがとうございます。当方この週末までまだ手をつけられてません。来週こそは…？

さて、恥ずかしながら更新していただいた記事を閲覧することができませんでした。何らかの方法でURLをお知らせいただけますか？るびまのWikiの公開前の記事のURLならこちらに公開してしまっても問題なさそうです

**Comment by youhei19880130** [comment]
私は本日、一気に書き上げる予定なので、出来ましたら共有いたします。

2016年6月13日(月) 6:31 Daigo <3 Dango <notifications@github.com>:

**Comment by tsuda7** [comment]
@zunda 
腰をあげるのが大変ですよね、書き始めてしまえば意外と楽しいものですが… 
miyohide さんにページを作っていただいたので、そちらを更新しました（ログイン後、見れるかと思うのですが、いかがでしょう？）：
http://magazine.rubyist.net/?0054-TokyoRubyKaigi11Report

**Comment by tsuda7** [comment]
担当のものは執筆終わりました。写真もいれないとですね…
他の Ruby会議のフォーマットにならい、フッターに「書いた人」の欄を加えてみました。よろしければ一筆いかがでしょうか？

**Comment by zunda** [comment]
ありがとうございます！とりあえず楽しく読ませていただきました:P

「書いた人」欄いい感じですね。アルファベット順にソートしてみました。

僕の担当分はまずは雑記から書いてみました。それぞれのセクションの担当者の記載はあんまり目立たない方がいいかと思ってかっこ内に記してみました。これまでの書き方とどちらがいいかな？

**Comment by zunda** [comment]
担当分の記事をダンプしました。長い！すみません！なんとか短くします。

**Comment by tsuda7** [comment]
これで写真入るとすごいボリュームですね、、w

**Comment by tsuda7** [comment]
@youhei19880130 さん、もし手元にもう記事がありましたらアップお願いできますでしょうか？

**Comment by youhei19880130** [comment]
手元に記事あります！
昼間時間がなく、夜にあげます！

**Comment by youhei19880130** [comment]
@zunda @tsuda7 
作業遅れていて申し訳ないです。
本日中(明日の朝まで)には上げきります。
終わりましたら、再度こちらでアナウンスします。

**Comment by youhei19880130** [comment]
@zunda @tsuda7 
ご連絡遅くなりましたが、記事あげておりますので、ご確認お願いしますm(_ _)m

**Comment by tsuda7** [comment]
記事が揃いましたね、お疲れ様でした 👍 
あとは写真をつける感じでしょうか？

**Comment by youhei19880130** [comment]
そうですね！
オフィシャルな写真ってあるんでしたっけ？

**Comment by hsbt** [comment]
こんばんは

https://goo.gl/photos/6TZY9bBVfcZ8LzZx5

私が撮影したものがあるのでご利用ください。

**Comment by tsuda7** [comment]
体裁を整え、写真を貼付しました。

@hsbt さん、ありがとうございます！大変助かりました。記事末尾にお名前掲載せていただきました 🙇 

@zunda さん、須藤さんの写真お持ちでしょうか。担当が zunda さんでしたのでお持ちでしたらアップロードいただけると助かります。あと、Aaron さんの記事分量少し削ることは可能でしょうか…？（ここだけちょっと長過ぎるかと思っております）

**Comment by zunda** [comment]
編集ありがとうございます！須藤さんの写真と会場入り口の写真を追加しました。

**Comment by zunda** [comment]
そしてAaronさんの記事も少し削ってみました。分量、いかがでしょう？

**Comment by youhei19880130** [comment]
良いと思います。
写真入れると一気に見栄え良くなりましたね。
@tsuda7 さん、 @hsbt さんありがとうございます。

**Comment by tsuda7** [comment]
@zunda ありがとうございます！
各記事末尾の「執筆担当」は読む側としては冗長かなと思うのですが、いかがでしょうか？（ページ末尾にクレジットありますし…）

@zunda この後の流れはどうすればよいでしょうか？

**Comment by zunda** [comment]
ありがとうございます!

あとは、下記を並行して進めていく感じでしょうか。今ちょっと余裕がなくてすみませんが、

- るびまの締め切り確認
- 他の編集者にも依頼しつつ誤字脱字の修正
- 講演者に記事の確認を依頼、必要ならるびま編集アカウントを発行

個人的には写真の配置をもう少し工夫したい気もします

こちらで時間ができたらぼちぼち進めますが興味のある項目を進めていただいてもかまいません！

**Comment by miyohide** [comment]
@zunda さん、 @tsuda7 さん、 @youhei19880130 さん、こんにちは。記事の執筆ありがとうございます。

- るびまの締め切りですが、8/7（日）を考えています（リリースは8/21（日）、See. #402 ）。
- 誤字脱字の修正等は主担当 @miyohide で行います。
- 講演者用のるびま編集アカウントは共通アカウントを一つ発行します（おそらく週末を目処に）。それをどなたかにお知らせして（おそらく、 @ko1 さん？）、確認していただければ良いかなと思っています。

**Comment by znz** [comment]
差分を読んでいて気付いた

- 見えなくなってしまいまうからです → 見えなくなってしまうからです
- 発展発展 → 発展

という修正をしました。

`しなてはいけないので` というのも気になったのですが、`してはいけないので`なのか`しなくてはいけないので`なのかわからなかったのでそのままにしています。
修正をお願いします。

**Comment by zunda** [comment]
znzさんご指摘ありがとうございます。「する必要があるので」にしてみました。

**Comment by zunda** [comment]
講演者用のるびまアカウントは、それぞれの講演者に個別にメールでお知らせした方が良さそうですよね。こちらで知らせても良いですが、既に連絡先を知っていそうな @ko1 さんにお願いできるとうれしいです。アカウントの準備ができた時にこちらから講演者メーリングリストに原稿のURLとアカウントをお送りする旨アナウンスして、笹田さんから個別に認証情報を送っていただく感じで良いでしょうか？

**Comment by ko1** [comment]
共通アカウントをスピーカーMLに流せばよくない？

**Comment by zunda** [comment]
写真をもう一枚だけ追加して配置を少し変えました。僕的には満足。これじゃいかん、という部分があったらみなさま編集をお願いします。

それじゃあ、講演者向けの確認依頼は、みよひでさんがアカウントを用意してくださった後に僕からスピーカーMLに流すようにします。

**Comment by miyohide** [comment]
@zunda gmailアカウントにアカウント情報を送信しましたので、ご確認ください。
遅くなり申し訳ございません。

**Comment by zunda** [comment]
ありがとうございます!! 講演者の皆さんに確認を依頼しました。

**Comment by miyohide** [comment]
@zunda @tsuda7 @youhei19880130 他の記事など、0054号のリリースの目処がたちましたので、8/21（日）17:00ぐらいにリリースする予定です。修正等ありましたら、それまでにお願いします。

**Comment by miyohide** [comment]
@zunda @tsuda7 @youhei19880130 遅くなりましたが、るびま0054号をリリース出来ました。開催レポートの寄稿、ありがとうございました。

**Comment by zunda** [comment]
@miyohide さん、みなさん、いつもありがとうございます！編集後記書かなきゃ！
