### ISSUE TITLE
tDiary 15th anniversary party レポート

### ISSUE THREAD

**Issue by hsbt** [rubima/rubima#397]
http://eventdots.jp/event/580813 の開催レポートの寄稿を @takkanm から誘われたので、 @machu がメイン、 @hsbt がサブで寄稿しようと思います。

**Comment by machu** [comment]
遅くなりましたがちゃんと書いています。どこにアップすればいいですかねぇ。

1. (アカウント作ってもらえるなら)直接Hiki上にアップロード
2. このGitHubのWikiページ
3. Herokuあたりにサーバ立ち上げてアップロード

簡単そうなので1を希望しますが、ダメなら3を用意します〜。

**Comment by miyohide** [comment]
@machu るびま編集部の @miyohide と申します。寄稿、ありがとうございます。

アカウントを発行いたしますので、お手数ですが、
miyohide ＠ gmail dot com　（dotは.に変換してください）
までメールを送信いただけますか？

折り返し、ユーザIDとパスワード、Hikiのアップロード先をご連絡いたします。
（作業の都合上、本日の夜11時以降の対応となりそうです。ご了承ください。）

**Comment by miyohide** [comment]
本件、 @machu さんにアカウントを発行済みです。
また、記事ページを以下に用意しました。
http://magazine.rubyist.net/?0054-tDiary15thAnniversary
よろしくお願いします。

**Comment by miyohide** [comment]
@machu こんにちは。次回のるびまのリリースを8/21（日）、記事締め切りを8/7（日）と考えております。上記URLを拝見しますと、ほぼ記事ができているように見受けられるのですが、進捗いかがでしょうか。
See. #402

**Comment by miyohide** [comment]
@machu @hsbt こんにちは。次回のるびまの記事締めきりが明日に迫っているのですが、記事の進捗はいかがでしょうか。
上記URLを拝見しますと、ほぼ記事ができているように見受けられますが、どのような状況かご連絡を頂けますと助かります。

**Comment by hsbt** [comment]
@miyohide 僕の方で内容を見て、加筆修正あれば追記します!

**Comment by hsbt** [comment]
@miyohide 写真を埋めたり、文章が足りてないところを埋めましたー。ギリギリまで加筆修正はするかもしれませんが、現時点のもので発行していただいてかまいません。

**Comment by miyohide** [comment]
@hsbt 対応ありがとうございます。助かります。
なお、るびまのリリースは8月21日（日）を予定しております。

**Comment by machu** [comment]
対応できておらずすみません。書きかけだったところを追記しました。

**Comment by miyohide** [comment]
@machu @hsbt 他の記事など、0054号のリリースの目処がたちましたので、8/21（日）17:00ぐらいにリリースする予定です。修正等ありましたら、それまでにお願いします。

**Comment by miyohide** [comment]
@machu @hsbt 遅くなりましたが、るびま0054号をリリース出来ました。記事の寄稿、ありがとうございます。
