### ISSUE TITLE
東京 Ruby 会議 11 特別号

### ISSUE THREAD

**Issue by ko1** [rubima/rubima#398]
特別号誰か手伝ってもらえると助かります。
発表内容を事前にお伝えできればと思っています。

**Comment by ko1** [comment]
手伝って下さる方は、すでに3件インタビュー原稿があるんで、見て貰えると。

**Comment by ko1** [comment]
あと、代わりにインタビューして下さっても勿論可能です。

**Comment by zunda** [comment]
5月14日の週末に原稿を見る時間をつくれるとうれしい!

**Comment by zunda** [comment]
週末に半日くらいは時間ありそうです！るびまのWIkiから原稿を見るのがいいでしょうか？

**Comment by zunda** [comment]
ささださんとのチャットのまとめ

- ページ自体は http://regional.rubykaigi.org/tokyo11/ 以下にアップロードする
- 講演者それぞれのインタビューを1ページにまとめて、原稿はGitHubに置く
- それぞれのページが公開できるようになったら順次
  - http://regional.rubykaigi.org/tokyo11/schedule/ からリンクする
  - るびまの特別号のページからリンクする

**Comment by zunda** [comment]
順次公開状態となりました http://magazine.rubyist.net/?preTokyoRubyKaigi11 編集のみなさまお時間があればタイポ等の修正おねがいします

**Comment by miyohide** [comment]
左端のサイドメニューにリンクを追加しました。

**Comment by miyohide** [comment]
RSSの更新も終わりました。
http://magazine.rubyist.net/atom.xml

残念なことにこのRSSの更新は手作業となります。記事の追加がありましたら対応しますので、ご連絡（このIssueとかidobataとか）頂けますと助かります。

**Comment by zunda** [comment]
ありがとうございます！先ほど須藤さんへのインタビューを公開しました。あと発効日を間違えていたのを修正しました。あと何時間かでもう一件公開予定です。

**Comment by zunda** [comment]
田中先生へのインタビューを公開しました。現状ではこれでしばらく休憩です

**Comment by miyohide** [comment]
インタビュー追加ありがとうございます。後ほどRSSの更新を行います（おそらく深夜になるかと。すみません...）

**Comment by miyohide** [comment]
RSS更新終了しました。

**Comment by zunda** [comment]
ありがとうございます！こちらでも更新作業できそうでしたら手順を教えていただけますか？

**Comment by zunda** [comment]
栗原さん、奥さん、まつもとさんへのインタビューを公開しました

**Comment by asonas** [comment]
インタビュー記事楽しませて頂いてます。
ksssさんのインタビュー記事で誤字脱字を見つけたのですが、どこに報告していいのかわからなかったのでとりあえずここに報告します。

``` diff
-笹田 型を指定するのと、メソッド呼び出しで書ける、というのは別々の話いですよね？
+笹田 型を指定するのと、メソッド呼び出しで書ける、というのは別々の話ですよね？
```
http://regional.rubykaigi.org/tokyo11/interview/ksss/

**Comment by ko1** [comment]
ありがとうございます。
修正しました。

ちなみに、 https://github.com/ko1/tokyo11 に気づいた点を頂けると助かります。

**Comment by asonas** [comment]
修正ありがとうございます！

**Comment by miyohide** [comment]
RSS更新、追いつきました。

RSSは、https://github.com/rubima/hiki の public/atom.xml を手で修正後、るびまを動かしているSqaleにgit pushしています。
例えば、public/atom.xmlに対するPull Requestだけでもありがたいです。

**Comment by zunda** [comment]
ありがとうございます！遠藤さんと古橋さんへのインタビュー記事を追加したのでPRしてみました。お手数ですがお時間のある時によろしくお願いします

https://github.com/rubima/hiki/pull/23

**Comment by miyohide** [comment]
Pull Requestありがとうございます。RSS更新済みです。

**Comment by zunda** [comment]
ありがとうございました！すべてのインタビュー記事を公開しましたので、 https://github.com/rubima/hiki/pull/24 が今号最後の更新となります。よろしくお願いします。

**Comment by miyohide** [comment]
Pull Requestありがとうございます。RSS更新済みです。

インタビュー記事の公開作業、お疲れ様でした。

**Comment by zunda** [comment]
RSSの更新をありがとうございました!!

**Comment by miyohide** [comment]
特別号掲載が終了しましたので、Closeします。
