### ISSUE TITLE
TokyuRuby会議10 レポート

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#399]
TokyuRuby会議10 レポート用のIssueです。
担当者の方、よろしくお願いします。
http://magazine.rubyist.net/?0054-TokyuRubyKaigi10Report

**Comment by miyohide** [comment]
@igaiga こんにちは。次回のるびまのリリースを8/21（日）にと考えております。拝見したところ、後は写真を貼り付けるだけという状況かと思われるのですが、進捗いかがでしょうか。
See. #402

**Comment by miyohide** [comment]
@igaiga こんにちは。次回のるびまの記事締め切りが明日に迫っているのですが、進捗状況いかがでしょうか。

「写真はこれを貼って」ということでしたら、私やりますので、ご連絡ください。

**Comment by igaiga** [comment]
@miyohide 遅くなってすみません、これでお願いします。写真の画像の大きさ調整をしてないので、お手数ですがお願いできますでしょうか。m(_ _)m

**Comment by miyohide** [comment]
@igaiga 対応ありがとうございます。画像の大きさ調整承りました。完了しましたらご連絡いたしますので、ご確認ください。8月14日（日）までには対応できるかと思います。

なお、るびまのリリースは8月21日（日）を予定しております。

**Comment by miyohide** [comment]
@igaiga 画像の大きさ編集、終了しました。ご確認いただけますと幸いです。
http://magazine.rubyist.net/?0054-TokyuRubyKaigi10Report

**Comment by miyohide** [comment]
@igaiga 他の記事など、0054号のリリースの目処がたちましたので、8/21（日）17:00ぐらいにリリースする予定です。修正等ありましたら、それまでにお願いします。

**Comment by miyohide** [comment]
@igaiga 遅くなりましたが、るびま0054号をリリース出来ました。開催から素早い記事の寄稿、助かります。今後とも宜しくお願いします。
