### ISSUE TITLE
るびまの編集をやりたいです

### ISSUE THREAD

**Issue by yadokarielectric** [rubima/rubima#401]

**Comment by gunjisatoshi** [comment]
@yadokarielectric お申し出ありがとうございます！　アカウント発行とか諸々は別途ご連絡させていただきます！

**Comment by miyohide** [comment]
@yadokarielectric ご連絡遅くなってすみません。取り急ぎ、編集作業についてやることをまとめましたので、ご参照ください。
https://github.com/rubima/rubima/wiki/HowToEditRubimaArticle

後日、るびま編集用アカウントを頂いた名刺のメールアドレスに送付させていただきます。ご確認いただけますと幸いです。

**Comment by yadokarielectric** [comment]
ありがとうございます。メール確認しました。できそうな仕事があるときは手を挙げようと思います。
