### ISSUE TITLE
0054号 巻頭言

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#403]
@takahashim
こんにちは、るびま編集のみよひでです。
0054号のリリースは2016年8月21日 (日)を予定しております（See. #402 ）。

リリースの1週間前の2016年8月14日(日) ごろまでに巻頭言の原稿をいただけると助かります。
直前のご連絡となり申し訳ございません。

よろしくお願いします。

**Comment by miyohide** [comment]
@takahashim 
るびま編集のみよひでです。

るびま54号の記事が出揃ってきました。

- #400 「Rubyに型があると便利か」
- #397 「tDiary 15th anniversary party レポート」
- #396 「東京 Ruby 会議 11レポート」
- #399 「Tokyu Ruby 会議 10レポート」
- #406 「Rails Girls Tokyo 6th レポート」

が現在の記事候補です。よろしくお願いします。

**Comment by miyohide** [comment]
@takahashim 
るびま編集のみよひでです。

るびま54号の巻頭言、進捗いかがでしょうか。8/21（日）リリースを目指しているため、お忙しいところ恐縮ですが、原稿頂けますと幸いです。

**Comment by takahashim** [comment]
@miyohide 遅くなってすみません！　まだ途中ですが仮のものを書き込んでみました。

**Comment by miyohide** [comment]
@takahashim 記入ありがとうございます。
54号は8/21（日）17:00ぐらいのリリースを予定しておりますので、それまでに完成版へのご対応頂けますと助かります。

**Comment by takahashim** [comment]
@miyohide 直前ですみません、各記事紹介も追加しました

**Comment by miyohide** [comment]
@takahashim ありがとうございます。助かります。

**Comment by miyohide** [comment]
@takahashim いつも素敵な巻頭言、ありがとうございます。無事、リリース出来ました。ご協力ありがとうございました。

**Comment by takahashim** [comment]
@miyohide こちらこそリリースおつかれさまでした！
