### ISSUE TITLE
川崎Ruby会議01 レポート

### ISSUE THREAD

**Issue by minoritea** [rubima/rubima#404]
川崎Ruby会議01のレポートについて起票いたします。

担当者は
@minoritea
@Peranikov
@xmisao
です。
開催日は8/20（土）になります。

よろしくお願い致します。

**Comment by miyohide** [comment]
@minoritea 川崎Ruby会議01のレポート起票、ありがとうございます。
現在のところ、次々号（55号、2016年12月頃）の記事候補とさせてください。

レポート、大変かと思いますが、よろしくお願いします。

**Comment by minoritea** [comment]
みよひでさん＞
了解しました。よろしくお願い致します。

**Comment by miyohide** [comment]
@minoritea さん
0055号のリリース時期を次のスケジュール感で考えております。記事の執筆、いかがでしょうか。

> 記事申し込み・概要締切：2016年12月11日（日）
> 記事の目次・アウトライン締切：2016年12月25日（日）
> 記事の締切：2017年1月8日（日）
> 校正完了・リリース：2017年1月22日（日）

**Comment by minoritea** [comment]
@miyohideさん、そちらのスケジュールで大丈夫です。よろしくお願いいたします。
