### ISSUE TITLE
Rails Girls Tokyo 6thの開催レポート

### ISSUE THREAD

**Issue by kurotaky** [rubima/rubima#406]
[Rails Girls Tokyo 6th](https://railsgirls-tokyo.doorkeeper.jp/events/47257)のレポートをコーチの @torobi さんが書きたいとのことなので、
issue作っておきます〜。よろしくお願いいたします！

**Comment by torobi** [comment]
よろしくお願いします！

**Comment by kurotaky** [comment]
@miyohide @gunjisatoshi 
こちら0054号に掲載したいとのことなので、54号に間に合わせられるように進めたいと思います。
校正などは僕が担当しようと思います！

@torobi 
取り急ぎ、こちらのissueにコメントするかたちで良いので、
記事の概要、アウトライン、目次を頂いてもよろしいでしょうか。
るびまの記事のフォーマットなどは追って案内いたします。

また、記事の締め切りは2016年8月7日(日)でお願いします！ 🙇

**Comment by torobi** [comment]
@miyohide さん、@gunjisatoshiさん
Rails girls Tokyo コーチの渥美です。
この度は参加させていただきありがとうございます。
宜しくお願いいたします！

@kurotaky
締め切り承知しました:bow:

>記事の概要、アウトライン、目次
すみません...不慣れなもので「アウトライン」でどういうものを求められているかわからず..:cry:
取り急ぎ、概要と目次を簡単にですが記載します！
問題あればご指摘ください :bow:　

### 記事の概要
初心者向け女性プログラミングワークショップ Rails Girls Tokyo 6thレポートです

### 目次
* はじめに
* オーガナイザー挨拶
* スポンサーLT
* 会の様子
* アフターパーティ
* 参加して感想
* 書いた人

**Comment by miyohide** [comment]
@torobi さん、記事の寄稿、ありがとうございます。

「アウトライン」ですが、「概要」と「目次」でOKです。

るびまの記事はHikiという文法で書くようになっています。
https://github.com/rubima/rubima/wiki/HikiFormat
Markdownで書きたいという場合は、ご連絡ください。

締め切りがちょっとタイトですが、よろしくお願いします。

**Comment by miyohide** [comment]
@torobi さん、こんにちは。
るびま記事の締切が明日に迫っているのですが、進捗いかがでしょうか。

**Comment by torobi** [comment]
@miyohideさん、こんにちは！
現在、進捗60％ほどで、残りは明日書く予定です。ギリギリとなり恐縮ですが、引き続きよろしくお願いします！

**Comment by torobi** [comment]
@miyohide さん、@kurotakyさん ギリギリになってしまって申し訳有りません！
下記のgistにまとめております。提出の方法がこうしたほうが良いなどあればご指示お願いします！
写真だけ追ってご連絡します！
https://gist.github.com/torobi/5126549dd0b55720fcb151a395165978

**Comment by miyohide** [comment]
@torobi さん、記事の寄稿ありがとうございます。助かります。

早速記事をるびま化させて頂きました。
http://magazine.rubyist.net/?0054-RailsGirlsTokyo6thReport

上記のURLにアクセスするには、ユーザ名とパスワードが必要になります。 @torobi さんのアカウントを作成しますので、お手数ですが、 magazine@ruby-no-kai.org までメールを送付して頂けますでしょうか。作業の都合上、8/8（月）の19:00以降にお知らせする形になるかと思います。お手数おかけしてすみません。

**Comment by torobi** [comment]
@miyohide さん、ご連絡・るびま化ご対応ありがとうございます！
ご指定のメールアドレスにご連絡させていただきます。
どうぞ宜しくお願い致します！

**Comment by miyohide** [comment]
@torobi さん、先ほどメールにてログイン情報を送付いたしました。ご確認ください。

ログインできるようになりますと、写真のアップロードも可能となりますので、準備ができましたらアップロード作業お願いします。

**Comment by torobi** [comment]
@miyohide さん、メール確認させていただきました！
ありがとうございます！
写真アップロード作業も完了いたしました。

**Comment by miyohide** [comment]
@torobi さん、写真アップロードありがとうございます。
@kurotaky さん、お手数ですが、校正作業おねがいします。

**Comment by torobi** [comment]
@kurotaky お手数をおかけしますが、宜しくお願いします！

**Comment by kurotaky** [comment]
校正します! 👌

**Comment by kurotaky** [comment]
@torobi 
当日の雰囲気が伝わってきて、読みやすい記事だと思います 🙆 
気になったところコメントしていきます。

### 記事内のリンクについて
Chrome と Safari で https://attsumi.com/ を開いたところ、
アクセスができません。と出ました！
http://attsumi.com/ なら問題なく表示できます。リンク先を修正したほうが良いかもしれません。

> Rails Girlsガイドに沿って

ここのリンクですが、 `Rails Girlsガイド` までをリンクにして良いかなと思いました。
(今は `Rails Girls` がリンクになっています。)

**Comment by torobi** [comment]
@kurotacy
ご指摘ありがとうございます！修正しました！

**Comment by miyohide** [comment]
@torobi @kurotaky リリースの目処がたちましたので、8/21（日）17:00ぐらいにリリースする予定です。修正等ありましたら、それまでにお願いします。

**Comment by kurotaky** [comment]
はい! 👌

**Comment by torobi** [comment]
承知しました！

**Comment by miyohide** [comment]
@torobi 遅くなりましたが、るびま0054号をリリース出来ました。記事の寄稿ありがとうございます。今後とも宜しくお願いします。

**Comment by torobi** [comment]
@miyohide さん、リリースお疲れさまでした... 🔆 !
記事確認しました！
この度は参加させていただきありがとうございます！
こちらこそ今後ともよろしくお願いします！　🙇 

@kurotaky さん、お誘い&校正ありがとうございました！

**Comment by kurotaky** [comment]
@torobi 
記事の寄稿ありがとうございました！ 👍
