### ISSUE TITLE
0054 号のアクセスランキングを作成する

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#409]

**Comment by kurotaky** [comment]
✋

**Comment by kurotaky** [comment]
📝 
* [ ] アクセスランキング集計する
* [ ] miyohideさんのアカウント作成 (できたらやってみる)

**Comment by kurotaky** [comment]
http://magazine.rubyist.net/?0054-RubyistMagazineRanking

@miyohide 作成しました。

**Comment by miyohide** [comment]
@kurotaky 作成ありがとうございました。助かりました。

**Comment by kurotaky** [comment]
@miyohide 
お疲れ様でした！
`miyohide@gmail.com` にGoogleアナリティクスの権限付与しておきました。
