### ISSUE TITLE
「Ruby における機械学習のための環境整備の取り組み」の記事化

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#414]
@mrkn さん
RubyWorld Conference 2016の場にてお話いただきました、同カンファレンスでの発表内容「Ruby における機械学習のための環境整備の取り組み」を記事化して頂く件、 次のようなスケジュールでのリリースを考えております（c.f. #412 ）。

> 記事申し込み・概要締切：2016年12月11日（日）
> 記事の目次・アウトライン締切：2016年12月25日（日）
> 記事の締切：2017年1月8日（日）
> 校正完了・リリース：2017年1月22日（日）

スケジュールとして執筆可能でしょうか。

**Comment by miyohide** [comment]
記事をいただきましたので、現在編集中です。

http://magazine.rubyist.net/?0055-pycall

**Comment by SugHimsi** [comment]
mrknさんがRuby Business Users Conference 2017で発表したキーノートの資料が追加できそうだけど、いまさらかな。

**Comment by miyohide** [comment]
リリースしましたので、Closeします。

**Comment by gunjisatoshi** [comment]
目次を追加しました。あと冒頭の「書いた人」を追加、表記ゆれ「やってる」「やっている」を「やっている」に統一しました。

あと一番最後に「著者について」があるといいんですけど、これは本人とのやりとりが必要なので追加するかどうかはお任せします。

**Comment by mrkn** [comment]
@gunjisatoshi 自分で入れちゃって大丈夫ですか？

**Comment by gunjisatoshi** [comment]
@mrkn ありがとうございます！　おねがいします！
