### ISSUE TITLE
RubyConf 2016 参加レポート

### ISSUE THREAD

**Issue by mtsmfm** [rubima/rubima#415]
2016/11/10-12 に開催している RubyConf 2016 に参加しているため、そのレポートを書きたいです。
http://rubyconf.org/

**Comment by miyohide** [comment]
@mtsmfm るびま編集部の @miyohide と申します。寄稿の申し出ありがとうございます。
現状のところ、次号のるびまは #412 に記したように、以下のスケジュールでのリリースを考えているのですが、問題ありませんでしょうか。

> 記事申し込み・概要締切：2016年12月11日（日）
> 記事の目次・アウトライン締切：2016年12月25日（日）
> 記事の締切：2017年1月8日（日）
> 校正完了・リリース：2017年1月22日（日）

**Comment by mtsmfm** [comment]
> 現状のところ、次号のるびまは #412 に記したように、以下のスケジュールでのリリースを考えているのですが、問題ありませんでしょうか。

問題ありません! 了解しました :pray:

**Comment by mtsmfm** [comment]
@miyohide 

アウトラインですが、以下のようになる予定です。

```
# RubyConf 2016 参加レポート

## はじめに

## 1日目

## RubyConf 2016 5K

## 2日目

## Rails Tutorial Beerware Night at RubyConf

## 3日目

## おわりに
```

入稿はるびま上でアカウントを発行していただき直接入力する形がよいでしょうか。
PR を出す形がよいでしょうか。

**Comment by miyohide** [comment]
@mtsmfm 遅くなりすみません。
入稿ですが、できるだけ、るびま上でアカウントを発行後、直接入力する形でお願いします。この場合、書式はHikiフォーマットとなります。

お手数ですが、 `magazine@ruby-no-kai.org` までメール送付して頂けますでしょうか。そのメールの返信でるびま上でのアカウント情報をお知らせします。

**Comment by miyohide** [comment]
@mtsmfm 先程アカウントを発行し、いただいたメールの返信という形でご連絡しました。ご確認ください。

**Comment by mtsmfm** [comment]
@miyohide 確認しました。ありがとうございます。
1/8 の締切に間に合うよう入力します。
入力完了したらまた連絡します。

**Comment by miyohide** [comment]
@mtsmfm 確認ありがとうございます。

なお、記事の締め切りですが、当初予定していた記事締め切りは他の記事の都合や編集リソースの都合上、断念しました。現在は3月末に公開することを目指して動いています。

そのため、3月中旬ぐらいまでに記事を書いて頂けると助かります。

お手数おかけしますが、よろしくお願いします。

**Comment by mtsmfm** [comment]
@miyohide 

http://magazine.rubyist.net/?0055-RubyConf2016Report

入力完了しました。ご確認お願いします。

**Comment by miyohide** [comment]
@mtsmfm ありがとうございます。3日間のレポートは大変読み応えがありますね。執筆お疲れ様でした。
各セッションのタイトルが「!!!!」で装飾されていたのですが、「!!!」に変更しました。これで各セッションの区切りが分かりやすくなったように思うのですが、いかがでしょうか。

**Comment by mtsmfm** [comment]
> 各セッションのタイトルが「!!!!」で装飾されていたのですが、「!!!」に変更しました。これで各セッションの区切りが分かりやすくなったように思うのですが、いかがでしょうか。

すみません、ありがとうございます、いいと思います :pray: 
マークダウンからの変換に失敗していたようでした :cry:

**Comment by miyohide** [comment]
@mtsmfm 記事を読み終わりました。他に指摘事項はありません。素晴らしい記事の寄稿、ありがとうございました。

**Comment by ko1** [comment]
最初に、誰が書いたかかいときましょう！

**Comment by mtsmfm** [comment]
@miyohide @ko1 

確認いただきありがとうございます。
書いた人を上にかいときました。

また、若干誤字があったので修正しました。

**Comment by miyohide** [comment]
@mtsmfm 先程、本記事を公開しました。
http://magazine.rubyist.net/?0055-RubyConf2016Report

今回は記事の寄稿、ありがとうございます。大変助かりました。

**Comment by mtsmfm** [comment]
こちらこそリリースお疲れ様でした && ありがとうございました :pray:
