### ISSUE TITLE
名古屋Ruby会議03 レポート

### ISSUE THREAD

**Issue by eitoball** [rubima/rubima#417]
名古屋Ruby会議03 の開催が、2017年02月11日になりましたので、レポート作成 issue を起こします。
レポート担当は、現在の所、未定です。

**Comment by miyohide** [comment]
@eitoball 次号のるびまを以下のスケジュールでリリースしようかと考えています。

    記事申し込み・概要締切：2017年7月9日（日）
    記事の目次・アウトライン締切：2017年7月23日（日）
    記事の締切：2017年8月13日（日）
    校正完了・リリース：2017年8月27日（日）

記事の執筆等間に合いそうでしょうか。

**Comment by eitoball** [comment]
> 記事の執筆等間に合いそうでしょうか。

間に合うと思います。よろしくお願いします。

**Comment by miyohide** [comment]
@eitoball 了解しました。記事候補として挙げさせて頂きます。執筆よろしくお願いします。

**Comment by miyohide** [comment]
@eitoball 記事の締め切りまであと1週間少々となりましたが、執筆の状況はいかがでしょうか。

**Comment by eitoball** [comment]
@miyohide 先週末、時間を取る予定でしたが、できませんでした…今週末も時間をとれないですが、8月10日までには、完成させたいと思っています。よろしくお願いします。

**Comment by miyohide** [comment]
@eitoball 了解しました。よろしくお願いします。

**Comment by eitoball** [comment]
#436 で提出しました。遅くなり申し訳ありません。よろしくお願いします。

**Comment by miyohide** [comment]
@eitoball 記事をるびまに載せました。
http://magazine.rubyist.net/?0056-NagoyaRubyKaigi03Report

上記URLをご確認いただけますでしょうか。

**Comment by eitoball** [comment]
@miyohide 確認しました。画像の大きさを調整したいのですが、良い方法はありますか？直接、るびまの hiki にログインして、編集する方がよい場合、 `eitoball _at_ gmail.com` でアカウントの作成をお願いします。

**Comment by miyohide** [comment]
@eitoball ご確認ありがとうございます。
画像の大きさの調整ですが、大きさを調整した画像ファイルを`{{attach_view('ファイル名')}}`で表示させるのが一番簡単かと思います。これによって、画像への文字の回り込みも避けられるので、この方法が良かと思います。

るびまのアカウントは上記アドレスにメールしましたので、ご確認ください。

**Comment by eitoball** [comment]
@miyohide るびまのアカウントの追加ありがとうございます。ログインして、助言通り、大きさを変更した画像を添付して、`attach_view` を使って表示するようにしました。

記事の方は、これで大丈夫です。今週末から来週にかけて、若干、調整するかもしれませんがよろしいでしょうか？

**Comment by miyohide** [comment]
@eitoball 修正ありがとうございます。
調整については、リリースの前日（8/26（土））まではご自由にどうぞ。
またpull requestについてはcloseして頂けますでしょうか。

**Comment by miyohide** [comment]
@eitoball さきほど0056号リリースしました。寄稿ありがとうございました。
