### ISSUE TITLE
記事「なるほどErlangプロセス」

### ISSUE THREAD

**Issue by niku** [rubima/rubima#420]
[idobata](https://idobata.io/archives/messages/20421996#message_20421996) のあたりで話がありました．
作者は私です．

進行

- [x] 担当を決める
- [x] 作者から概要をもらう
- [x] 作者から目次アウトラインをもらう
- [x] 作者から記事をもらう
- [x] もらった記事を編集Wikiに転載する
- [x] 編集Wikiの記事を校正する
- [x] 編集した記事を作者に確認してもらう
- [ ] 編集MLに作者からの確認が完了した旨を伝える
- [ ] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [ ] 作者にお礼を伝える

**Comment by niku** [comment]
記事は https://gist.github.com/niku/a9fd57e62c51b8cbb6009bf7dbae9111#file-rubima-article-md に書いていこうと思います．

**Comment by miyohide** [comment]
@niku 次号のるびまを以下のスケジュールでリリースしようかと考えています。

    記事申し込み・概要締切：2017年7月9日（日）
    記事の目次・アウトライン締切：2017年7月23日（日）
    記事の締切：2017年8月13日（日）
    校正完了・リリース：2017年8月27日（日）

記事の執筆等間に合いそうでしょうか。

**Comment by niku** [comment]
@miyohide 間に合うと思います．がんばります 📝

**Comment by miyohide** [comment]
@niku 了解しました。記事候補として挙げさせて頂きます。執筆よろしくお願いします。

**Comment by miyohide** [comment]
@niku 記事の締めきりがあと1週間と少しとなりましたが、状況いかがでしょうか。

**Comment by niku** [comment]
うっすみません．すすめます．

**Comment by niku** [comment]
すみません終わりませんでした．
あと1-2日あれば完成させられそうです．
一応PRをつくるところまでやっておきます．(56号に載らなくてもOK)

**Comment by miyohide** [comment]
@niku 了解しました。8/16ぐらいまで待ちますので、そこまでよろしくお願いします。

**Comment by miyohide** [comment]
@niku さきほど0056号リリースしました。寄稿ありがとうございました。

**Comment by niku** [comment]
るびまのおかげでなんとか記事を世に出せました．ありがとうございました！
