### ISSUE TITLE
RubyKaigi 2016 託児室運営記録へのリンクを載せて記事とする

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#421]
RubyKaigi 2016 託児室運営記録へのリンクを載せて、るびまの記事とする。
https://esa-pages.io/p/sharing/68/posts/489/bf1736e8ef111c9d2f9b.html

- [x] 担当を決める（ @ko1 さん）
- [x] 作者から概要をもらう
- [x] 作者から目次アウトラインをもらう
- [x] 作者から記事をもらう
- [x] もらった記事を編集Wikiに転載する
- [x] 編集Wikiの記事を校正する
- [x] 編集した記事を作者に確認してもらう
- [x] 編集MLに作者からの確認が完了した旨を伝える
- [x] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [x] 作者にお礼を伝える

**Comment by miyohide** [comment]
@ko1 本件、進捗いかがでしょう。

**Comment by ko1** [comment]
>  編集MLに作者からの確認が完了した旨を伝える

ML は今はなんだろ？　issue かな？

**Comment by miyohide** [comment]
@ko1 先程、記事をリリースしました。
http://magazine.rubyist.net/?0055-RubyKaigi2016Nursery

寄稿ありがとうございました。
