### ISSUE TITLE
るびまの移行を考える

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#422]
るびまを動かしているSqaleさんが2017年5月末でもってサービスを終了するようです。
http://info.sqale.jp/?eid=105

今後の移行について相談したいと考え、Issueを立てました。

案としては思いついた順で記すと、

- 今のシステムそのまんまHerokuに移す（移行先として提示されている）
- 今のシステムそのまんま別のサービスに移す（特に案なし）
- miyohideが今手元で動かしているjekyll版るびまをどこかで動かす（5月末までに間に合いそうにはない）

などがあります。

というわけで、ご意見欲しいです。@takahashim , @ko1

**Comment by takahashim** [comment]
jekyllはタイミング的に厳しそうであれば、そのまま移行でいいんではないでしょうか。
移行先の希望は特にないです…。

**Comment by znz** [comment]
- 添付ファイル
- 認証情報
- プラグインとテーマが別 repo
- データベースが mysql

というあたりが heroku へそのまま移行するにはひっかりそうな気がします。

- 添付ファイル : もしかしてデータベースに入ってる?
- 認証情報 : これももしかしてデータベースに入ってる?
- プラグインとテーマ: サブモジュールでなんとかなる?

**Comment by takkanm** [comment]
lightsail とかが楽ですかねぇ。 https://amazonlightsail.com

**Comment by hsbt** [comment]
お手数をおかけしております 🙇 

heroku 以降に関してですが、ストレージに保存している添付ファイルを s3 に持っていって、hiki のアップロードプラグインを s3 対応すれば、あとはすでにある技術スタックでなんとかなると思ってます。

1. 認証情報は db に入ってます
1. プラグインとテーマは git submodule で ok
1. データベースは yaml_db を使って mysql から postgresql に変換

**Comment by takahashim** [comment]
実は3月末で契約更新なのですが、とりあえず5月末日までは契約更新しておきますね（なんかディスカウントあるかな？と思ったら特になくて普通に2ヶ月分の金額でした）。

**Comment by gunjisatoshi** [comment]
最近関われてなくてすみません‥‥。

hiki の s3 対応って（誰が手を動かすのかという問題はさておき）、どの程度の工数かかるものでしょうかねえ。

そんなにアクセスの集中するサイトでもないですし、技術的には退化ですが「レンタルサーバ系の何か + Hiki の cgi 運用」のほうが今後の移行（まあ Heroku がすぐになくなるとは考えにくいですが）は楽そうな気がします。

（レンタルサーバ系の何かというのは vps とか Amazon EC2 や Google Compute Engine の VM インスタンスを意図しています）

**Comment by gunjisatoshi** [comment]
という意味で Amazon Lightsail は選択肢の一つかなあと思います。

**Comment by hsbt** [comment]
lightsail, (さくらの VPS でも良いのではー)でも、チャチャッとやるぶんにはいいんじゃないかなあとは思います。やるかなあ。

**Comment by gunjisatoshi** [comment]
vps はまあ (さくらでも何でも) どこでもいいんですけど (まあクラウドサービス比較のような自転車置き場の議論は楽しいので別途やりましょう)、運用系の問題がついて回るのが悩ましいですね。
（このあたりは PaaS だとよしなにやってくれるので楽なんですけど、いやまあ現状でも本当はちゃんとやんないといけないんですけど）

* 定期的なパッチ適用 (これはまあ自動適用にしちゃってもいいんですけど)
* 定期的なバックアップ
* アカウント管理
* 可用性チェック (各種ログの確認とか死活監視とか)

などなど。移行とは直接関係ないので別 Issue にしますかね。

**Comment by miyohide** [comment]
先日のるびまリリース作業に合わせて、MySQLとdata/以下のバックアップを取得しました（記事の追加更新に合わせて再取得済み）。

VPSを借りて今のHikiのものをとりあえず構築してみてみようかと思っています。とりあえず目標は4月中にでも。

どこにするかですが、日本Rubyの会でお金を払ってもらうことを考えると、請求書払いができる所が良いかなと思っています。さくらだとそれができそうなので、まずはさくらのVPSをターゲットにしようかと思っています。

**Comment by takahashim** [comment]
あ、支払いはカードでも大丈夫ですよ（VISAデビットがあるので）

**Comment by miyohide** [comment]
@takahashim ありがとうございます。
#427 にて試行をしているのですが、大体問題なさそうなのでさくらのVPS上で構築しようと考えています。

さくらのVPSの契約を高橋さんに行っていただいた後、ID・パスワードをご連絡して頂く形で情報連携すれば、本番構築までもっていけるかなと思っています。

もう少し試行作業が残っているのですが、4月末までには完了させますので、その後、新環境についてご相談させてください。

**Comment by miyohide** [comment]
移行試行をやってみて、以下のURLで動かすことに成功しました。
http://tk2-228-23726.vs.sakura.ne.jp/

一通り操作してみましたが問題ないかと思っていますが、何か抜け・漏れがあるかもしません。
5/2ぐらいまでは動かしておこうと思いますので、お手すきの際に操作し、問題がありましたらご連絡頂けますと幸いです。

**Comment by hsbt** [comment]
@hsbt の家から見えました!(というだけの第一報告)

**Comment by miyohide** [comment]
特に問題の報告もありませんでしたので、移行したいと考えています。

1点確認したいのですが、 magazine.rubyist.net のネームサーバー設定も移行が必要になるかと思うのですが、これはどこに連絡すればよいのでしょう。

**Comment by hsbt** [comment]
*.rubysit.net は @shugo さんでしたっけ...

**Comment by miyohide** [comment]
@hsbt 連絡遅くなりすみません。 @shugo さんに連絡を取り、ネームサーバー設定も確認が取れました。

**Comment by miyohide** [comment]
@takahashim 移行先でも問題がなかったので、移行作業を行いたいと思います。
契約を高橋さんに行っていただき、ログイン情報をご連絡いただく形が良いかなと思っているのですが、他に良い案があればご連絡頂けますでしょうか。sudo権限があるユーザが1つあれば作業可能です。

今回、私が立てたのは、1Gプラン（HDD 100GB）東京リージョンで立てました。
http://vps.sakura.ad.jp/specification/

**Comment by takahashim** [comment]
そうですね、Rubyの会のカードで支払いたいので、私というかRubyの会名義のアカウントを作ってそれで契約するのが良さそうです。

**Comment by miyohide** [comment]
@takahashim では、契約をお願いできますでしょうか。
情報を miyohide @ gmail . com までご連絡頂けますと幸いです。

**Comment by miyohide** [comment]
遅くなりましたが、立ててみました。
http://tk2-203-11146.vs.sakura.ne.jp/

現状、rebootするとFirewallの設定が初期化されて、httpアクセスができなくなるという問題があります。
（Ubuntu 16.04.02で netfilter-persistent がreboot時に起動に失敗する）

少し動かしてみて問題なければ5/27（土）ぐらいにドメイン移行をしようと思います。

@takahashim ドメイン設定では、VPS側の設定が必要となるようです。お手数ですが、ご協力をお願いします。
http://www.sakura-vps.net/original-domain-settings-for-sakura-vps/

**Comment by takahashim** [comment]
サーバ構築作業ありがとうございます！

@miyohide この「VPS側の設定」ってネームサーバをさくらに持ってくる場合なのでは…？
今回はネームサーバは現状のものを使う前提で、その設定（magazine.rubyist.netの向き先）を`tk2-203-11146.vs.sakura.ne.jp`か`160.16.54.150`に向けてもらうだけだと思うので、そのURLに書かれている設定はしなくても良いのではないかと思いました（読み違いだったらスミマセン！）。

**Comment by znz** [comment]
@miyohide 
> 現状、rebootするとFirewallの設定が初期化されて、httpアクセスができなくなるという問題があります。
> （Ubuntu 16.04.02で netfilter-persistent がreboot時に起動に失敗する）

netfilter-persistent ってよく知らないのですが、 Ubuntu なら標準で入っている ufw を使うんじゃダメなんでしょうか?
(個人的にはIPv4とIPv6の設定を別々にするのが面倒なので、DebianでもUbuntuでもufwを使ってます。)

**Comment by miyohide** [comment]
@takahashim よく分かってなくてすみません。「ドメイン側・VPS側の両方のネームサーバー設定完了後」という記述がありましたので、てっきり、さくらのVPS側でも作業が必要なのかと思っていました。

**Comment by miyohide** [comment]
@znz 
> netfilter-persistent ってよく知らないのですが、 Ubuntu なら標準で入っている ufw を使うんじゃダメなんでしょうか?

当初、ufwを使っていたのですが、設定が有効にならない（ufw上では80番を開けているのに繋がらない）のと再起動したら元に戻ってしまう（非アクティブ状態になってしまう）ということから、ひょっとして...ということでiptablesを直接叩いて80番を開けたところ接続できたので、iptablesを使っています。

**Comment by gunjisatoshi** [comment]
さくらの VPS イメージ (ubuntu) 固有の問題っぽいですね。

http://xibbar.hatenablog.com/entry/2017/04/14/161938

**Comment by miyohide** [comment]
一通りの記事の確認・作成・添付ファイルのアップロード・編集を実施して問題ないようですので、DNSの変更をお願いしておきます。

**Comment by miyohide** [comment]
終わりました。

**Comment by takahashim** [comment]
ありがとうございました！
