### ISSUE TITLE
RubyEventCheckにUpcomingRegionalRubyKaigiをマージする

### ISSUE THREAD

**Issue by kakutani** [rubima/rubima#426]
https://twitter.com/miyohide/status/844526554868662272 がきっかけです。
地域Ruby会議の日程調整のことばかり考えて、https://github.com/ruby-no-kai/official/wiki/Upcomingregionalrubykaigi を用意していました。

が、今さらですがこれはRubyEventCheckとカブるんだな、ということに気づきました。
https://github.com/ruby-no-kai/official/wiki/RubyEventCheck

似たようなの2つメンテするのもいまいちだからRubyEventCheckを正にするのが良さそうと思っています。
(地域Ruby会議のオーガナイザーにもRubyEventCheckを修正してもらうように伝える)

ただ1点相談したいことがあります。

UpcomingRegionalRubyKaigiは **日程** の確認が主な用途です。
現在の「今後の Ruby 関連イベント」のリストの書き方は「イベント/日時/会場」になってるので、
異論がなければフォーマットをシンプルなものに変えたいです。

### 具体的にはこんな感じ:

~~~
#### 2017年

* 04/25(火)..27(木) [RailsConf 2017](https://railsconf.com/)(アリゾナ州フェニックス)
* 05/27(土) [関西Ruby会議2017](http://regional.rubykaigi.org/kansai2017/)(大阪産業創造館 4F イベントホール)
...
* 9/18(月祝)..9/20(水) [RubyKaigi 2017](http://rubykaigi.org/2017)(広島国際会議場)
~~~

* 日付が先。1行ずつのリスト(upcoming式)
* イベント名にリンクする(rubyeventcheck式)
* どこでやってるか情報を書く(rubyeventcheck式)

以下、現状です:

### RubyEventCheck(参考)

<img width="330" alt="rubyeventcheck_ _ruby-no-kai_official_wiki" src="https://cloud.githubusercontent.com/assets/2160/24232532/e7e5866c-0fce-11e7-9aef-d5d7932f25d0.png">

### UpcomingRegionalRubyKaigi(参考)
<img width="561" alt="upcomingregionalrubykaigi_ _ruby-no-kai_official_wiki" src="https://cloud.githubusercontent.com/assets/2160/24232544/f97643e4-0fce-11e7-803b-ae4f62fe846c.png">

変えてよければ、編集作業は私がやります。

いまのるびまで誰のOKをもらえばいいのかわかってないけど、よろしくお願いします。

**Comment by miyohide** [comment]
@kakutani Rubyist MagazineからはRubyEventCheckへのリンクを貼らせて頂いている立場ですので、記述を変更することに異論はありません。また、メンテがし易い方向に進みそうですので、変更してもよいと思っています。

**Comment by kakutani** [comment]
👍  もいくつかついてるし、やっちゃいますね。

ありがたいことに、今年後半にさらにby会議も増えそうだし(まだ確定ではないみたいだけど)

> Rubyist MagazineからはRubyEventCheckへのリンクを貼らせて頂いている立場

何年か前に、もともとるびまの記事の一部だったけど、イベントの頻度とるびまのリリース頻度が合わないから、「じゃあWikiにしちゃうか」みたいな感じでいまのかたちになっているので、「頂いている」というのは私の感覚とは温度/距離感が違うなあという印象。
(RubyEventCheckは元々るびまのもの、という認識)

**Comment by gunjisatoshi** [comment]
> 何年か前に、もともとるびまの記事の一部だったけど、イベントの頻度とるびまのリリース頻度が合わないから、「じゃあWikiにしちゃうか」みたいな感じでいまのかたちになっているので、「頂いている」というのは私の感覚とは温度/距離感が違うなあという印象。
> (RubyEventCheckは元々るびまのもの、という認識)

知らなかった :scream:

**Comment by SugHimsi** [comment]
この件、気になってました。対応ありがとうございます。

**Comment by kakutani** [comment]
やってみました: https://github.com/ruby-no-kai/official/wiki/RubyEventCheck

**Comment by miyohide** [comment]
作業ありがとうございます。助かりました。

Closeします。
