### ISSUE TITLE
Hanami の記事を書かせていただきたいです。

### ISSUE THREAD

**Issue by kbaba1001** [rubima/rubima#428]
Hanami ( http://hanamirb.org/ ) の 1.0.0 がそろそろリリースされる予定なので、紹介記事を書かせていただきたいです。

Hanami は以前 Lotus と呼ばれていたものです。Post Rails を狙うRuby 製 Web フレームワークで、Ruby をゴリゴリ拡張する Rails とは対極に Rack や他の小さな gem をいい感じに組み合わせて、メンテナンスしやすい設計がしやすくなっています。

Hanami 1.0.0 は日本の桜前線にあわせてリリースするらしく、今月中にはでる見込みのようです。

記事は Markdown で書いてもいいでしょうか？

**Comment by kbaba1001** [comment]
http://hanamirb.org/blog/2017/04/06/announcing-hanami-100.html?utm_campaign=ml0011&utm_source=hanami&utm_medium=link

リリースされた！

**Comment by miyohide** [comment]
@kbaba1001 寄稿のお話ありがとうございます。るびま編集部の miyohide と申します。寄稿、是非ともお願いします。

記事はHikiで書いていただきたいのですが、Markdownでも良いです。ただ、Markdownですと一部の記法に制限があります（例えば、`一行コード`のようなものは使えません）。ご了承ください。

ただ、次号のるびまのリリース時期ですが、正式決定したものはなく、漠然と8月ぐらいに出せればいいかなと思っています。また、だいたいリリースの2週間前が記事の締切となります。この点もご了承いただければ。

いろいろとお願いばかりしていますが、寄稿大歓迎です。是非ともお願いします。

**Comment by kbaba1001** [comment]
かしこまりました！

**Comment by miyohide** [comment]
@kbaba1001 次号のるびまを以下のスケジュールでリリースしようかと考えています。

    記事申し込み・概要締切：2017年7月9日（日）
    記事の目次・アウトライン締切：2017年7月23日（日）
    記事の締切：2017年8月13日（日）
    校正完了・リリース：2017年8月27日（日）

記事の執筆等間に合いそうでしょうか。

**Comment by kbaba1001** [comment]
かしこまりました。間に合うように執筆します！

**Comment by miyohide** [comment]
@kbaba1001 了解しました。記事候補として挙げさせて頂きます。執筆よろしくお願いします。

**Comment by kbaba1001** [comment]
@miyohide  Hanamiの記事、とりあえず自分用のメモとしてアウトラインを作りましたが、結構な長さになりそうです。8月13日 には間に合うように執筆します。
Hiki 記法に慣れていないので、プレビューをどうしたらいいのかわからないのですが、何かおすすめのツールなどありますでしょうか？
ひとまず Hiki で書いて、プレビューはるびまの方で作成していただいて細かい部分を修正するという流れでも構いません。

とりあえずタイトルだけ決めましたので、タイトルは「HanamiはRubyの救世主(メシア)となるか、愚かな星と散るのか」でお願いします。

**Comment by miyohide** [comment]
@kbaba1001 Hikiですが、手元で動かせるプレビューツールはありません。
るびまのアカウントを発行して、プレビューページを適宜見ていただくという手もあるのですが、双方ともに負荷が高いかなと思っています。

最近は、記事はMarkdownで書いていただいて、るびま編集部（というか私）で変換して結果を見ていただくという形をとることが多いです。Markdown から Hiki への変換作業があるので、8/13必達でお願いしたいのですが、それでよろしければMarkdownでもOKです。

**Comment by kbaba1001** [comment]
@miyohide かしこまりました。それでは Markdown で書かせていただきます。

**Comment by znz** [comment]
プレビューツールではないですが、Hikiは手元でも動かせるWebアプリなので、そのまま使うという方法はありそうです。
るびま環境と同じプラグインを使いたいなどの条件があると大変そうですが、基本的な書式で書いてプレビューツール的に使うのなら、簡単に動かせるはずなんじゃないかと思っているのですが。

**Comment by kbaba1001** [comment]
今日の昼頃には提出します

**Comment by kbaba1001** [comment]
@miyohide ↑ 記事を Pull Request にしましたのでご確認をお願いします。長くてすみません。。。

**Comment by miyohide** [comment]
@kbaba1001 記事ありがとうございます。現在、るびまのHikiに変換していますので、今しばらくお待ち下さい。今週末ぐらいには何とか。

**Comment by kbaba1001** [comment]
@miyohide かしこまりました。知人から PR にレビューを頂いておりまして、申し訳ないのですが、Hikiの変換作業が終わった後に若干加筆修正したいのですがよろしいでしょうか？ 
スケジュール的に難しいということであれば断念します。ご迷惑をおかけします。

**Comment by miyohide** [comment]
@kbaba1001 加筆修正、問題ないです。16日までに終わらせて頂けますと助かります。

**Comment by kbaba1001** [comment]
@miyohide ありがとうございます!!! すみません :sweat_drops:

**Comment by kbaba1001** [comment]
@miyohide おまたせしました。 PR を修正しましたので、よろしくお願いします。

**Comment by miyohide** [comment]
@kbaba1001 るびまへの掲載が完了しました。
http://magazine.rubyist.net/?0056-hanami

上記URLを参照してご確認いただけますでしょうか。

**Comment by kbaba1001** [comment]
@miyohide ありがとうございます。一通り確認しました。
下記の2点だけご対応いただけますでしょうか。
よろしくお願いします。

### 「Router」の節

```
> A Rack application is a Ruby object (not a class) that responds to call. It takes exactly one argument, the environment and returns an Array of exactly three values: The status, the headers, and the body.
```

上記の引用の部分、引用のデザインがないようであれば、コードと同じように□枠で囲っていただいてもよいでしょうか？

### 「Hanami::Cli」 の節

```
これは hanami コマンドの内部実装 *ではなく*
```

上記の部分「ではなく」を太字にしたいのですが可能でしょうか？
(Markdown だと太字は `**` でしたが、間違えて `*` にしていました :sweat:  )

太字の対応が難しいようであれば、「これは hanami コマンドの内部実装ではなく」でお願いします。

**Comment by miyohide** [comment]
@kbaba1001 早速の確認ありがとうございます。
修正してみました。ご確認ください。
http://magazine.rubyist.net/?0056-hanami

**Comment by kbaba1001** [comment]
@miyohide ありがとうございます。確認しました。これでいいと思います :ok_man:

**Comment by miyohide** [comment]
@kbaba1001 さきほどリリースしました。寄稿ありがとうございました。
