### ISSUE TITLE
関西Ruby会議2017 レポート

### ISSUE THREAD

**Issue by t-kusakabe** [rubima/rubima#430]
関西Ruby会議2017のレポート作成issueを起こします。
- レポート担当 : @t-kusakabe
- 開催 : 2017/05/27

よろしくお願いいたします。

**Comment by miyohide** [comment]
@t-kusakabe 記事をるびまに載せました。
http://magazine.rubyist.net/?0056-KansaiRubyKaigi2017Report

上記URLをご確認いただけますでしょうか。

**Comment by miyohide** [comment]
@t-kusakabe さきほど0056号リリースしました。寄稿ありがとうございました。
