### ISSUE TITLE
ぎんざRuby会議 レポート

### ISSUE THREAD

**Issue by y-yagi** [rubima/rubima#435]
ぎんざRuby会議のレポート作成issueを起こします。

レポート担当 : @suginoy さん
開催 : 2017/08/04

宜しくお願い致します。

**Comment by suginoy** [comment]
承知しました。🙏

**Comment by miyohide** [comment]
@y-yagi @suginoy ぎんざRuby会議お疲れ様でした。
次回のるびまは、2018年1月末ぐらいのリリースを考えています。2018年1月初旬ぐらいまでに執筆して頂けますと助かります。

**Comment by miyohide** [comment]
@suginoy RubyKaigiの場で聞かれた件です。まとめてここで回答します。

- 編集指針については、 https://github.com/rubima/rubima/wiki/EditPolicy に記していますのでご確認ください。特に「極力守っていただきたいこと」について守って頂けますと助かります。
- 現状、るびまはhikiで書くことになっています。Markdownで書きたい場合は、ご連絡をお願いします。Markdownで書く場合、hikiとは異なった結果となる可能性があります（例えば、バッククォートを使った表現`p "hogehoge"`はhikiでは未対応です）。

**Comment by miyohide** [comment]
@suginoy 次号のるびまを 2018年2月11日（日）にリリースしようと考えています。（see. #453 ）
それまでにレポートの提出をお願いしたいのですが、大丈夫でしょうか。

**Comment by suginoy** [comment]
@miyohide リリース日について承知しました。手元に Hiki の環境がないので、Markdown にさせていただきたいです。

**Comment by miyohide** [comment]
@suginoy Markdown、了解です。

**Comment by miyohide** [comment]
@suginoy 状況いかがでしょう。

**Comment by miyohide** [comment]
@suginoy 1/14までに概要等のご連絡がありませんでしたので、残念ですが、57号への掲載は見送りとさせてください。

**Comment by suginoy** [comment]
@miyohide

返信が遅れて大変申し訳ありません。
原稿の gist が https://gist.github.com/suginoy/8fe9827fd07a1fff43ad00042bd8c160 にあります。
(許諾のある画像の挿入作業が残っていますが、今週末までには終える予定です。)
あまり時間を置かない方がよいトピックもあるため、できれば次号で含めいただきたいのですが、難しいでしょうか？

**Comment by miyohide** [comment]
@suginoy 画像の挿入作業など未完の作業を今週末までに終了し、ご連絡いただけましたら次号に入れます。間に合わなければ次々号以降に。

なにぶん、一人で編集・発行・メンテ作業を行っていますので、〆切等にはご協力をお願いします。

**Comment by miyohide** [comment]
@suginoy 本日リリースしました。寄稿ありがとうございました。
