### ISSUE TITLE
RubyKaigi 2017直前特集号を出す

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#445]
先日行われたるびま会議で出た話の内容です。

記事としては、

- RejectKaigi 2017の内容がSpeeeさんの企業ブログに載るので、そこへのリンクを貼る
- Rejectkaigi 2017にて行われた「RubyKaigi 2017タイムテーブル徹底解説」のサマリを記事化

を予定しています。

スケジュールとしては、ざっくりRubyKaigi 開催前の1週間前（9月11日ごろ）には出したいなと思っています...が、結構タイトな感じなので、できたところから五月雨で出しても良いかもしれません。

他に載せたほうが良い記事（記事へのリンクなど）があったらコメントいただけますと助かります。

**Comment by ko1** [comment]
上記2記事の執筆者は誰でしょう。

あと、スピーカーに事前資料を寄せろ、と聞いてみようと思います。

**Comment by ko1** [comment]
https://gist.github.com/ko1/4533e4e4068929967145160f24931d66 メール送りました。

**Comment by miyohide** [comment]
@ko1 
- RejectKaigi  2017の内容が記された企業ブログにリンクを貼る → @miyohide が担当します。
- 「RubyKaigi 2017タイムテーブル徹底解説」のサマリ → @takahashim さん

スピーカーへの連絡ありがとうございます。ここでのコメントで頂いたものは @miyohide が担当しようかと考えています。

**Comment by ko1** [comment]
> 「RubyKaigi 2017タイムテーブル徹底解説」のサマリ → @takahashim さん

いつごろ出来ます？

**Comment by takahashim** [comment]
今週末に頑張る予定ですが、いったん松田さん卜部さんに見てもらうので来週半ばくらいになりそうです

**Comment by miyohide** [comment]
ざっと表紙を作りました。
http://magazine.rubyist.net/?preRubyKaig2017

**Comment by znz** [comment]
URL の `Kaig` → `Kaigi` でしょうか

**Comment by miyohide** [comment]
@znz 修正しました。

**Comment by miyohide** [comment]
一つの案ですが、各企業ブログ（スポンサーさん？）が書いているRubyKaigiに関する情報をまとめるというのはどうでしょうか。
自分がちょっと目にしたのは↓の記事なのですが、集めれば色々あるかなと。
https://developer.aiming-inc.com/ruby/rubykaigi-2017-gold-sponsor/

**Comment by miyohide** [comment]
Reject Ruby Kaigiの記事はもう出ていたので、リンク張ります。
http://tech.speee.jp/entry/2017/08/25/121353

**Comment by hsbt** [comment]
これ、いつ頃公開予定でしょう...? 事前資料というか登壇しますお知らせを書こうと思ってまして、直前特集号までには用意しようと思ってます。

**Comment by miyohide** [comment]
@hsbt 最初の版を9/11（月）の夜にでも出そうと思っています。また、随時更新していく予定です。

**Comment by miyohide** [comment]
@hsbt 追記です。記事についてですが、るびまに直接書くことでも、ご自身のblogや日記などに書かれているものへのリンクでも両方対応できます。リンクの場合は一言コメントをいただければ合わせて直前号に記します。

**Comment by znz** [comment]
https://developer.aiming-inc.com/ruby/rubykaigi-2017-gold-sponsor/ に Ruby Kaigi と書かれているところがあるのが気になったのですが、公式には RubyKaigi でスペースは入らないという認識であっているのでしょうか?

**Comment by miyohide** [comment]
とりあえずえいや！で出しました。
http://magazine.rubyist.net/?preRubyKaigi2017

**Comment by hsbt** [comment]
@miyohide もう出ていた...! 自分が発表する内容の予告編とスポンサーしますのお知らせを弊社の技術ブログに掲載予定です。9/11 には公開しようと思うので、公開後にここに参上します。

**Comment by youchan** [comment]
@miyohide まだ間に合いますでしょうか。
http://blog.youchan.org/2017-09-10
https://youchan.github.io/RubyKaigi2017/
ブログとスライド公開しました。

**Comment by miyohide** [comment]
@hsbt 了解しました。公開を楽しみにしています。

**Comment by miyohide** [comment]
@youchan ご連絡ありがとうございます。反映しました。

**Comment by Nyoho** [comment]
RubyKaigi (本体) が広島に来ることがいかに貴重なことか - ワタタツの日記!(2017-09-08)
https://nyoho.jp/diary/?date=20170908#p01

を応募いたします。よろしくお願い申し上げます。

**Comment by hsbt** [comment]
柴田登壇に関して書いたので追記お願いします!

https://tech.pepabo.com/2017/09/11/rubykaigi-2017/

**Comment by miyohide** [comment]
@Nyoho 紹介ありがとうございます。反映しました。

**Comment by miyohide** [comment]
@hsbt ご連絡ありがとうございます。追記しました

**Comment by nishimotz** [comment]
スピーカーとしての事前資料のつもりで書きました

なぜ @24motz aka @nishimotz は #RubyKaigi で講演をするのか
https://d.nishimotz.com/archives/2038

**Comment by takahashim** [comment]
すみません、タイムテーブル徹底解説書きました！

**Comment by kou** [comment]
書きました。
http://www.clear-code.com/blog/2017/9/11.html

**Comment by masa16** [comment]
単なるリンク集ですが、よろしければ事前資料集として載せてください。
https://github.com/masa16/rk17info/blob/master/README.md

**Comment by miyohide** [comment]
@nishimotz 事前資料、ありがとうございます。掲載しました。

**Comment by miyohide** [comment]
@kou 事前資料、ありがとうございます。掲載しました。

**Comment by miyohide** [comment]
@masa16 事前資料、ありがとうございます。掲載しました。

**Comment by miyohide** [comment]
@takahashim タイムテーブル徹底解説、ありがとうございます。

**Comment by ko1** [comment]
@takahashim 著者名がないので微妙な感じ。

**Comment by hachi8833** [comment]
RubyKaigi単独の記事でなくて恐縮ですが、差し支えなければ追記お願いいたします:
https://techracho.bpsinc.jp/hachi8833/2017_09_08/45408

**Comment by takahashim** [comment]
@ko1 あー、たしかに。記事末尾に書いておきますね

**Comment by miyohide** [comment]
@hachi8833 情報ありがとうございます。更新しました。

**Comment by ko1** [comment]
伊藤泰さん: "Introducing the Jet Programming Language" <http://rubykaigi.org/2017/presentations/i2y_.html> の事前資料をいただきました。

https://gist.github.com/i2y/849a544ba8dc6f626644ee22e97a8e6e

**Comment by miyohide** [comment]
@ko1 反映しました。

**Comment by takahashim** [comment]
After Kaigi Sponsorのpixivこしばさんから https://inside.pixiv.blog/bash/2448 をご紹介くださいとご連絡いただきました

**Comment by miyohide** [comment]
@takahashim ご連絡ありがとうございます。反映しました。

**Comment by lctseng** [comment]
Hi, 
I'm Henry Tseng, 
I would like to publish an article about my talk
The link is below:
https://5xruby.tw/en/posts/tamashii-create-rails-iot-application-more-easily

Thanks a lot!

**Comment by miyohide** [comment]
@lctseng 
Hi.
Thank you for an article about your talk. I add a your link to http://magazine.rubyist.net/?preRubyKaigi2017

**Comment by mtsmfm** [comment]
大変遅くなりましたが書きました 🙇 

http://mtsmfm.github.io/2017/09/15/rubykaigi.html

**Comment by miyohide** [comment]
@mtsmfm ありがとうございます。追記しました。

**Comment by ko1** [comment]
大変遅くなりましたが、やっと書きました... http://www.atdot.net/~ko1/diary/201709.html#d17

**Comment by ko1** [comment]
こちら、リンクいただきました。
http://zverok.github.io/blog/2017-09-16-infoboxer-rubykaigi.html

**Comment by miyohide** [comment]
@ko1 ありがとうございます。両方追加しました。

**Comment by mrkn** [comment]
直前で申し訳ありません。以下の記事へのリンクも追加していただけますでしょうか。

http://tech.speee.jp/entry/2017/09/17/005431

よろしくお願いいたします。

**Comment by miyohide** [comment]
@mrkn ありがとうございます。追加しました。

**Comment by soutaro** [comment]
http://soutaro.hatenablog.com/entry/2017/09/17/151221 遅くなってしまって申し訳ないのですが、書きましたのでよろしくお願いします。

**Comment by znz** [comment]
@soutaro ありがとうございます。追加しました。
ブログのタイトルの方は Anntation になっていましたが、 http://rubykaigi.org/2017/presentations/soutaro.html の方で Annotations になっていたので、s をつけています。

**Comment by soutaro** [comment]
あれっ、ありがとうございます 🙏 ブログのタイトルを修正しました。

**Comment by ko1** [comment]
https://twitter.com/yotii23/status/909619239887048704

書いてくれました！

**Comment by miyohide** [comment]
@ko1 追加しました。

**Comment by Shekharrajak** [comment]
Hello,
I would like to publish an article : 
https://github.com/SciRuby/daru-view

Thanks!

**Comment by miyohide** [comment]
RubyKaigi 2017が終わったので閉じます。
