### ISSUE TITLE
とちぎRuby会議07のレポート

### ISSUE THREAD

**Issue by vestige** [rubima/rubima#447]
とちぎRuby会議07 のレポート作成issueを起こします。

レポート担当 :  @tkojitu さん
開催 : 2017/08/26

宜しくお願い致します。

**Comment by vestige** [comment]
すでにレポートをだいたいは作ってもらっていて、来週のtoRubyの勉強会(9/6)のなかでレビューする予定です。

**Comment by miyohide** [comment]
@vestige @tkojitu とちぎRuby会議07開催お疲れ様でした。
次のるびまは来年1月ごろのリリースを考えています。

**Comment by vestige** [comment]
こんな感じでかいてもらっています。

https://gist.github.com/tkojitu/c367aa60afb8d1cc84330e70700e6384

**Comment by miyohide** [comment]
@vestige @tkojitu 記事のドラフト、ありがとうございます。

3点お願いがあります。

1. 著者の連絡先がわかる記述を末尾に追加して頂けますでしょうか。
2. 「書いた人」という記述を記事の先頭に記してください。
3. 写真を使用する場合は、写真提供者に許可を得てから使用をお願いします。

1についてですが、「著者について」という記述を追加してください（参考：http://magazine.rubyist.net/?0056-hanami）。後々、記事について問合せがあったときに連絡先として提示したいと考えています。
2についてですが、書いた人をPRする意図で記述をお願いしています。

**Comment by vestige** [comment]
@miyohide  torubyのよねざわです。遅くなりましたが、指摘のあった箇所も含めてレポートにしてもらいました。ご確認お願いします。写真については、レイアウトしていないので別途相談させてくださいー。

https://gist.github.com/tkojitu/c367aa60afb8d1cc84330e70700e6384

**Comment by miyohide** [comment]
@vestige 寄稿ありがとうございます。写真ですが、貼り付ける場所にURLを貼っていただければ。

**Comment by vestige** [comment]
@miyohide 写真のURLを貼りました。よろしくお願いします。

https://gist.github.com/vestige/a3e166ed91806d7b2c69a74f3022a8e7

**Comment by miyohide** [comment]
@vestige ありがとうございます。るびまに載せるために作業が必要です。1～2週間ほどお待ちください。

**Comment by miyohide** [comment]
@vestige 遅くなりました。るびまに載せました。ご確認いただけますでしょうか。
http://magazine.rubyist.net/?0057-TochigiRubyKaigi07Report

すみません、1点お願いがあります。とちぎRuby会議06の記事のように、「はじめに」の部分に日時・場所・主催・後援・参加者数等を記して頂けますでしょうか。
http://magazine.rubyist.net/?0051-TochigiRubyKaigi06Report

**Comment by vestige** [comment]
@miyohide 
ありがとうございますっ。
写真は大丈夫だと、思います。はじめにのところ、直しておきますね。
２、３日中に直しておきますー。

**Comment by miyohide** [comment]
@vestige 早速の追記、ありがとうございます。対応しました。

では、これで57号の記事としてリリースします。リリース予定は2018年2月11日（日）と先となりますが、それまでは修正可能ですので、何かありましたらご連絡ください。

**Comment by miyohide** [comment]
@vestige 本日リリースしました。寄稿ありがとうございました。

**Comment by vestige** [comment]
こちらこそ、ありがとうございましたー！また、次回もよろしくお願いしますー。
