### ISSUE TITLE
0012-qwikWeb の（固定コンテンツの）更新

### ISSUE THREAD

**Issue by metanest** [rubima/rubima#448]
だいぶ旧聞になる件なのですが、「ジェームズ・クラーク式記法」という呼び方について、実は eto さんが勘違いで作ってしまったものだった、ということについて、Wiki版のほうに加筆しました。
（どなたかにレビューしていだたいて）更新していただけたら、と思うのですが……

あと、Hikiの記法でURLに見える文字列がリンクになるのは回避不可能でしょうか（xml名前空間の記法の部分が）

**Comment by miyohide** [comment]
@metanest コメントありがとうございます。申し訳ありませんが、「Wiki版」がどれを指すのか分かりませんでしたので、ご連絡頂けますと助かります。

**Comment by znz** [comment]
Hiki の記法でリンクを回避する方法があるのかはわかりませんでしたが、 rubima の hiki の場合は e プラグインを `{{e(58)}}` のように使って回避できるかもしれません。

**Comment by znz** [comment]
@miyohide 更新差分の通知メールがきていたのをみつけてわかったのですが、「Wiki版」というのは wiki.fdiary.net の非公開側の方のようです。

**Comment by metanest** [comment]
すいません、URLを公開していいかどうか、今調べていました。それです。よろしくお願いします。

**Comment by miyohide** [comment]
@znz wiki.fdiary.netの存在を今知りました。http://wiki.fdiary.net/rubima/ ですか？

**Comment by znz** [comment]
@miyohide 昔の 本番Wiki (のhikifarm側のURL) ではなく編集Wiki の方です。
認証がかかってて知らない人にはどうせみえないので、URL は idobata の方に書きました。

**Comment by miyohide** [comment]
@metanest 修正しました。
http://magazine.rubyist.net/?0012-qwikWeb

意図したものと異なる場合はお手数ですが、このIssueのコメントにてお知らせください。

**Comment by metanest** [comment]
`{http://www.w3.org/2000/xmlns/}xmlns` の部分が崩れているのの修正をお願いします。Wiki記法のソースで確認していただけると思うのですが、コロンの部分だけを、こちらのイシューのコメントにありますように「e プラグインを {{e(58)}} のように使って」、回避するとうまくできるはずです。こんな感じに `{http{{e(58)}}//www.w3.org/2000/xmlns/}xmlns` 。

**Comment by miyohide** [comment]
@metanest 修正しました。
