### ISSUE TITLE
wiki.fdiary.net にあるるびま編集Wikiを削除したい

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#449]
主メンテナのなかで知っている人も少なくなり、ここ数年誰も更新していないので、wiki.fdiary.netにあるるびま編集Wikiを削除したいと思います。

特に意見がなければ、11月中旬ぐらいには削除しようと思っています。

**Comment by znz** [comment]
編集Wikiにしか残っていない情報があるので、どの情報がそうなのかの特定と対処を決めてからなら問題ないと思います。

(diff ML 自体とそのアーカイブは編集Wikiが削除されたら消しちゃってもいいのかもしれない。)

**Comment by miyohide** [comment]
ちょっと時間が取れないので一旦閉じます。
