### ISSUE TITLE
福岡Ruby会議02のレポート

### ISSUE THREAD

**Issue by nagachika** [rubima/rubima#452]
福岡Ruby会議02 のレポート作成のissueを作成します。

レポート担当:  @nagachika, @bake0937 
開催： 2017/11/25

宜しくお願い致します。

**Comment by miyohide** [comment]
@nagachika @bake0937 issue作成ありがとうございます。
今のところ、次号のリリースを 次のように考えています。（see. #453 ）

  記事申し込み・概要締切：2018年1月7日（日） ← だいたいの掲載記事を決める。中間フォロー。
  記事の締切：2018年1月21日（日）← 記事の〆切。基本はここがデッドライン
  校正完了・リリース：2018年2月4日（日）

間に合いましたら57号に間に合わせたいと考えています。

よろしくお願いします。

**Comment by nagachika** [comment]
すみません、書き漏れていましたが、記事は Markdown で作成中です。

https://github.com/fukuokarb/rubima のブランチで作業して、状況をあきらかにするため pull request としています(通知などでわずらわしかったらすみません)。 https://github.com/rubima/rubima/pull/458
写真は会議スタッフが撮影したものを利用しており許可を得ております。

**Comment by miyohide** [comment]
@nagachika ドラフトの公開ありがとうございます。概ねできているように見受けられますが、まだ大きく追記する予定でしょうか？

なお、Markdownでの提出でもOKですが、Hikiへの変換をしたりるびまに載せるための作業をしたり、etc....なので、1/28（日）必達でお願いします。

**Comment by nagachika** [comment]
あとは
- 「著者について」のところにレポート担当者のプロフィールを追記
- 文体や体裁の統一
- 細かな校正
くらいで、本文に大きな追加はない予定です。
締切までに完了して [WIP] をはずしたいと思っています。

**Comment by miyohide** [comment]
@nagachika 了解しました。では、1/28（日）までの完了、お待ちしております。

**Comment by miyohide** [comment]
@nagachika 本日リリースしました。寄稿ありがとうございました。
