### ISSUE TITLE
るびま 0057 号のリリーススケジュール

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#453]
るびま 0057 号のリリーススケジュールを次のように考えています。

    記事申し込み・概要締切：2018年1月14日（日） ← だいたいの掲載記事を決める。中間フォロー。
    記事の締切：2018年1月28日（日）← 記事の〆切。基本はここがデッドライン
    校正完了・リリース：2018年2月11日（日）

というものを考えています。

記事については、これから感触を聞いてみます。

今のところ、各地域Ruby会議のレポート＋ @yhara さんが記事を書いてくれるかも...と聞いています。

**Comment by yhara** [comment]
yharaです。http://magazine.rubyist.net/?0018-GameProgramingForRubySDL を[DXOpal](https://github.com/yhara/dxopal)を使うようにしたアップデート版を書こうかなと考えています。
(もう10年前になるんですね…^^;) よろしくお願いします。
記事はmarkdownとかで書けば良いのでしょうか？

**Comment by yhara** [comment]
https://twitter.com/miyohide/status/936576013357629440 とのことなのでHikiDocで書こうと思います。

**Comment by miyohide** [comment]
@yhara 記事用のIssueを別途立てたので、記事に関しては以降 #454 にてお願いしますm(_ _)m

**Comment by miyohide** [comment]
リリースできましたのでCloseします。
