### ISSUE TITLE
Ruby/SDLで始めるゲームプログラミングの更新版の記事

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#454]
Ruby/SDLで始めるゲームプログラミングの更新版の記事を載せる。著者は @yhara さん。以下、作業テンプレ。

- [x] 原稿を受け取る
- [x] ページ名を決める ( http://magazine.rubyist.net/?0057-XXXX の XXXX の部分)
- [x] 上記名前で auth つきで空ページをつくる (auth つきだとログインしないと見えない)
- [x] 上記で作った空ページにいただいた原稿を転記する
- [x] るびまWiki のアカウントを作って著者の方にお伝えする
- [x] 転記した記事を著者の方に見ていただき、必要であれば加筆修正いただく
- [x] 表紙からリンクを張る
- [x] 表紙の記事リンクの作成・記事の説明・難易度をつける
- [x] リリース時に auth を外して誰でも見える状態にする

**Comment by yhara** [comment]
いまのところ進捗は50％くらいです。

@miyohide 原稿ってどうやって渡せばよいでしょうか？HikiDocファイルと、画像が何枚かあります。

**Comment by miyohide** [comment]
@yhara 
原稿は、るびまのHikiに直接入力して頂く形になります。アカウントを発行しますので、
メール（miyohide @ gmail . com ）もしくはTwitterでDMください。数日以内にアカウントを発行します。
ページは以下に用意しました。
http://magazine.rubyist.net/?0057-RevisedGameProgramingForRubySDL

**Comment by miyohide** [comment]
サイトは http://magazine.rubyist.net/?0057-GameProgramingWithDXOpal に変更とのこと。

**Comment by yhara** [comment]
しばらく細かい修正を入れていましたが、これで一段落したつもりです。よろしくお願いします。

**Comment by miyohide** [comment]
@yhara 無事、リリースできました。寄稿ありがとうございました。
