### ISSUE TITLE
jekyll版るびまについて

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#455]
とりあえず、herokuに載せて動かしてみました。
https://floating-woodland-58089.herokuapp.com/

特に問題なく動いているような気がしますが、触っていただいてご意見等頂けますと助かります。とりあえず今日から1週間ぐらいはこのまま動かそうかと思っています。

なお、データは56号まで。57号のデータはまだ載せていませんが、近日中に更新しようかと思っています。移行については、58号リリースの後にやろうかなと考えています。

**Comment by ko1** [comment]
結構もっさりしてる感じがするね。

**Comment by miyohide** [comment]
もっさりしているのは30分アクセスがないとSleepに入ってしまうからですね。一度起きてしまえば私の環境だとサクサク動いてくれてます。

**Comment by hsbt** [comment]
見てみましたが spinup の時間はどうしてももたつきますね。

1x dyno くらいなら Ruby の会に拠出してもらうといいかもしれない(支払い周りのあれこれがめんどそうなので @takahashim にやってもらった方が楽そう)

**Comment by ore-public** [comment]
見てみました。

コードブロックの部分が、周りの文字と同化して見えてしまうので
元々と同じように枠線が付くといいなと思います。

**Comment by takahashim** [comment]
@miyohide @hsbt Rubyの会の方から来ました。現行のappsに対して info@ruby-no-kai.orgをCollaboratorsに入れてもらってtransferしてもらってもHobby dynoにするでもいいですし、別個にRubyの会アカウントでHobby dynoなappsを作ってそこの権限を渡すのでもいいです。

**Comment by sunaot** [comment]
- plugin なのか css なのかまで見ていませんが、画像へのテキストの回り込みが挙動違っていてレイアウトが崩れたように見えているものがあります [新](https://floating-woodland-58089.herokuapp.com/articles/0056/0056-KansaiRubyKaigi2017Report.html) [旧](http://magazine.rubyist.net/?0056-KansaiRubyKaigi2017Report)
- こちらは plugin だと思いますが映像の埋込に失敗しているようでした (『桐島、部活やめるってよ』のあたりなど) [新](https://floating-woodland-58089.herokuapp.com/articles/0042/0042-FollowUpKirishimaRuby.html) [旧](http://magazine.rubyist.net/?0042-FollowUpKirishimaRuby)

(るびまが Jekyll で動いていてすごいです)

**Comment by sunaot** [comment]
細かくいくつか気付いたので追加で報告します。

- 書籍紹介「プログラミング Elixir」のタイトルが 54 号のトップページに出ていません (HTML 上も出ていないので単純に元データを直すと直るのかもしれません)
  - [新](https://floating-woodland-58089.herokuapp.com/articles/0054/0054-index.html) [旧](http://magazine.rubyist.net/?0054)
- 30 号読者プレゼントをトップページからリンクを踏んで記事を見ようとすると `Not found` が返ります
  - [新](https://floating-woodland-58089.herokuapp.com/articles/0030/0030-index.html) [旧](http://magazine.rubyist.net/?0030)
  - ちなみにリンクされている記事のパスはこれでした `/articles/0030/0030%20号%20読者プレゼント`
  - `/articles/0030/0030-Present.html` を叩くと記事は存在するのでリンク先が変われば直りそうです
- `<blockquote>` が `<pre><code>` と同様に変換されているので見た目が変わっている部分がありました (記事によって使い方も違いそうな部分なのでそういうものだということなら、それでいいと思います)
  - [新](https://floating-woodland-58089.herokuapp.com/articles/0050/0050-Hypermedia.html#もし-html-にリンクがなかったら) [旧](http://magazine.rubyist.net/?0050-Hypermedia#l14)
- 定義リスト記法が解釈されずに `: :` のまま表示されています
  - [新](https://floating-woodland-58089.herokuapp.com/articles/0050/0050-Hypermedia.html#もし-html-にリンクがなかったら) [旧](http://magazine.rubyist.net/?0050-Hypermedia#l14)
- `<table>` タグの罫線が表示されていませんでした。区切りがわかるように罫線入っている方が読みやすそうです
  - [新](https://floating-woodland-58089.herokuapp.com/articles/0050/0050-Hypermedia.html) [旧](http://magazine.rubyist.net/?0050-Hypermedia)
- footnote の *8 の途中から切れて、footnote の先頭に表示されています
  - [新](https://floating-woodland-58089.herokuapp.com/articles/0050/0050-Hypermedia.html) [旧](http://magazine.rubyist.net/?0050-Hypermedia) の footnote

**Comment by miyohide** [comment]
みなさま、コメントや検証ありがとうございます。徐々に対応します。

取り急ぎ、 @ore-public さんのコードの部分に枠線を入れてみました。

この対応をしていて気がついたんですが、横スクロールが発生しています。これも修正します。
