### ISSUE TITLE
Rubyist Hotlinks（村田さん）テープ起こしの募集

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#456]
村田さんのRubyist Hotlinksインタビューが先日行われまして、録音データを現在 @miyohide が持っています。

粗いテープ起こしは、外部の業者に依頼する予定なのですが、そこからの修正について協力していただける方を募集します。

音声データは135分（2時間15分）。ざっと一通り聞いたところ、音声が聞き取りにくい部分があったりします。

作業開始は2018年1月上旬、期限は2018年3月ぐらいを考えています（次号の58号には作業が間に合わないと判断しています）。

よろしくお願いします。

**Comment by hsbt** [comment]
テープ起こしではありませんが原稿で使える写真素材を @shyouhei と @mrkn に渡しました。直接必要な場合は呼んでください、みよひでさんにこっそり渡します。

**Comment by SugHimsi** [comment]
PyCallには注目しています。出来れば協力したく。

**Comment by znz** [comment]
興味があるので手伝いたいです。

**Comment by miyohide** [comment]
@SugHimsi @znz 業者から文字起こしデータが届きましたので、私のPrivateリポジトリに置きました。両名をCollaboratorとして招待しましたので、ご確認をお願いします。
音声データは、idobataにリンクを貼り付けましたので、ご確認ください。

**Comment by mrkn** [comment]
(@SugHimsi PyCall の話はあまりしていない気がします。すみません・・・)

**Comment by SugHimsi** [comment]
ちらっと出てきたFeynmanが脚注をつけるほどかどうか悩ましいな。

**Comment by miyohide** [comment]
@hsbt @mrkn 
文字起こしをしているときにわからないところが出てきたので、教えていただけますでしょうか。

Ruby/RPMの話のくだりで以下のような文言が出てきたのですが、〓で囲んだ部分や`Rawhide`が
あっているのか分かりませんでした。

```
柴田：Kondaraは、src.rpmを持ってきて、〓アンチャンデデ〓ビルドするシステムは何だっけ。
村田：あれはRawhide。
柴田：Rawhideか。
村田：RawhideをベースにKondaraでカスタマイズしたのをビルドして。
柴田：SPECファイルを読む。
村田：SPECファイルを読んできてとやるのですけれども、RPMの依存関係の解決の仕組みが
全然行けていないんですよね、生のRPMは。あの当時はyumみたいなものがなかったから、
あのとき、普通のRedHatの人たちはどうしていたのか、分からないですけれども。
Kondaraではその辺をうまいことするために、〓NPH〓という名前のパッケージマネジメント
システムを導入していましたね。
```

**Comment by SugHimsi** [comment]
@miyohide mphならありましたね。@hsbt @mrkn

**Comment by miyohide** [comment]
@shyouhei @mrkn @hsbt すみません、インタビューの参加者（野次馬含み）について教えて下さい。 卜部さん、村田さん、柴田さんの他に後1,2名ほどいるように聞こえるのですが、お名前を教えていただけますか？

**Comment by mame** [comment]
気づかなくてすみません。遠藤（@mame）とそらはー（@sorah）です。どちらも途中から参加してます。

**Comment by mame** [comment]
文字起こししたものを読んでの確認なり訂正なり検閲なりのお手伝いできます。

**Comment by miyohide** [comment]
@mame 情報提供ありがとうございます。また、文字起こし確認のご協力ありがとうございます。以下のプライベートリポジトリにて作業しています。
https://github.com/miyohide/rubima_hotlinks_37
Inviteしましたので、ご確認頂けますと幸いです。

**Comment by mrkn** [comment]
私も招待していただけませんか。

**Comment by miyohide** [comment]
@mrkn inviteしました。

**Comment by mrkn** [comment]
ありがとうございます。

**Comment by mrkn** [comment]
invite していただいたのに何もできてなくてすみません。雑誌の仕事が片付いたので、今週から週末はこちらに取り組もうと思います。

**Comment by publichtml** [comment]
yokohamarbでみよひでさんとお話しました。また終わってないとのことなので手伝いまーす。

**Comment by bengaltigerwhisky** [comment]
@miyohide さん
テープ起こしをお手伝いさせていただけないでしょうか。

**Comment by miyohide** [comment]
@muratiger ありがとうございます。リポジトリにInviteしましたので、ご確認ください。

**Comment by muratiger** [comment]
@miyohide さん
招待ありがとうございます。

**Comment by miyohide** [comment]
@hsbt すみません、見落としていました。テープ起こしがほぼ完了しましたので、脚注や写真を埋めたいと思います。お手数ですが、データいただけますか？
メールなら miyohide @ gmail . com でお願いします。

**Comment by hsbt** [comment]
メールで連絡しました!

**Comment by miyohide** [comment]
テープ起こしと脚注・写真埋めが完了しましたので、本件Closeします。
