### ISSUE TITLE
Ruby on Ice / Ruby User Group Berlin のレポート

### ISSUE THREAD

**Issue by kibitan** [rubima/rubima#457]
こんにちは。[yhara さんのツイート](https://twitter.com/yhara/status/938422223567597568) を見てお手伝いできるかもと思い書き込んでいます。以前、49号にて[インド・バンガロールの記事](http://magazine.rubyist.net/?0049-Bangalore) - #306 を書かせていただきました。

僕は現在ドイツ・ベルリンに住んでおり、来月1月に [Ruby on Ice - January 2018](https://rubyonice.com/2018) というカンファレンスが催行される予定でそのレポートはいかがでしょうか。ただ、1月26日~28日開催なので #453 の記事締切(2018年1月28日) に間に合わないのが気がかりなのと、そもそも行かない可能性もあるのですが。他の案としては、[RUG::B](http://www.rug-b.de/) という2012年からベルリンで毎月開催されているrubyのミートアップがあって、その主催者へのインタビューとかどうでしょうか。

よろしくお願いいたします。

**Comment by miyohide** [comment]
@kibitan ご提案ありがとうございます。 るびま編集部の miyohide です。取り急ぎ、回答します。

- #453 の記事締切は次号のためで、次々号も発行も予定しています。無理して2018年1月28日に合わせる必要はありません。
  - 次々号のリリースは現在決まっていませんので、ご都合の良い時がありましたらお知らせください。調整します。
- RUG::Bの主催者へのインタビューも大変興味深いです。どのように実現するかは今後の相談とさせてください。

**Comment by kibitan** [comment]
@miyohide ありがとうございます！

Ruby on Ice については来月初旬までには行くかどうか決めようと思うので、また相談させてください。
RUG::B については、来月のミートアップに行こうと思っていますので（1/4か1/11の予定）そのときに主催者と話をするか、もっと早めにコンタクトを取ってもいいと思っています。どういうコンテンツ（インタビューの質問内容とか？）にするかなど、ぜひ相談させてください。
