### ISSUE TITLE
0057 号 巻頭言 執筆のお願い

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#460]
@takahashim
こんにちは、るびま編集のみよひでです。すみません、依頼を忘れてました。

0057号のリリースを2018年2月11日 (日)を予定しております（See. #453 ）。

リリースの1週間前の2018年2月4日(日) ごろまでに巻頭言の原稿をいただけると助かります。

よろしくお願いします。

**Comment by takahashim** [comment]
はい、頑張ります！

**Comment by miyohide** [comment]
@takahashim 執筆ありがとうございました。無事、リリースできました。

**Comment by takahashim** [comment]
リリースありがとうございました！
