### ISSUE TITLE
るびま編集者会議を開きたい

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#461]
57号リリースの後に、るびま編集者会議を開きたいと思っています。オンラインで集まる形をとりたいです。日程感は2月中にできたらと思っていますが、3月でも問題ありません。

テーマは、るびまをこのまま存続させるか否かについて。

@ko1 と @takahashim には参加して欲しいです。

**Comment by ko1** [comment]
平日昼以外ということで、

* 夜9時以降ならたいてい。
* 休日は 2/11, 2/12 の daytime （w/ 娘）、2/25 多分全日

なら都合つけられると思います。

**Comment by takahashim** [comment]
オンラインだと2/12か2/17が空いてます。

**Comment by miyohide** [comment]
@ko1 @takahashim 早速の回答ありがとうございます。では、2/12（祝）14:00からでお願いします。

**Comment by ko1** [comment]
この日程で上野のあたりで行うことにしました。
参加される方は、詳細な場所について、私までお問い合わせ下さい。

**Comment by SugHimsi** [comment]
オンラインの上野とは。

**Comment by zophos** [comment]
こごえそうなかもめみつめないていました。

**Comment by miyohide** [comment]
本件追記。2/12（祝）14:00から @ko1 、 @takahashim 、 @miyohide の3名は上野周辺で集まることにしました。他に集まりたいという方は @ko1 までお問い合わせください。オンラインについては参加希望の方が居ましたらベストエフォートで用意します。オンラインで参加希望の方はこちらのIssueにその旨を明記してください。

**Comment by sunaot** [comment]
だいぶ長いことなにもできていないですが声かけてもらったので参加します。

**Comment by znz** [comment]
オンラインで参加希望です。

**Comment by miyohide** [comment]
参加していただいた皆様、本日はありがとうございました。

まずは私が作ったJekyll版るびまをrubima ownerとしました。
https://github.com/rubima/magazine.rubyist.net

移行スケジュール等については、上記のIssueに記します。

**Comment by kakutani** [comment]
閉じちゃったやつに絡んじゃってアレですが、ここに書ける範囲で決まったアクションとか今後の計画(とかやりたいこと)とかがあったら教えてほしいです(参加できなかったけど気にはなっている)。

**Comment by takahashim** [comment]
私の方でとっていた記録は https://github.com/rubima/rubima/wiki/20180212_rubima_meetup.md にあります
