### ISSUE TITLE
るびま on GitHub Page版レビューのお願い

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#462]
先日のるびま編集者会議で、るびまをJekyll化するということになりました。

先日はHerokuで動かしてみたのですが、より手間の掛からないGitHub Page版を動かすことができましたのでご連絡します。
https://rubima.github.io/magazine.rubyist.net/

つきましては、本ページを見ていただき、問題が有りましたら下記リポジトリに対してPull Requestでご連絡いただけますでしょうか。Issueではちょっと対応するのが辛いというのが本音。
https://github.com/rubima/magazine.rubyist.net

とりあえず1週間程度はこのまま表示し、一旦Close。同じ記事が二重に表示されるのを避けたいという思いのためそのように考えていますが、気にし過ぎかもしれません。

実際の移行ですが、連絡いただいた問題の程度によって移行の日程を決めたいと思います。

なお、現在のるびまからはURLが変わります。移行案内を出すのがベストとは思いますが、体力的に自分は無理ですので、対応できる方はご協力をお願いします。

**Comment by hsbt** [comment]
お疲れ様です!

前段に fastly などを置いて

-> fastly(magazine.rubyist.net) -> gh-pages

というようにすれば、URL は今のまま維持、はできそうな雰囲気はあります...

**Comment by miyohide** [comment]
@hsbt ありがとうございます。ざっと探してみると、次の情報が見つかりました。
https://docs.fastly.com/guides/vcl/conditionally-changing-a-url
正規表現を書けばできそうですね。

**Comment by miyohide** [comment]
1週間ほどたちましたので、一旦GitHub Page版はCloseしました。

指摘も特になかったので、来週のどこかでDNSの変更をお願いしようかなと思っています。
