### ISSUE TITLE
移行日程のご相談

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#463]
先日公開したGitHub Page版でも特に指摘はなかったので、HikiからGitHub Page版に移行したいと思います。移行日は3月17日（土）を考えているのですが、ご意見ありましたらコメントください。

- [x] GitHub Page版の公開
- [x] magazine.rubyist.netの向き先変更を前田さんに依頼する
- [x] るりまと地域Ruby会議レポート一覧ページのURL変更Pull Requestを出す

**Comment by miyohide** [comment]
すみません、技術的な問題が発生したので、3/17（土）移行はなしで。

**Comment by miyohide** [comment]
問題は以下の点。

- 現状のままだと、Project GitHub Pagesになってしまうため、URLがmagazine.rubyist.net/magazine.rubyist.netになってしまう。
  - それを避けるためには、rubima.github.ioというリポジトリを作る必要があるが、ここに現状のrubima/magazine.rubyist.netのdocsの内容をコピーする必要がある。
  - このコピーすることは自動化できないかなと思案中（最悪手動でも）。

**Comment by niku** [comment]
docsの内容をコピーするのが必要なのは最初の1回だけですか？
それとも今後も継続的に必要になるのでしょうか．

前者なら手動でコピーするのを手伝います．
後者はTravisCIなどを利用して何かできないですかね．これも手伝います．

手前味噌で恐縮ですが
https://github.com/niku/niku.github.io は
https://github.com/niku/nikulog にCommitをPushしたタイミングで自動的に更新されます．

https://docs.travis-ci.com/user/deployment/pages/ や
nikulog/.travis.yml のこの辺が参考になるかもしれません．
https://github.com/niku/nikulog/blob/9c7e60dc1923b508d89d0af6c20b3e8c92c984b7/.travis.yml#L28-L38

**Comment by miyohide** [comment]
@niku ご協力ありがとうございます。
docsの内容をコピーするのは、今後も継続的に必要になります。ですが、自動化は後でもいいかなと。
自動化についてはTravisCIなどを利用してやりたいのですが、ちょっと手が空かないのでとりあえずコメントとして記させて頂きました。
気が付くのが直前で申し訳ない...

**Comment by niku** [comment]
なるほど．確かに手でやってもいい気がしますね．
こんな感じでしょうか？

1. rubima/rubima.github.io というリポジトリを新しく作る
2. rubima/rubima.github.io を手元に clone する
3. rubima/magazine.rubyist.net を手元に clone する
4. magazine.rubyist.net/docs を rubima.github.io のルートにコピーする
5. rubima.github.io を push する

**Comment by miyohide** [comment]
@niku 手順はそのとおりですね。まずは、rubima/rubima.github.ioリポジトリを作りました。
簡素なindex.htmlをつくったところ、 https://rubima.github.io/ に表示されることを確認しました。

**Comment by miyohide** [comment]
最新版を公開しました。
https://rubima.github.io/

**Comment by miyohide** [comment]
無理にmagazine.rubyist.netにURLを変更しなくても、https://rubima.github.io/のままでいいんじゃないかという気がしてきた。

現在公開している内容は数ヶ月間（次号リリースぐらいまで？）公開して、後はClose。
アクセスランキングトップ10に入っている定番記事と最新号＋トップページにURL変更の案内出せばOKな気がする。

**Comment by znz** [comment]
以下の点から rubima.github.io のままは避けた方が良いかなあと思いました。

- github 以外に移動する可能性もあるので、 github.io は避けたい。(最近 netlify を色々使い始めている)
- io ccTLD は過去に https://mackerel.io/ja/blog/entry/announcement/20170921 のようなこともあったので不安。
- 個人的に GitHub Pages の信頼度が下がることがあったので不安。

**Comment by miyohide** [comment]
ここ1〜2週間ほどいろいろとやってみたのですが、次の2点は解決できませんでした。

- rubima/magazine.rubyist.netが更新されたらrubima/rubima.github.ioにpull requestを出す
  - organizationアカウントにdeploy keyを登録しても、rubima/rubima.github.ioをcloneするときにユーザ名・パスワードの入力が求められる
- URLの変換
  - CDNを使って試してみたが、どうにもこうにも正規表現でQuery Stringがマッチせずに変換されない

先日、たまたま高橋さんとお会いしたので、次の方針で移行をしたいと考えています。

- 現行のるびまの記事にURL変更のお知らせを出す
  - るびまトップページ、57号のトップページ、アクセスランキングTop10ぐらいの記事にURL変更のお知らせを出そうと思います。
  - 今週末ぐらいに作業を行う予定です。
- 移行日は2018年4月21日（土）

**Comment by znz** [comment]
Netlify ならいけるかもと思って [\_redirects](https://www.netlify.com/docs/redirects/)を試してみたのですが、

```
/?0001 /0001/
/?0001-hoge /0001/hoge.html
```

が https://play.netlify.com/redirects で試すと

```
[[redirects]]
from = "/?0001="
to = "/0001/"
status = 301
force = false
[[redirects]]
from = "/?0001-hoge="
to = "/0001/hoge.html"
status = 301
force = false
```

となって、試しにデプロイしてみても `/?0001` でも `/?0001=` でもリダイレクトしてくれなくてダメそうでした。
CDN でもダメということなので、トップページにリダイレクト用の JavaScript を埋め込んでおくしかなさそうです。

**Comment by miyohide** [comment]
トップページにリダイレクト用のJavaScriptを埋め込んでみました。だいたいこんな感じで。

/?0057 にアクセスすると、赤メッセージを出して...
![2018-04-02 22 33 43](https://user-images.githubusercontent.com/601621/38198051-29880c7e-36c6-11e8-87d2-fe561d0ef26f.png)

0.5秒後に移動します。
![2018-04-02 22 34 12](https://user-images.githubusercontent.com/601621/38198063-2ddf93b4-36c6-11e8-86e1-1f5acb0a4be9.png)

github page、JavaScript使えないものかと思っていたのですが、使えたんですね...

**Comment by takahashim** [comment]
リリースありがとうございました！🎉 🎉 🎉

**Comment by ko1** [comment]
🎉

**Comment by miyohide** [comment]
長きに渡る皆様のご協力ありがとうございました。

Closeします。
