### ISSUE TITLE
RubyKaigi 2018直前特集号について

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#464]
昨年やりましたRubyKaigi直前特集号を今年もできればやりたいなと思っています。

去年は、 @takahashim さんの「タイムテーブル徹底解説」が非常に好評、また、発表内容の事前情報もよかったという声があったそうです。

問題は記事集めなのですが、拡散等でご協力いただけませんでしょうか？（発表内容の事前情報募集については、 @ko1 さんにお願いすればよい？）

**Comment by miyohide** [comment]
1社から寄稿のお話を頂きましたので、やるほうこうで動きます。

5月ぐらいにページを用意して、そこに対してpull requestを送ってもらう形にしようかと思っています。

**Comment by ko1** [comment]
今年は ML あるのかなぁ。

**Comment by miyohide** [comment]
@ko1 発表者用のMLのことでしょうか？無ければ登壇者への直接のご連絡はなしでいいかなと思っています。すみません。

**Comment by miyohide** [comment]
今年もRejectKaigi 2018というイベントの中で「RubyKaigi 2018タイムテーブル徹底解説」が行われるようです。

昨年の直前特集号でも好評だったので、できれば記事化したい（音声の文字起こしぐらい？）と思っているのですが、協力して頂ける方いますか？

**Comment by niku** [comment]
はい．どの程度というと，少しかもしれませんが手伝います．

**Comment by miyohide** [comment]
本件ですが、私が右腕を怪我しまして直前特集号の作成について動けなくなりました。

今のところ2社よりお話を頂いているのですが、どなたか引き継ぎもしくはご対応頂けませんでしょうか。

**Comment by ko1** [comment]
やります！　ってちょっと忙しくて言えなさそうなのが弱いんですが、github のフローをよく知らないのですが、表紙を用意して、PR をマージするだけ？

**Comment by zunda** [comment]
体調依存で申し訳ないんですが1日最大1時間くらい手を動かせそうです。作業内容等どこかにまとまってますか？

**Comment by zunda** [comment]
> お手数おかけします。https://github.com/rubima/magazine.rubyist.net で2018年版のページを作りjekyll buildした結果を https://github.com/rubima/rubima.github.io にPull Requestしてマージしていただければと。

https://twitter.com/miyohide/status/995929222521667585

作業中です

**Comment by miyohide** [comment]
@zunda ご協力ありがとうございます。さきほど、rubimaのteamにinviteしましたので、メールをご確認ください。

**Comment by zunda** [comment]
さっそくありがとうございます! 少なくとも rubima/magazine.rubyist.net と rubima/rubima.github.io で書き込み権限があるのを確認しました。作業自体はこちらの夜になってから続行します。

**Comment by mata0514** [comment]
@ご担当者さま

初めまして、SmartHRの勝股と申します。
みよひでさんにこちらの issue を共有いただきました。

RubyKaigi直前特集号について、掲載のご相談です。

弊社 SmartHR は RubyKaigi2018 にスポンサーとして出展予定です。
RubyKaigi2018をより盛り上げられたらと思い、
以下 RubyKaigi にまつわる記事とイベントを公開しました。

-  [【保存版】自腹でつくる仙台グルメマップ #RubyKaigi 2018 - SmartHR Tech Blog](http://tech.smarthr.jp/entry/2018/05/10/192540)
 

- [SmartHRビアバッシュ@RubyKaigi 2018](https://smarthr.connpass.com/event/87674/)

もし可能でしたら掲載をお願いできればと思います。
よろしくお願いします。

**Comment by ko1** [comment]
掲載、ってのは、るびま特集号表紙からリンク張る感じですかね？

**Comment by ko1** [comment]
@takahashim プログラム解説って今年はやりますか？

**Comment by zunda** [comment]
@ko1 RubyKaigi2017に倣うとそのようです。これから作業します。

**Comment by takahashim** [comment]
@ko1 はい、何かしら書くつもりです！

**Comment by zunda** [comment]
@mata0514 さま、

記事とイベントのお知らせをありがとうございます。下記のURLに公開しました。お待たせしました。

修正して欲しい点などありましたらお気軽にお知らせください！

http://magazine.rubyist.net/articles/prerubykaigi2018/preRubyKaigi2018-index.html

**Comment by m-nakamura145** [comment]
@miyohide さんよりご紹介いただきました。株式会社トレタの中村と申します。

るびまのRubyKaigi直前特集号に弊社tech blogへのリンクのご相談です。

弊社は今回のRubyKaigi2018にスポンサーとして出展予定です。また、今回RubyKaigi2018を盛り上げるために、会場周辺の仙台のお店を予約できるアプリを作りましたので、そのご紹介を行うためのテックブログを執筆予定です。

執筆後、可能でしたらるびまから弊社tech blogへのリンクを張って頂くことは可能でしょうか？

**Comment by ko1** [comment]
良いんじゃ無いでしょうか!

https://github.com/rubima/magazine.rubyist.net/blob/master/articles/preRubyKaigi2018/_posts/2018-05-01-preRubyKaigi2018-index.md

への PR でも良い？ @zunda

**Comment by zunda** [comment]
ここへのお知らせでもPRでもどちらでも問題ありません。よろしくお願いします！

**Comment by m-nakamura145** [comment]
お待たせ致しました。ブログを公開してPull Requestを作成しました！よろしくお願いします！
https://github.com/rubima/magazine.rubyist.net/pull/51

**Comment by zunda** [comment]
@m-nakamura145 さん、ありがとうございます！単語前後のスペースの調整だけさせていただき、 https://magazine.rubyist.net/articles/prerubykaigi2018/preRubyKaigi2018-index.html に公開しました。もし修正点などありましたらお気軽にお知らせください。

**Comment by zunda** [comment]
@自分

- [ ] https://twitter.com/rechiba3/status/999493922832318465 へのリンクを追加する

**Comment by zunda** [comment]
- [ ] https://twitter.com/thatblue_plus/status/999555854956314624 へのリンクを追加する

**Comment by yui-knk** [comment]
2日目に発表する金子と申します。
こんな話をします。という文章を書きましたので、リンクを貼ってください。よろしくお願いします。
https://gist.github.com/yui-knk/169fc1ae1fc8c88547cc6ee2bca4e351

**Comment by zunda** [comment]
@yui-knk さん、ありがとうございます！リンクを追加しました。https://magazine.rubyist.net/articles/prerubykaigi2018/preRubyKaigi2018-index.html をご確認ください。

**Comment by mata0514** [comment]
@zunda 遅くなりましたがこちらありがとうございました！

**Comment by hsbt** [comment]
こんにちは、GMO ペパボからやってきた柴田です。

社内ブログに RubyKaigi の事前特集号を書きましたので掲載していただけると幸いです。

https://tech.pepabo.com/2018/05/28/pre-rubykaigi-2018/

**Comment by zunda** [comment]
@hsbt さん、ありがとうございます！リンクを掲載しました。

講演内容のご紹介からもリンクを掲載してあります。こちらについては、もし、より詳しい予習資料をみつけた場合には差し替えさせていただこうと考えています。

https://magazine.rubyist.net/articles/prerubykaigi2018/preRubyKaigi2018-index.html

**Comment by koichiro** [comment]
@zunda こんにちは。Speeeの大場です。

直前で大変恐縮なのですがSpeeeのRubyKaigi活動まとめをブログにしたのでリンクをお願いできまでしょうか 🙇 

http://tech.speee.jp/entry/2018/05/30/144944

**Comment by zunda** [comment]
@koichiro -san、お知らせいただきありがとうございます！  https://magazine.rubyist.net/articles/prerubykaigi2018/preRubyKaigi2018-index.html からリンクしました。もし修正点などお気づきになりましたらお知らせください。

**Comment by miyohide** [comment]
@zunda さん、大変お世話になりました。毎日の更新助かりました。

**Comment by niku** [comment]
誤って閉じてしまいました。すみません。reopenしておきました？

**Comment by zunda** [comment]
おかげさまでリモートから参加してる感を感じることができました。こちらこそありがとうございました! 今週いっぱいくらいは新しい記事を見つけたらリンクを追加しようかと思っています。

**Comment by miyohide** [comment]
@zunda リンク追加の方針、了解しました。終了しましたら、お手数ですが本Issueを閉じて頂けますと助かります。

**Comment by zunda** [comment]
そろそろ打ち止めの感じですので、こちらのIssueを閉じ、rubima/magazine.rubyist.net rubima/rubima.github.io のrk2018ブランチを削除します。たいへんたいへん楽しませていただきました。ありがとうございました!

今後とも必要があれば記事の更新修正をしますのでお知らせください。
