### ISSUE TITLE
旧るびまサーバの停止について

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#465]
Markdown化が完了しとりあえずうまく動いている感じですので、旧るびまサーバについて以下のように考えています。ご意見いただけますと助かります。

- 4/29（日）にHTTPサーバの停止
  - HTTPサーバプロセスを止めるだけで、サーバとしては活かしておく
- 5/20（日）ぐらいにさくらVPS解約
  - 日付に特に思いはないが、移行して一ヶ月経過したらあらかたの問題も出尽くしているだろうという考え
  - 実際に解約作業を実施するのは @takahashim さんなので、ご都合に合わせて（RubyKaigi直前で難しいようであれば、6月でもOKです）

特になければ、今週末にHTTPサーバの停止を行います。

**Comment by miyohide** [comment]
早速の確認ありがとうございます。
了解しました。さくらVPS解約日付については特に思いはないので、先になるのであればそれでOKです。

**Comment by miyohide** [comment]
特に反対意見もなかったので、旧るびまサーバのHTTPは止めました。

なお、解約まで定期的に`apt update && apt upgrade`は行います。

**Comment by miyohide** [comment]
解約されたようなので、本件はClose

**Comment by ko1** [comment]
お疲れ様でした！！
