### ISSUE TITLE
沖縄Ruby会議02レポート

### ISSUE THREAD

**Issue by Yuta1122** [rubima/rubima#471]
沖縄Ruby会議02のレポート作成issueを起こします。
レポート担当は@Yuta1122他2名です。0059号で出したいです。
開催日は2018.3/10(土)でした。よろしくお願い致します。

**Comment by miyohide** [comment]
@Yuta1122 お世話になります。るびま編集部のmiyohideです。

0059号で出したい旨、了解しました。現在0059号の発行スケジュールは具体的に立てていません。
早くて2018年12月、遅くて2019年2月ぐらいを考えていますが具体的な日程はまだです。
取り急ぎ、上記を一つの目安として考えてください。

記事の書き方については、以下にまとめています。
https://github.com/rubima/magazine.rubyist.net/wiki/HowToNewRelease
なにかご質問がありましたら、ご連絡いただけますと助かります。

**Comment by miyohide** [comment]
@Yuta1122  #473 に記しましたが、次号のるびまのリリーススケジュールを以下のように考えています。

    記事申し込み・概要締切：2018年12月23日（日） ← だいたいの掲載記事を決める。中間フォロー。
    記事の締切：2019年1月13日（日）← 記事の〆切。基本はここがデッドライン
    校正完了・リリース：2019年1月27日（日）

お忙しいところ恐縮ですが、以下のスケジュールで記事の提出をお願いできますでしょうか。

**Comment by Yuta1122** [comment]
@miyohide ご連絡有難うございます。
記事の申し込み締切日、確認致しました。締め切りまでに提出させていただきます。
