### ISSUE TITLE
Rails Girls Tokyo 10thの開催レポート

### ISSUE THREAD

**Issue by emorima** [rubima/rubima#472]
[Rails Girls Tokyo 10th](http://railsgirls.com/tokyo) コーチの @katorie さんが書いてくれるとのことなので、issue 作りました！

**Comment by miyohide** [comment]
@emorima @katorie お世話になります。るびま編集部のmiyohideです。

Rails Girls Tokyo 10thの開催レポート寄稿のお話、ありがとうございます。今週末開催のようですね。成功をお祈り申し上げます。

さて、直近のるびまリリース予定は具体的には立っていません。早くて2018年12月、遅くて2019年2月ぐらいを考えていますが具体的な日程は未定です。
取り急ぎ、上記を一つの目安として考えてください。ある程度、掲載記事のめどが立ちましたら再度ご連絡いたします。

記事の書き方については、以下にまとめています。
https://github.com/rubima/magazine.rubyist.net/wiki/HowToNewRelease
なにかご質問がありましたら、ご連絡いただけますと助かります。

**Comment by miyohide** [comment]
@katorie @emorima  #473 に記しましたが、次号のるびまのリリーススケジュールを以下のように考えています。

    記事申し込み・概要締切：2018年12月23日（日） ← だいたいの掲載記事を決める。中間フォロー。
    記事の締切：2019年1月13日（日）← 記事の〆切。基本はここがデッドライン
    校正完了・リリース：2019年1月27日（日）

お忙しいところ恐縮ですが、以下のスケジュールで記事の提出をお願いできますでしょうか。

**Comment by miyohide** [comment]
@katorie @emorima お世話になります。記事の進捗はいかがでしょうか。来年1月13日（日）の締切までに記事が出せるかどうかをご連絡いただけますと助かります。

**Comment by katorie** [comment]
@emorima @miyohide 大変申し訳ありません！見落としていました 🙇‍♀️ 🙇‍♀️ 🙇‍♀️ 
締め切りを1月13日（日）で把握しました。守ります！！

**Comment by miyohide** [comment]
@katorie よろしくお願いします。

**Comment by miyohide** [comment]
@katorie すみませんが、1/13までに記事をいただけませんでしたので59号への掲載は見送りとさせてください。

**Comment by katorie** [comment]
@miyohide すみません！PRを出してからこのコメントに気づきました 🙇‍♀️ 
PRの方でもコメントしていますが、後日60号用に必要箇所を訂正いたします。

**Comment by miyohide** [comment]
@katorie せっかく提出いただいたので、取り込みます。確認少々お待ちください。
