### ISSUE TITLE
『現場で使えるRuby on Rails5速習実践ガイド』に関する記事執筆依頼

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#474]
@tatsuosakurai RubyWorld Conferenceの場にてお話させていただきましたが、『現場で使えるRuby on Rails5速習実践ガイド』に関する記事をるびまに書いていただきたいです。

記事の内容は書籍紹介を考えていますが、他に書きたい内容がありましたら変更していただいて問題ありません。

なお、スケジュールについてですが、以下のように考えています。

    記事申し込み・概要締切：2018年12月23日（日） ← だいたいの掲載記事を決める。中間フォロー。
    記事の締切：2019年1月13日（日）← 記事の〆切。基本はここがデッドライン
    校正完了・リリース：2019年1月27日（日）

お忙しいところ恐縮ですが、ご協力いただけますでしょうか。

**Comment by tatsuosakurai** [comment]
@miyohide オファーありがとうございます！チームで担当者決まったので、間に合うように進めたいと思います！！

**Comment by miyohide** [comment]
快諾ありがとうございます。では、よろしくお願いします。

**Comment by miyohide** [comment]
@tatsuosakurai お世話になります。記事の進捗はいかがでしょうか。来年1月13日（日）の締切までに記事が出せるかどうかをご連絡いただけますと助かります。

**Comment by tatsuosakurai** [comment]
@miyohide ご確認ありがとうございます！1/13(日) の締切までに出せそうです！

**Comment by miyohide** [comment]
@tatsuosakurai 了解しました。よろしくお願いします。
