### ISSUE TITLE
『ゼロからわかる Ruby 超入門』に関する記事執筆依頼

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#475]
@igaiga RubyWorld Conferenceの場にてお話いただきました、『ゼロから分かるRuby超入門』に関する記事をるびまに書いていただきたいです。

記事の内容は書籍紹介を考えていますが、他に書きたい内容がありましたら変更していただいて問題ありません。プレゼント企画もご希望でしたらお申し付けください。

なお、スケジュールについてですが、以下のように考えています。

    記事申し込み・概要締切：2018年12月23日（日） ← だいたいの掲載記事を決める。中間フォロー。
    記事の締切：2019年1月13日（日）← 記事の〆切。基本はここがデッドライン
    校正完了・リリース：2019年1月27日（日）

お忙しいところ恐縮ですが、ご協力いただけますでしょうか。

**Comment by igaiga** [comment]
@miyohide ありがとうございます！執筆します！
書き方はTokyuの記事と同じくMarkdonwで書いてPRで良いでしょうか？

**Comment by igaiga** [comment]
そろそろ本気出す！

**Comment by miyohide** [comment]
@igaiga すみません、見落としてました。
記事については、 rubima/magazine.rubyist.net に対してPull Requestを出してください。
Markdownで書いてOKですが、いくつか注意事項がありますので、
https://github.com/rubima/magazine.rubyist.net/wiki/HowToNewRelease
を参照していただけますと幸いです。
