### ISSUE TITLE
mruby/cに関する記事の執筆依頼

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#476]
@kishima RubyWorld Conferenceの場にてお話させていただきましたが、mruby/cに関する記事をるびまに書いていただきたいです。

なお、スケジュールについてですが、以下のように考えています。

    記事申し込み・概要締切：2018年12月23日（日） ← だいたいの掲載記事を決める。中間フォロー。
    記事の締切：2019年1月13日（日）← 記事の〆切。基本はここがデッドライン
    校正完了・リリース：2019年1月27日（日）

お忙しいところ恐縮ですが、ご協力いただけますでしょうか。

**Comment by kishima** [comment]
みよひでさん

お誘いありがとうございます！
はい。自分なんかでいいのだろうか、という思いもありつつ、せっかくの機会なのでお引き受けしたいと思います。
事前に伝えておくべき情報や、書き方のガイドライン等あれば教えて頂けると助かります。
よろしくおねがいします。

kishima
kishima7@gmail.com

2018年11月5日(月) 20:34 miyohide <notifications@github.com>:

**Comment by miyohide** [comment]
@kishima 快諾ありがとうございます。
記事の書き方については、以下にまとめています。
https://github.com/rubima/magazine.rubyist.net/wiki/HowToNewRelease

事前にお伝えして頂く情報は特にありません。12/23（日）をめどに、記事の概要ができていればOKです。都合が悪くなり、記事の執筆が難しい状況になりましたらお知らせいただけますと助かります。

**Comment by kishima** [comment]
了解しました！
12/23頃に概要お送りできるよう進めます。

2018年11月6日(火) 21:45 miyohide <notifications@github.com>:

**Comment by miyohide** [comment]
@kishima お世話になります。記事の進捗はいかがでしょうか。来年1月13日（日）の締切までに記事が出せるかどうかをご連絡いただけますと助かります。

**Comment by kishima** [comment]
kishimaです。

遅くなってなってすみません、
まだ本編はかけていないのですが、以下のブログ記事を膨らませる内容にする予定です。
https://silentworlds.info/2018/05/26/post-188/
年末年始は時間が取れるので、冬休み中に仕上げたいと考えています。

以下のような構成を考えています。
------
タイトル案
「mruby/cで始めるオリジナルIoTデバイス作り」

導入
目的
mruby/cでIOP
mruby/cとは
特徴
mrubyとの違い
開発環境の構築
WioLTEの説明
SoracomSIMの説明
実装方法
mruby/cのダウンロード
C拡張の書き方
LTEでWebサーバにデータを送るAPIの作成
動かし方
WioLTE実機への転送
動作チェック
まとめ

よろしくお願いします！

2018年12月24日(月) 22:57 miyohide <notifications@github.com>:

**Comment by miyohide** [comment]
@kishima 了解しました。よろしくお願いします。

**Comment by miyohide** [comment]
@kishima すみませんが、1/13までに記事をいただけませんでしたので59号への掲載は見送りとさせてください。

**Comment by kishima** [comment]
みよひでさん

大変申し訳ありません、もう少しのところだったのですが、寝落ちしてしまいました。。。
もう遅いかとは思いますが今晩中に一度PullRequest投げたいと思います。


2019年1月14日(月) 0:14 miyohide <notifications@github.com>:

**Comment by kishima** [comment]
もし不要ということであれば、いつでも次回に寄稿できるように準備しておきます。
よろしくお願いいたします。

2019年1月14日(月) 10:47 kishima <kishima7@gmail.com>:

**Comment by miyohide** [comment]
@kishima せっかくPull Requestとして出していただいたので取り込みます。少々お待ちください。

**Comment by kishima** [comment]
ご配慮頂きありがとうございます！
お手数お掛けして申し訳ないです。

2019年1月15日(火) 15:06 miyohide <notifications@github.com>:
