### ISSUE TITLE
Ovto の紹介記事執筆の件

### ISSUE THREAD

**Issue by miyohide** [rubima/rubima#477]
@yhara RubyWorld Conferenceの場にてお話させていただきましたが、記事執筆していただける件、最新号は以下のスケジュールで作業を進めようかと考えています。

    記事申し込み・概要締切：2018年12月23日（日） ← だいたいの掲載記事を決める。中間フォロー。
    記事の締切：2019年1月13日（日）← 記事の〆切。基本はここがデッドライン
    校正完了・リリース：2019年1月27日（日）

このスケジュールで問題なければ、記事執筆をお願いしたいですが、いかがでしょうか。

**Comment by yhara** [comment]
@miyohide はい、問題ありません。[Ovto](https://qiita.com/yhara/items/07eeb2c165e35964db76) の紹介記事を書こうと思っています。

**Comment by miyohide** [comment]
ありがとうございます。Issueのタイトルを変更しました。

**Comment by miyohide** [comment]
@yhara お世話になります。記事の進捗はいかがでしょうか。来年1月13日（日）の締切までに記事が出せるかどうかをご連絡いただけますと助かります。

**Comment by yhara** [comment]
@miyohide お疲れさまです。記事自体はあんまり進捗してないですが、それまでに済ませたいと思っていた作業(0.3.0リリース)は終えたので、何かしらは出せると思っています。よろしくお願いします。

**Comment by miyohide** [comment]
@yhara 0.3.0のリリースお疲れ様でした。記事、楽しみにしています。

**Comment by miyohide** [comment]
@yhara すみませんが、1/13までに記事をいただけませんでしたので59号への掲載は見送りとさせてください。

**Comment by yhara** [comment]
@miyohide わーすみません。22分遅れの[提出](https://github.com/rubima/magazine.rubyist.net/pull/147)でしたが、RubyKaigiより前に公開してしまいたいので、今号に入れていただけないでしょうか。レンダリング結果、命名規則(`articles/0059/0059-Ovto.html`)等手元で確認済みなのであまりお手間を取らせないと思います。

よろしくお願いします。

**Comment by miyohide** [comment]
@yhara 了解しました。取り込みます。確認は少々お時間をください。
