### ISSUE TITLE
Rails Girls Sendai 1stの開催レポート

### ISSUE THREAD

**Issue by emorima** [rubima/rubima#479]
次号のるびまのスケジュール
```
記事申し込み・概要締切：2018年12月23日（日） ← だいたいの掲載記事を決める。中間フォロー。
記事の締切：2019年1月13日（日）← 記事の〆切。基本はここがデッドライン
校正完了・リリース：2019年1月27日（日）
```

記事の書き方については、以下にまとめられているとのこと。
https://github.com/rubima/magazine.rubyist.net/wiki/HowToNewRelease

**Comment by miyohide** [comment]
@emorima よろしくお願いします。

**Comment by emorima** [comment]
記事は、 @okuramasafumi  が書きます！

**Comment by okuramasafumi** [comment]
よろしくお願いします！

**Comment by miyohide** [comment]
@okuramasafumi すみませんが、1/13までに記事をいただけませんでしたので59号への掲載は見送りとさせてください。

**Comment by okuramasafumi** [comment]
@miyohide 申し訳ありません、なぜか締切を1月16日だと思い込んでおりました、申し訳ありません…
改めて、60号への記事を書かせていただきたいと思います。よろしくお願いいたします。

**Comment by miyohide** [comment]
@okuramasafumi 16日までに提出いただけるのでしたら、取り込む方向で動きたいと思います。よろしくお願いします。

**Comment by okuramasafumi** [comment]
@miyohide かしこまりました、16日までに提出いたします！

**Comment by okuramasafumi** [comment]
@miyohide ありがとうございます！
