### ISSUE TITLE
Rails Girls Tokyo 12thの開催レポート 

### ISSUE THREAD

**Issue by emorima** [rubima/rubima#481]
コーチの @ave-hikari さんが書いてくれるとのことなので、issue 作りました！

記事の書き方については、以下にまとめられているとのこと。
https://github.com/rubima/magazine.rubyist.net/wiki/HowToNewRelease

**Comment by miyohide** [comment]
@emorima @ave-hikari 
お世話になります。るびま編集部のmiyohideです。Rails Girls Tokyo 11th、開催お疲れさまでした。Twitterなどで楽しそうな雰囲気が伝わってきました。

さて、寄稿のお話、ありがとうございます。大変助かります。ただ、現在、次号のるびまについては発行日を具体的に立てられていない状態です。漠然と6月～7月ぐらいを考えていますが、まだ何も動けていません。

この時期までに掲載してほしいなど何か希望はありますでしょうか。

**Comment by emorima** [comment]
@miyohide 
特に掲載希望時期はありません。

RubyKaigi直前号が４月に出るのかな？と予想していたのですが、
直前号にはRubyKaigi以外の記事の掲載はないようなので、
次号の時期で大丈夫です！ :)

**Comment by miyohide** [comment]
@emorima 了解しました。

**Comment by miyohide** [comment]
@emorima @ave-hikari 次回のるびまレポートを8/18（日）に出そうかと考えています。つきましては、8/11（日）までにレポートをいただければと考えております。スケジュールとして問題ありませんでしょうか。

**Comment by emorima** [comment]
@miyohide すみません、8/2, 3で 12thを開催するので、12th開催レポートに変更させて頂いてもよいでしょうか？

8/11(日) までにレポート提出できるように対応します！

**Comment by miyohide** [comment]
@emorima  12th開催レポートへの変更、問題ありません。

**Comment by emorima** [comment]
@miyohide ご確認ありがとうございます！では、期日までにPRお送りさせて頂きます！

**Comment by miyohide** [comment]
Issueの閉じ忘れ。
