### ISSUE TITLE
TokyuRubyKaigi13開催レポート

### ISSUE THREAD

**Issue by igaiga** [rubima/rubima#482]
- レポート担当: @igaiga 
- イベントページ https://tokyurubykaigi.github.io/tokyu13/
- 開催日: 2019年6月29日

今回も寄稿させていただければと思います。よろしくお願いいたします。

**Comment by igaiga** [comment]
@miyohide こちら、勝手に作ってしまってよかったでしょうか？問題なければまた今回もよろしくお願いいたします。

**Comment by miyohide** [comment]
@igaiga すみません、見落としてました。できればこちらにIssueを立てていただけますと助かります。
https://github.com/rubima/magazine.rubyist.net/issues

**Comment by igaiga** [comment]
@miyohide どもです！そちらへ立てましたのでこちらはクローズしますね。
https://github.com/rubima/magazine.rubyist.net/issues/204
