### ISSUE TITLE
名古屋Ruby会議04 レポート

### ISSUE THREAD

**Issue by eitoball** [rubima/rubima#483]
@huequica が書いてくれる予定です。

記事の書き方: https://github.com/rubima/magazine.rubyist.net/wiki/HowToNewRelease

**Comment by miyohide** [comment]
@eitoball @huequica Issue作成ありがとうございます。リポジトリ一本化のため、 https://github.com/rubima/magazine.rubyist.net/issues にIssueを立てていただけると助かります。

**Comment by huequica** [comment]
立てましたのでこちらはCloseをお願いします。
