### ISSUE TITLE
Rails Girls Nagano 1stの開催レポート

### ISSUE THREAD

**Issue by emorima** [rubima/rubima#484]
Nagano 1stでるびまに開催記事書きたいという話があり、issue作りました。
オーガナイザーの @cobachie さんが、取りまとめてくれると思います。

記事の書き方については、以下にまとめられているとのこと。
https://github.com/rubima/magazine.rubyist.net/wiki/HowToNewRelease

**Comment by miyohide** [comment]
@emorima @cobachie 寄稿のお話ありがとうございます。お手数ですが、リポジトリ一本化のため、 https://github.com/rubima/magazine.rubyist.net/issues にIssueを立てていただけますでしょうか。

**Comment by emorima** [comment]
@miyohide リポジトリ間違えていましたか...すみません！

たてました！

**Comment by miyohide** [comment]
対応ありがとうございます。
