### ISSUE TITLE
RubyConfTHの参加レポート

### ISSUE THREAD

**Issue by 3150** [rubima/rubima#485]
９月にバンコクで行われた第一回RubyConfTHに参加してきました。
第一回目ということもあり、バンコクからの参加者よりも国外の参加者の方が多かったように感じました。
諸用で初日しか参加できていませんが、参加レポートを寄稿させてください 🙇 
掲載希望時期は特にありません。

**Comment by miyohide** [comment]
@takaaki-kanetsuki 寄稿のお話ありがとうございます。寄稿は歓迎ですので、記事ができましたら  rubima/magazine.rubyist.net にPull Requestを出してください。
記事の書き方については、以下を参照してください。
https://github.com/rubima/magazine.rubyist.net/blob/master/README.md

なお、管理の都合上、 Issueを https://github.com/rubima/magazine.rubyist.net/issues に立てていただけると助かります。

**Comment by 3150** [comment]
こちら対応が遅れてしまい、Issueを放置する形になってしまい、大変申し訳ございませんでした。記事作成資料不足などもあり、closeさせていただきたいと思います。
